export const SCRIPT_STYLES = [
  {
    id: "mrbeast",
    name: "MrBeast Mode",
    icon: "💥",
    tagline: "Insane stakes · retention hooks · epic energy",
    bgClass: "from-yellow-500/15 to-orange-500/15",
    borderClass: "border-yellow-500/30",
    accentColor: "#f59e0b",
    defaults: {
      platform: "YouTube Long",
      type: "Full Script",
      style: "Shock",
      tone: "High energy, dramatic, over-the-top",
      audience: "Everyone (13–35)",
    },
  },
  {
    id: "tiktok",
    name: "TikTok Viral",
    icon: "📱",
    tagline: "Fast hooks · trend-aware · curiosity-driven",
    bgClass: "from-pink-500/15 to-purple-500/15",
    borderClass: "border-pink-500/30",
    accentColor: "#ec4899",
    defaults: {
      platform: "TikTok",
      type: "Hook + Script Combo",
      style: "Curiosity Gap",
      tone: "Casual, direct, Gen Z energy",
      audience: "Gen Z (16–24)",
    },
  },
  {
    id: "finance",
    name: "Finance Edu",
    icon: "💰",
    tagline: "Authority · data · simple breakdowns",
    bgClass: "from-green-500/15 to-emerald-500/15",
    borderClass: "border-green-500/30",
    accentColor: "#10b981",
    defaults: {
      platform: "YouTube Shorts",
      type: "Full Script",
      style: "Authority",
      tone: "Confident, educational, trustworthy",
      audience: "Adults (25–45)",
    },
  },
  {
    id: "storytelling",
    name: "Story Arc",
    icon: "🎭",
    tagline: "3-act structure · emotional · character-driven",
    bgClass: "from-blue-500/15 to-cyan-500/15",
    borderClass: "border-blue-500/30",
    accentColor: "#3b82f6",
    defaults: {
      platform: "Instagram Reels",
      type: "Full Script",
      style: "Storytelling",
      tone: "Emotional, authentic, vulnerable",
      audience: "Broad (18–40)",
    },
  },
  {
    id: "comedy",
    name: "Comedy Skit",
    icon: "😂",
    tagline: "Setup · punchline · relatable chaos",
    bgClass: "from-orange-500/15 to-red-500/15",
    borderClass: "border-orange-500/30",
    accentColor: "#f97316",
    defaults: {
      platform: "TikTok",
      type: "Full Script",
      style: "Shock",
      tone: "Funny, sarcastic, self-aware",
      audience: "Millennials & Gen Z",
    },
  },
  {
    id: "product",
    name: "Product Drop",
    icon: "🛒",
    tagline: "FOMO · social proof · urgency that converts",
    bgClass: "from-violet-500/15 to-purple-500/15",
    borderClass: "border-violet-500/30",
    accentColor: "#8b5cf6",
    defaults: {
      platform: "Instagram Reels",
      type: "Viral Hook",
      style: "Curiosity Gap",
      tone: "Excited, persuasive, aspirational",
      audience: "Shoppers (18–45)",
    },
  },
  {
    id: "tutorial",
    name: "Tutorial Pro",
    icon: "🎓",
    tagline: "Step-by-step · clear value · strong CTAs",
    bgClass: "from-indigo-500/15 to-blue-500/15",
    borderClass: "border-indigo-500/30",
    accentColor: "#6366f1",
    defaults: {
      platform: "YouTube Shorts",
      type: "Full Script",
      style: "Authority",
      tone: "Clear, instructional, helpful",
      audience: "Learners (all ages)",
    },
  },
  {
    id: "custom",
    name: "Custom",
    icon: "✨",
    tagline: "Full control — you decide everything",
    bgClass: "from-white/5 to-white/8",
    borderClass: "border-white/20",
    accentColor: "#7A3BFF",
    defaults: {},
  },
];
