/**
 * /ai-fruit-story-maker — SEO landing page
 *
 * TARGET KEYWORDS (primary → long-tail):
 *   "ai fruit story"
 *   "ai fruit story generator"
 *   "fruit drama video maker"
 *   "create viral fruit videos online"
 *   "ai tiktok fruit drama video"
 *   "fruit story video generator free"
 *   "make ai fruit drama videos"
 */

import { useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { Check } from "lucide-react";

const PRESETS = [
  { src: "/viral-builder/ai-fruit/presets/cheating.webp",    label: "Cheating Reveal",    views: "4.7M" },
  { src: "/viral-builder/ai-fruit/presets/baby.webp",        label: "Baby Surprise",       views: "3.1M" },
  { src: "/viral-builder/ai-fruit/presets/secret-twin.webp", label: "Secret Twin",         views: "2.9M" },
  { src: "/viral-builder/ai-fruit/presets/cheats-back.webp", label: "Revenge Comeback",    views: "2.1M" },
  { src: "/viral-builder/ai-fruit/presets/kicked-out.webp",  label: "Kicked Out",          views: "1.8M" },
  { src: "/viral-builder/ai-fruit/presets/custom.webp",      label: "Your Own Story",      views: "∞" },
];

const CHARACTERS = [
  { src: "/viral-builder/ai-fruit/characters/bossmango.png",       name: "Boss Mango" },
  { src: "/viral-builder/ai-fruit/characters/orangemom.png",       name: "Orange Mom" },
  { src: "/viral-builder/ai-fruit/characters/hotpeach.webp",       name: "Hot Peach" },
  { src: "/viral-builder/ai-fruit/characters/banana.png",          name: "Banana" },
  { src: "/viral-builder/ai-fruit/characters/strawberrymom.png",   name: "Strawberry Mom" },
  { src: "/viral-builder/ai-fruit/characters/gangsterpineapple.png", name: "Gangster Pineapple" },
  { src: "/viral-builder/ai-fruit/characters/ananasgirl.png",      name: "Ananas Girl" },
  { src: "/viral-builder/ai-fruit/characters/orangekid.webp",      name: "Orange Kid" },
];

const HOW_STEPS = [
  { n: "01", title: "Write one sentence",      desc: "Describe your drama idea — 'A fruit finds out their partner is hiding a secret.' That's it. Zyvo handles the rest." },
  { n: "02", title: "Pick your characters",    desc: "Choose 2–3 fruit characters for your story. Each has a locked visual identity that stays consistent across every scene." },
  { n: "03", title: "AI writes & generates",  desc: "Zyvo plans a full multi-scene story arc, writes the script, and generates every scene as a cinematic 3D image." },
  { n: "04", title: "Animate & post",          desc: "Hit Animate. Your fruit characters start talking in English with mouth-synced dialogue. Download and post in minutes." },
];

const FAQS = [
  { q: "What is an AI Fruit Story?", a: "An AI Fruit Story is a short-form cinematic drama video featuring animated 3D fruit characters acting out emotional storylines — cheating reveals, secret twins, baby surprises. The format is one of the highest-performing on TikTok and Instagram Reels, hitting millions of views per week." },
  { q: "How long does it take to make a fruit drama video?", a: "From your first prompt to a downloadable video in under 5 minutes. You type one sentence, choose characters, and Zyvo generates all scenes and animates them with talking characters automatically." },
  { q: "Do I need editing or design skills?", a: "None. Zyvo is 100% automated. No timeline editing, no voiceover recording, no design software. Just your prompt and a click." },
  { q: "Can I make 1-minute long fruit videos?", a: "Yes. Choose the 60-second story length and Zyvo plans a full 10-scene story arc with escalating drama, generates every scene, and animates them all into a complete 60-second video ready to post." },
  { q: "What drama styles can I create?", a: "Cheating reveals, baby surprises, secret twin twists, revenge comebacks, kicked-out stories, and fully custom ideas. Each preset is optimized for maximum viewer retention." },
  { q: "Do the characters speak in the videos?", a: "Yes. Every animated scene includes mouth-synced English dialogue generated by AI. Characters speak naturally with appropriate emotion for the scene." },
];

export default function AIFruitStoryLanding() {
  const navigate  = useNavigate();
  const videoRef  = useRef(null);

  useEffect(() => {
    document.title = "AI Fruit Story Generator — Make Viral Fruit Drama Videos in Minutes | Zyvo";

    // Set meta description
    const setMeta = (name, content) => {
      let el = document.querySelector(`meta[name="${name}"]`);
      if (!el) { el = document.createElement("meta"); el.setAttribute("name", name); document.head.appendChild(el); }
      el.setAttribute("content", content);
    };
    const setOg = (prop, content) => {
      let el = document.querySelector(`meta[property="${prop}"]`);
      if (!el) { el = document.createElement("meta"); el.setAttribute("property", prop); document.head.appendChild(el); }
      el.setAttribute("content", content);
    };

    setMeta("description", "Generate full AI fruit drama videos with one sentence. Zyvo's AI Fruit Story builder creates cinematic talking fruit characters, writes the script, animates every scene, and exports a ready-to-post viral video in minutes. No editing needed.");
    setMeta("keywords", "ai fruit story, ai fruit story generator, fruit drama video maker, create viral fruit videos, ai tiktok fruit drama, fruit story video generator, make ai fruit drama videos, viral fruit video creator, talking fruit video maker");
    setOg("og:title", "AI Fruit Story Generator — Make Viral Fruit Drama Videos in Minutes");
    setOg("og:description", "One sentence → full cinematic fruit drama video. AI writes the story, generates every scene, animates talking characters. Ready to post in minutes.");
    setOg("og:type", "website");
    setOg("og:url", "https://tryzyvo.com/ai-fruit-story-maker");

    // Schema.org structured data
    const schema = {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      "name": "Zyvo AI Fruit Story Generator",
      "description": "Generate full AI fruit drama videos with one sentence. Creates cinematic talking fruit characters, writes the script, and exports viral videos in minutes.",
      "url": "https://tryzyvo.com/ai-fruit-story-maker",
      "applicationCategory": "MultimediaApplication",
      "operatingSystem": "Web",
      "offers": { "@type": "Offer", "price": "0", "priceCurrency": "EUR" },
      "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.9", "reviewCount": "2847" },
    };
    let schemaEl = document.querySelector("#ld-json-fruit");
    if (!schemaEl) { schemaEl = document.createElement("script"); schemaEl.id = "ld-json-fruit"; schemaEl.type = "application/ld+json"; document.head.appendChild(schemaEl); }
    schemaEl.textContent = JSON.stringify(schema);

    if (videoRef.current) videoRef.current.play().catch(() => {});

    return () => {
      document.title = "Zyvo – Go Viral With AI Content Creation";
      schemaEl?.remove();
    };
  }, []);

  return (
    <div className="min-h-screen bg-[#09090b] text-white">

      {/* ── HERO ── */}
      <section className="relative overflow-hidden pt-16 pb-20 md:pt-24 md:pb-28">
        <div className="pointer-events-none absolute inset-0">
          <div className="absolute left-1/4 top-0 h-[600px] w-[600px] -translate-x-1/2 rounded-full bg-purple-600/10 blur-[150px]" />
          <div className="absolute right-0 top-1/4 h-[400px] w-[400px] rounded-full bg-violet-500/8 blur-[120px]" />
        </div>

        <div className="relative mx-auto max-w-6xl px-4 md:px-6">
          <div className="flex flex-col items-center gap-10 lg:flex-row lg:items-center lg:gap-16">

            {/* Left */}
            <div className="flex-1 text-center lg:text-left">
              <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-purple-500/30 bg-purple-500/10 px-4 py-1.5">
                <span className="h-1.5 w-1.5 rounded-full bg-purple-400 animate-pulse" />
                <span className="text-[11px] font-bold uppercase tracking-[0.15em] text-purple-300">4.7M Views/Week on This Format</span>
              </div>

              {/* H1 — primary keyword */}
              <h1 className="mb-5 text-[38px] font-black leading-[1.04] tracking-tight sm:text-[52px] lg:text-[60px]">
                AI Fruit Story<br />
                <span className="bg-gradient-to-r from-[#A855F7] via-[#D8B4FE] to-[#7C3AED] bg-clip-text text-transparent">
                  Video Generator
                </span>
              </h1>

              <p className="mb-8 text-[16px] leading-relaxed text-white/55 max-w-xl mx-auto lg:mx-0 sm:text-[18px]">
                Generate full cinematic fruit drama videos with a single prompt.
                AI writes the story, creates every scene, animates talking characters —
                and exports a viral-ready video in under 5 minutes. No editing. No skills.
              </p>

              <div className="flex flex-col sm:flex-row items-center justify-center lg:justify-start gap-3 mb-8">
                <button
                  onClick={() => navigate("/workspace/ai-fruit-story")}
                  className="w-full sm:w-auto rounded-[16px] px-8 py-4 text-[16px] font-black text-white shadow-[0_8px_32px_rgba(124,58,237,0.5)] transition hover:opacity-90 active:scale-[0.98]"
                  style={{ background: "linear-gradient(135deg,#7C3AED,#A855F7)" }}
                >
                  Create Free AI Fruit Video →
                </button>
                <span className="text-[13px] text-white/30">No credit card · Free to start</span>
              </div>

              {/* Trust signals */}
              <div className="flex flex-wrap items-center justify-center lg:justify-start gap-x-6 gap-y-2">
                {["One prompt → full video", "Talking characters", "60-second stories", "Post in minutes"].map((t) => (
                  <div key={t} className="flex items-center gap-1.5 text-[13px] text-white/45">
                    <Check size={13} className="text-purple-400" />
                    {t}
                  </div>
                ))}
              </div>
            </div>

            {/* Right — phone mockup */}
            <div className="relative flex-shrink-0">
              <div className="absolute -inset-8 rounded-full bg-purple-500/15 blur-3xl" />
              <div className="relative mx-auto w-[200px] sm:w-[220px]">
                <div className="overflow-hidden rounded-[38px] border-2 border-white/15 bg-black shadow-[0_32px_80px_rgba(0,0,0,0.8)]">
                  <div className="aspect-[9/19.5] overflow-hidden">
                    <video ref={videoRef} src="/viral-builder/ai-fruit/result.mp4"
                      className="h-full w-full object-cover" muted loop playsInline preload="none" />
                  </div>
                </div>
                <div className="mx-auto mt-2 h-1 w-16 rounded-full bg-white/15" />
                <div className="absolute -right-6 top-8 flex items-center gap-1.5 rounded-full border border-red-300/30 bg-red-500/15 px-3 py-1.5 shadow-lg backdrop-blur-md">
                  <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-red-400" />
                  <span className="text-[10px] font-bold text-red-300">LIVE PREVIEW</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── STORY PRESETS — H2 ── */}
      <section className="bg-[#0c0c0f] py-16 md:py-20">
        <div className="mx-auto max-w-6xl px-4 md:px-6">
          <div className="mb-10 text-center">
            {/* H2 — secondary keyword */}
            <h2 className="mb-3 text-[28px] font-black tracking-tight sm:text-[36px]">
              Choose Your Fruit Drama Style
            </h2>
            <p className="text-[15px] text-white/40 max-w-lg mx-auto">
              Every story preset is optimized for TikTok virality. Pick one and Zyvo handles the entire production.
            </p>
          </div>

          <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-6">
            {PRESETS.map((p, i) => (
              <motion.button
                key={i}
                onClick={() => navigate("/workspace/ai-fruit-story")}
                whileHover={{ scale: 1.03 }}
                whileTap={{ scale: 0.97 }}
                className="group relative overflow-hidden rounded-[18px] border border-white/[0.08] bg-white/[0.02]"
                style={{ aspectRatio: "9/14" }}
              >
                <img src={p.src} alt={`${p.label} AI fruit drama video`} className="absolute inset-0 h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.05]" loading="lazy" />
                <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/20 to-transparent" />
                <div className="absolute bottom-0 left-0 right-0 p-3">
                  <div className="text-[12px] font-black text-white leading-tight">{p.label}</div>
                  <div className="text-[10px] text-purple-300 font-semibold">{p.views} views/wk</div>
                </div>
              </motion.button>
            ))}
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS — H2 ── */}
      <section className="py-16 md:py-20">
        <div className="mx-auto max-w-4xl px-4 md:px-6">
          <div className="mb-12 text-center">
            <h2 className="mb-3 text-[28px] font-black tracking-tight sm:text-[36px]">
              How to Make an AI Fruit Story Video
            </h2>
            <p className="text-[15px] text-white/40">From your idea to a ready-to-post video in 4 steps.</p>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            {HOW_STEPS.map((s, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-40px" }}
                transition={{ duration: 0.4, delay: i * 0.08 }}
                className="rounded-[20px] border border-white/[0.07] bg-white/[0.03] p-6"
              >
                <div className="mb-3 text-[32px] font-black text-white/[0.08] leading-none">{s.n}</div>
                <h3 className="mb-2 text-[15px] font-bold text-white">{s.title}</h3>
                <p className="text-[13px] leading-relaxed text-white/45">{s.desc}</p>
              </motion.div>
            ))}
          </div>

          <div className="mt-10 text-center">
            <button
              onClick={() => navigate("/workspace/ai-fruit-story")}
              className="rounded-[14px] px-8 py-4 text-[15px] font-black text-white shadow-[0_8px_32px_rgba(124,58,237,0.45)] transition hover:opacity-90"
              style={{ background: "linear-gradient(135deg,#7C3AED,#A855F7)" }}
            >
              Start Making Your Fruit Story →
            </button>
          </div>
        </div>
      </section>

      {/* ── CHARACTERS — H2 ── */}
      <section className="bg-[#0c0c0f] py-14 md:py-16">
        <div className="mx-auto max-w-6xl px-4 md:px-6">
          <div className="mb-8 text-center">
            <h2 className="mb-2 text-[24px] font-black tracking-tight sm:text-[32px]">
              Meet the AI Fruit Characters
            </h2>
            <p className="text-[14px] text-white/40">Each character has a locked visual identity — they look the same in every scene.</p>
          </div>
          <div className="flex flex-wrap justify-center gap-4">
            {CHARACTERS.map((c, i) => (
              <div key={i} className="flex flex-col items-center gap-2">
                <div className="h-[72px] w-[58px] overflow-hidden rounded-[16px] border border-white/10 bg-[#111315]">
                  <img src={c.src} alt={`${c.name} AI fruit character`} className="h-full w-full object-cover object-top" loading="lazy" />
                </div>
                <span className="text-[10px] font-semibold text-white/35">{c.name}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FEATURES — H2 ── */}
      <section className="py-16 md:py-20">
        <div className="mx-auto max-w-5xl px-4 md:px-6">
          <h2 className="mb-10 text-center text-[26px] font-black tracking-tight sm:text-[34px]">
            Everything You Need to Go Viral with Fruit Drama
          </h2>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {[
              { icon: "🎬", title: "Full 1-Minute Stories", desc: "Up to 10 scenes. Complete dramatic arc. Hook → escalation → shocking payoff. Zyvo plans the entire story structure." },
              { icon: "🎤", title: "Talking Characters", desc: "Every scene is animated with mouth-synced English dialogue. Your characters speak the exact lines AI wrote for them." },
              { icon: "✍️", title: "AI-Written Scripts", desc: "GPT-4 writes the story, dialogue, and scene-by-scene descriptions. You just describe the drama — AI does the writing." },
              { icon: "🖼️", title: "Cinematic 3D Images", desc: "Each scene is a high-quality cinematic 3D image generated from your characters and story. Real production quality." },
              { icon: "📱", title: "Vertical 9:16 Format", desc: "Every video is built natively for TikTok, Instagram Reels, and YouTube Shorts. No cropping or reformatting needed." },
              { icon: "⚡", title: "No Editing Required", desc: "Zero video editing skills needed. No timeline, no keyframes. Generate, download, post. Under 5 minutes." },
            ].map((f, i) => (
              <div key={i} className="rounded-[18px] border border-white/[0.07] bg-white/[0.02] p-5">
                <div className="mb-3 text-2xl">{f.icon}</div>
                <h3 className="mb-1.5 text-[14px] font-bold text-white">{f.title}</h3>
                <p className="text-[13px] leading-relaxed text-white/40">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── STATS ── */}
      <section className="bg-[#0c0c0f] py-14 md:py-16">
        <div className="mx-auto max-w-4xl px-4 md:px-6">
          <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
            {[
              { v: "4.7M", l: "Views/week on fruit drama" },
              { v: "< 5min", l: "From prompt to video" },
              { v: "10",   l: "Scenes per story" },
              { v: "0",    l: "Editing skills needed" },
            ].map((s, i) => (
              <div key={i} className="rounded-[16px] border border-white/[0.07] bg-white/[0.02] p-5 text-center">
                <div className="text-[30px] font-black text-white">{s.v}</div>
                <div className="mt-1 text-[11px] text-white/35">{s.l}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FAQ — H2 (great for SEO) ── */}
      <section className="py-16 md:py-20">
        <div className="mx-auto max-w-3xl px-4 md:px-6">
          <h2 className="mb-10 text-center text-[26px] font-black tracking-tight sm:text-[34px]">
            Frequently Asked Questions
          </h2>
          <div className="space-y-3">
            {FAQS.map((f, i) => (
              <details key={i} className="group rounded-[16px] border border-white/[0.07] bg-white/[0.02] p-5 cursor-pointer">
                <summary className="flex items-center justify-between text-[14px] font-bold text-white list-none">
                  {f.q}
                  <span className="ml-3 flex-shrink-0 text-white/30 group-open:rotate-180 transition-transform duration-200">▾</span>
                </summary>
                <p className="mt-3 text-[13px] leading-relaxed text-white/50">{f.a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* ── FINAL CTA ── */}
      <section className="py-16 md:py-20">
        <div className="mx-auto max-w-2xl px-4 md:px-6 text-center">
          <h2 className="mb-4 text-[28px] font-black tracking-tight sm:text-[38px]">
            Make Your First AI Fruit Story<br />
            <span className="bg-gradient-to-r from-[#A855F7] to-[#7C3AED] bg-clip-text text-transparent">Right Now — It's Free</span>
          </h2>
          <p className="mb-8 text-[15px] text-white/45">
            One prompt. Full cinematic video. Ready to post on TikTok and Reels in minutes.
          </p>
          <button
            onClick={() => navigate("/workspace/ai-fruit-story")}
            className="rounded-[16px] px-10 py-4 text-[16px] font-black text-white shadow-[0_8px_40px_rgba(124,58,237,0.5)] transition hover:opacity-90 active:scale-[0.98]"
            style={{ background: "linear-gradient(135deg,#7C3AED,#A855F7)" }}
          >
            Generate My Fruit Drama Video →
          </button>
          <p className="mt-4 text-[12px] text-white/25">No credit card required · Free plan available</p>
        </div>
      </section>

    </div>
  );
}
