// From data/fruit-characters/library.json (written by upload.mjs):
//  - supabase/seeds/fruit_characters.sql   idempotent upsert of all rows
//  - src/.../ai-fruit-story-v2/api/mock/libraryData.js   the same library for the mock backend
//   node scripts/fruit-characters/export.mjs
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const lib = JSON.parse(fs.readFileSync(path.join(ROOT, "data/fruit-characters/library.json"), "utf8"));

const q = (v) => (v == null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
const arr = (a) => `ARRAY[${a.map(q).join(", ")}]::text[]`;
const COLS = ["id", "name", "collection", "fruit", "emoji", "hue", "gender", "age", "tag", "role", "story_types", "settings", "voice_style", "face", "build", "outfit", "ref_image_url", "ref_image_path", "ref_width", "ref_height", "ref_model", "ref_seed", "ref_prompt", "ref_cost_usd", "sort_order"];
const rows = lib.map((c) => `(${[
  q(c.id), q(c.name), q(c.collection), q(c.fruit), q(c.emoji), c.hue, q(c.gender), c.age, q(c.tag), q(c.role),
  arr(c.storyTypes), arr(c.settings), q(c.voiceStyle), q(c.face), q(c.build), q(c.outfit),
  q(c.refImageUrl), q(c.refImagePath), c.refWidth, c.refHeight, q(c.refModel), c.refSeed ?? "NULL", q(c.refPrompt), c.refCostUsd ?? "NULL", c.sortOrder,
].join(", ")})`);

const sql = `-- Seed for public.fruit_characters (generated by scripts/fruit-characters/export.mjs; do not edit by hand).
-- Idempotent: re-running updates rows in place. ${lib.length} characters.
BEGIN;
INSERT INTO public.fruit_characters (${COLS.join(", ")}) VALUES
${rows.join(",\n")}
ON CONFLICT (id) DO UPDATE SET
${COLS.filter((c) => c !== "id").map((c) => `  ${c} = EXCLUDED.${c}`).join(",\n")};
COMMIT;
`;
fs.mkdirSync(path.join(ROOT, "supabase/seeds"), { recursive: true });
fs.writeFileSync(path.join(ROOT, "supabase/seeds/fruit_characters.sql"), sql);

const mock = lib.map((c) => ({
  id: c.id, name: c.name, collection: c.collection, fruit: c.fruit, emoji: c.emoji, hue: c.hue,
  tag: c.tag, role: c.role, gender: c.gender, voiceStyle: c.voiceStyle, storyTypes: c.storyTypes, refImageUrl: c.refImageUrl,
}));
const js = `// The AI Fruit Story character library (${lib.length} characters), for the mock backend.
// Generated by scripts/fruit-characters/export.mjs from the same data as the
// fruit_characters table seed. Do not edit by hand.

/** @type {import("../fruitStoryV2Api").Character[]} */
export const LIBRARY = ${JSON.stringify(mock, null, 1)};
`;
fs.writeFileSync(path.join(ROOT, "src/components/viral-tools/ai-fruit-story-v2/api/mock/libraryData.js"), js);
console.log(`seed: ${rows.length} rows · mock: ${mock.length} characters`);
