// How each library character's voice SOUNDS: pitch, texture, pace, accent.
// Never an emotion or attitude ("smug", "nervous", "icy"): the scene's emotion
// decides the delivery, so the two never fight in a clip prompt.
// The clip builder says "in her <voice> voice, delivered with <emotion>".
//   node scripts/fruit-characters/voices.mjs   rewrites roster.mjs + the data JSON, then run export.mjs

export const VOICES = {
  mia: "low, smooth, unhurried",
  marco: "warm baritone, smooth, even pace",
  pia: "light, airy, lilting",
  rick: "loud, booming baritone",
  bella: "bright, quick, slightly high",
  marg: "thin, crisp, precise diction",
  gloria: "quick, chirpy, mid-pitched",
  linda: "clipped, crisp, mid-pitched",
  benny: "quick, thin, a little breathy",
  pina: "very deep, slow, gravelly bass",
  coco: "low, gravelly, sparse",
  olive: "warm, full, mid-pitched",
  kiki: "bright, upbeat, quick",
  walt: "hearty, warm, older baritone",
  ana: "bright, bubbly, high",
  sally: "soft, sugary, older",
  andy: "nasal, reedy, young",
  adam: "loud, punchy, fast",
  abby: "soft, gentle, quick",
  gus: "gravelly, low, older, slow",
  fiona: "crisp, clear, measured",
  candy: "bright, glossy, quick",
  grace: "soft, sweet-toned, older",
  greg: "soft, mumbly, quick",
  vic: "nasal, thin, drawling",
  jade: "quick, bright, light",
  manny: "booming, rich, older",
  maya: "bubbly, fast, high",
  milo: "relaxed drawl, warm, low",
  ali: "loud, hard-edged, fast",
  dina: "brisk, full, projecting",
  paige: "breathy, light, bright",
  pete: "warm, round, mid-pitched",
  georgia: "slow, soft, sugary drawl",
  percy: "projecting, rich, rolling",
  penny: "low, crisp, cool-toned",
  hank: "slow, dry, low",
  stan: "casual, mid-pitched, quick",
  rosa: "shrill, high, fast",
  stella: "loud, quick, chatty rhythm",
  jimmy: "loud, high-energy, fast",
  sid: "deep, measured, even",
  greta: "soft, light, mid-pitched",
  vinny: "silky, fast, smooth",
  gordon: "booming, smooth, resonant",
  connie: "soft, smooth, cool-toned",
  gabe: "low, smooth, relaxed",
  lenny: "gruff, rough, low",
  lola: "dry, flat, low",
  larry: "flat, low, rough",
  lucy: "light, sweet-toned, clear",
  martin: "slow, formal diction, older, soft",
  lionel: "low, smoky, unhurried",
  lila: "peppy, high, bright",
  kay: "whispery, thin, older",
  leo: "loud, drawling, young",
  bruno: "loud, heavy, fast",
  bea: "soft, light, sweet-toned",
  barb: "loud, older, carrying",
  buddy: "gravelly, warm, chatty rhythm",
  bonnie: "high, sing-song lilt, young",
  chip: "soft, light, slightly shaky",
  pablo: "quick, light, a little breathy",
  pam: "firm, low, slightly raspy",
  tony: "smooth, warm, older baritone",
  piper: "loud, bright, quick",
  carl: "gruff, flat, low",
  cora: "clipped, even, mid-pitched",
  kai: "relaxed, mellow, low",
  hazel: "slow, airy, older, soft",
  oscar: "hearty, bright, mid-pitched",
  clara: "bright, clear, young",
  otto: "dry, formal diction, older, slow",
  tanya: "flat, drawling, low",
  jojo: "loud, loose, quick",
  mandy: "bright, projecting, mid-pitched",
  ken: "monotone, flat, mid-pitched",
  nora: "soft, soothing, older",
  kurt: "squeaky, high, quick",
  wanda: "slow, soft, drawling",
  mel: "relaxed, smooth, low",
  rhonda: "shrill, loud, fast",
  wes: "clear, mid-pitched, quick",
  chloe: "light, sweet-toned, crisp",
  charlie: "smooth, mid-pitched, a little quick",
  carmen: "low, husky, rich",
  chuck: "grumbly, low, older",
  bing: "high, halting rhythm, quick",
  tara: "smooth, clear, mid-pitched",
  perry: "nasal, reedy, thin",
  paula: "soft, whispery, light",
  bart: "dry, low, older",
  anya: "clear, even pace, mid-pitched",
  boris: "slow, deep, measured",
  polly: "high, trilling, older",
  philip: "rich, plummy, formal diction",
  priya: "fast, crisp, clear",
  dan: "mellow, mid-pitched, relaxed pace",
  betty: "quick, breathy, mid-pitched",
  barry: "fast, smooth, silky",
  bree: "chirpy, high, quick",
  jay: "steady, even, mid-pitched",
  violet: "low, purring, older",
  moe: "deep, flat, heavy",
  remy: "quiet, low, soft",
  rita: "raspy, rough, low",
  ron: "slow, booming, older",
  rae: "low, smooth, cool-toned",
  ava: "nasal, bright, quick",
  al: "quiet, breathy, soft",
  hector: "smooth, loud, resonant",
  addie: "airy, soft, light",
  andre: "soft, warm, low",
  edna: "shrill, high, older",
  priscilla: "rich, crisp, older, formal diction",
  pedro: "slow, sharp, low",
  ruby: "quick, bright, chatty rhythm",
  omar: "warm, soft, mid-pitched",
  felix: "smooth, warm, even pace",
  fran: "slow, husky, older",
  farrah: "crisp, posh British accent",
  pappy: "loud, crackly, older",
  paco: "loud, bright, quick",
  pilar: "quiet, low, soft",
  patty: "loud, high, fast",
  dex: "smooth, low, relaxed",
  daria: "raspy, loud, fast",
  dot: "sharp, thin, older",
  ty: "loud, clear, quick",
  gail: "tight, clipped, mid-pitched",
  grant: "booming, smooth, resonant",
  ruth: "sharp, dry, older",
  hal: "loud, rough, barking",
  april: "chatty rhythm, bright, quick",
  archie: "barking, gruff, older",
  aria: "cool-toned, clear, even",
  arlo: "loud, quick, young",
  lily: "bubbly, high, light",
  lee: "low, quiet, even",
  lulu: "silky, smooth, low",
  brad: "deep, even, unhurried",
  bianca: "low, crisp, cool-toned",
  mac: "whispery, low, flat",
  dolly: "gruff, low, older",
  harriet: "whispery, crisp, older",
  hugh: "gentle, soft, mid-pitched",
  dewey: "bright, bouncy rhythm, mid-pitched",
  duke: "slow, deep, gravelly",
  doris: "shrill, high, older",
  dusty: "loud, drawling, lazy pace",
  lemz: "low, unhurried London accent",
  zesty: "fast, high, young London accent",
  tomzy: "loud, bouncy London accent",
  razz: "low, clipped London accent",
  pinesy: "rhythmic, smooth London accent",
  pez: "soft, mellow, slow London accent",
  wedge: "bright, quick London accent",
  blu: "smooth, silky London accent",
  grapz: "quiet, deep, sparse London accent",
  chez: "warm, chatty-rhythm London accent",
  uncle: "warm, booming, older London accent",
  trims: "low, measured, even London accent",
  rasco: "loud, punchy London accent",
  jito: "soft, mellow London accent",
  roxy: "quick, crisp London accent",
  tia: "dry, low, cool-toned London accent",
  chatty: "fast, bright, chatty-rhythm London accent",
  nessa: "firm, warm London accent",
  auntie: "warm, crisp, older London accent",
  tizzy: "loud, bubbly, fast London accent",
};

// Words that describe a feeling or attitude, not a sound. A test keeps them out.
export const EMOTION_WORDS = [
  "gleeful", "nervous", "smug", "icy", "menacing", "dangerous", "scary", "sly", "guilty", "greedy", "bossy",
  "entitled", "oblivious", "clueless", "passive-aggressive", "scheming", "calculating", "demanding", "defiant",
  "dramatic", "fake", "flirty", "loyal", "ambitious", "worried", "frazzled", "hopeful", "sad", "anxious",
  "amused", "bored", "stubborn", "nosy", "mystic", "shady", "wild", "sassy", "bratty", "funny", "sweaty",
  "noir", "pushy", "proud", "tough", "strict", "wise", "sloppy", "corny", "salesy", "happy",
  "angry", "furious", "excited", "scared", "panicked", "gleefully", "slang", "calm", "confident", "eager", "friendly", "persuasive", "cheerful",
  "playful", "pompous", "cheesy", "theatrical", "slick", "giggly", "shouty", "awkward", "easygoing", "tired", "whiny",
];

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, "/").split("/").pop())) {
  const fs = await import("fs");
  const path = await import("path");
  const { fileURLToPath } = await import("url");
  const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
  // roster.mjs: the voice is the 9th string in each row; swap it by id.
  const rosterFile = path.join(ROOT, "scripts/fruit-characters/roster.mjs");
  let roster = fs.readFileSync(rosterFile, "utf8");
  let swapped = 0;
  for (const [id, voice] of Object.entries(VOICES)) {
    const re = new RegExp(`(\\["${id}", (?:(?:"[^"]*"|\\d+), ){7})"[^"]*"`);
    if (!re.test(roster)) throw new Error(`roster row for ${id} not found`);
    roster = roster.replace(re, (_, head) => `${head}${JSON.stringify(voice)}`);
    swapped++;
  }
  fs.writeFileSync(rosterFile, roster);
  for (const file of ["data/fruit-characters/characters.json", "data/fruit-characters/library.json"]) {
    const full = path.join(ROOT, file);
    const data = JSON.parse(fs.readFileSync(full, "utf8"));
    const rows = Array.isArray(data) ? data : data.characters;
    for (const c of rows) {
      if (!VOICES[c.id]) throw new Error(`no voice for ${c.id}`);
      c.voiceStyle = VOICES[c.id];
    }
    fs.writeFileSync(full, JSON.stringify(data, null, 1));
  }
  console.log(`voices: ${swapped} roster rows + characters.json + library.json`);
}
