// deno-lint-ignore-file no-explicit-any
// visualPlanFocalSubjectRepair.ts — 2026-09-22 "targeted Visual Plan
// repair" pass. Generic, topic-agnostic repair for FOCAL_SUBJECT_REPETITION:
// a run of consecutive EXPANDED shots collapsing to the same visual subject
// despite covering materially different narration.
//
// Root cause (confirmed against real, live Atlantis data, verified by
// reading the actual persisted contracts — never inferred from a
// screenshot): visualShotPlanning.js's per-shot subject resolution
// (shotEntityIds) matches candidate entity NAMES against that shot's own
// narration text literally. When a shot's specific narration slice doesn't
// happen to literally repeat any candidate entity's name — which is the
// COMMON case, since narration usually elaborates an idea without renaming
// its subject every sentence — resolution falls through to the shared
// narration claim's single, segment-wide primarySubject. Every shot in a
// macro sequence maps to the SAME claim, so every shot in that macro
// collapses onto the SAME fallback subject, even though the macro's own
// primaryEntityIds already declared multiple distinct, valid subjects
// (verified live: a macro's primaryEntityIds correctly listed 3-4 distinct
// entities; every one of its expanded shots still resolved to the same
// single entity).
//
// This module NEVER rewrites that deterministic shot-expansion pipeline
// (out of scope — "do not rebuild Visual Plan" as a wholesale system). It
// operates entirely on an ALREADY-EXPANDED plan's visualBeats, as a
// targeted, versioned repair: detect the defective regions, ask an LLM to
// re-judge ONLY those regions' subjects from actual narration meaning
// (never keyword-matching, never a hardcoded entity preference), merge the
// result back with full provenance, and hand the caller a plan ready for
// deterministic validation. No image is ever generated by this module; no
// provider other than one text LLM call per repair region is ever invoked.

// Mirrors episodeQA.ts's own FOCAL_SUBJECT_REPETITION threshold exactly —
// the same generic definition of "repetitive," just applied at Visual Plan
// beat-authoring time instead of post-compile QA time.
export const FOCAL_SUBJECT_REPETITION_THRESHOLD = 4;

export type RepairRegion = {
  regionId: string;
  macroSequenceIds: string[]; // sourceMacroBeatId values, in the plan's own order
  beatIds: string[]; // every visualBeats id belonging to any of macroSequenceIds — a macro is the atomic repair unit, never split mid-macro
  reason: string;
  repeatedSubjects: string[];
};

/**
 * Detects runs of FOCAL_SUBJECT_REPETITION_THRESHOLD+ consecutive shots
 * (by sequenceIndex) sharing the identical `subject` string, then SNAPS
 * every detected run out to the full set of macro sequences it touches —
 * a macro's shots share one continuity/baseSetupKey lineage and are always
 * repaired (or preserved) together, never partially. Two raw runs whose
 * snapped macro sets are adjacent or overlapping merge into ONE region, so
 * the caller never receives overlapping/duplicate regions. Generic: reads
 * only `sequenceIndex`, `subject`, and `sourceMacroBeatId` — no entity
 * names, topics, or project-specific values appear anywhere in this logic.
 *
 * Deliberately does NOT treat a differing pre-compile `visualType` as proof
 * of real visual variety: a beat authored as a graphic/diagram visualType
 * can still compile down to a plain GENERATE-strategy illustration (the
 * compile-time PROGRAMMATIC_GRAPHIC->GENERATE fallback this same pass
 * fixed at the scene_type/render_strategy-agreement level — see §7)
 * whenever its claim doesn't fit any graphic template, at which point the
 * "different visualType" promise never survives into the actually
 * rendered output. Detection stays on the one signal proven to reflect
 * what a viewer will actually see: the resolved subject itself.
 */
export function detectFocalSubjectRepairRegions(plan: any, threshold = FOCAL_SUBJECT_REPETITION_THRESHOLD): RepairRegion[] {
  const beats = [...(plan.visualBeats ?? [])].sort((a: any, b: any) => a.sequenceIndex - b.sequenceIndex);
  const flaggedMacroIds = new Set<string>();
  const reasonsByMacro = new Map<string, string[]>();
  const subjectsByMacro = new Map<string, Set<string>>();
  let runStart = 0;
  for (let i = 1; i <= beats.length; i++) {
    const sameAsStart = i < beats.length && beats[i].subject && beats[i].subject === beats[runStart].subject;
    if (!sameAsStart) {
      const runLength = i - runStart;
      if (runLength >= threshold && beats[runStart].subject) {
        const runBeats = beats.slice(runStart, i);
        const macroIds = [...new Set(runBeats.map((b: any) => b.sourceMacroBeatId).filter(Boolean))] as string[];
        for (const m of macroIds) {
          flaggedMacroIds.add(m);
          reasonsByMacro.set(m, [...(reasonsByMacro.get(m) ?? []), `${runLength} consecutive shots (sequenceIndex ${runBeats[0].sequenceIndex}-${runBeats[runBeats.length - 1].sequenceIndex}) resolved to "${beats[runStart].subject}"`]);
          subjectsByMacro.set(m, new Set([...(subjectsByMacro.get(m) ?? []), beats[runStart].subject]));
        }
      }
      runStart = i;
    }
  }
  if (!flaggedMacroIds.size) return [];

  const macroOrder: string[] = [];
  const seenMacro = new Set<string>();
  const beatsByMacro = new Map<string, any[]>();
  for (const b of beats) {
    if (!b.sourceMacroBeatId) continue;
    if (!seenMacro.has(b.sourceMacroBeatId)) { seenMacro.add(b.sourceMacroBeatId); macroOrder.push(b.sourceMacroBeatId); }
    beatsByMacro.set(b.sourceMacroBeatId, [...(beatsByMacro.get(b.sourceMacroBeatId) ?? []), b]);
  }

  const regions: RepairRegion[] = [];
  let i = 0;
  while (i < macroOrder.length) {
    if (!flaggedMacroIds.has(macroOrder[i])) { i++; continue; }
    let j = i;
    while (j < macroOrder.length && flaggedMacroIds.has(macroOrder[j])) j++;
    const macroIds = macroOrder.slice(i, j);
    const beatIds = macroIds.flatMap((m) => beatsByMacro.get(m)!.map((b) => b.id));
    const reasons = [...new Set(macroIds.flatMap((m) => reasonsByMacro.get(m) ?? []))];
    const repeatedSubjects = [...new Set(macroIds.flatMap((m) => [...(subjectsByMacro.get(m) ?? [])]))];
    regions.push({
      regionId: `repair_region_${macroIds[0]}_${macroIds[macroIds.length - 1]}`,
      macroSequenceIds: macroIds,
      beatIds,
      reason: reasons.join("; "),
      repeatedSubjects,
    });
    i = j;
  }
  return regions;
}

/* ============================ LLM repair schema/instructions ============================ */
// Deliberately restricted to visualTypes that stay within the SAME
// render-strategy family the beat was already planned under (a photographic
// GENERATE/EDIT beat can freely become a different photographic concept —
// STORY_ILLUSTRATION/ENVIRONMENT/CHARACTER/OBJECT_DETAIL — without any
// render-strategy implication). Switching a beat to/from a graphic/diagram
// concept would also require re-routing render_strategy and the graphic-
// template compiler — a materially larger, riskier change deliberately left
// out of this pass (see the final report's scope notes).
const REPAIR_VISUAL_TYPES = ["STORY_ILLUSTRATION", "ENVIRONMENT", "CHARACTER", "OBJECT_DETAIL"];

export function buildFocalSubjectRepairSchema(beatIds: string[]) {
  return {
    type: "object",
    additionalProperties: false,
    required: ["shots"],
    properties: {
      shots: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: ["beatId", "narrationMeaning", "focalEntityId", "displaySubject", "visualType", "continuityWithPrevious", "meaningfulDelta"],
          properties: {
            beatId: { type: "string", enum: beatIds },
            narrationMeaning: { type: "string", description: "One short sentence: what THIS shot's own specific narration text is actually saying, independent of its neighbors." },
            focalEntityId: { type: ["string", "null"], description: "The id of the ONE entity (from this shot's own listed candidate entities) that best visualizes this exact narration moment, or null when no listed entity is the right visual (e.g. this moment is better shown as a detail/diagram-like concept/reconstruction/comparison with no single existing entity as its subject)." },
            displaySubject: { type: "string", description: "Short, plain, human-readable description of what the viewer sees in this shot. 3-10 words. Never internal planning language." },
            visualType: { type: "string", enum: REPAIR_VISUAL_TYPES },
            continuityWithPrevious: { type: "boolean", description: "true ONLY if keeping the same subject/visual as the immediately preceding shot genuinely serves the explanation (the narration is still elaborating the same scene/idea) — never true merely because it would be convenient or because a reference happens to already exist for it." },
            meaningfulDelta: { type: "string", description: "One short phrase: what is visually different from the immediately preceding shot — a different subject, OR (if continuityWithPrevious is true) what changed about the SAME subject's state/action/expression/framing. Never empty." },
          },
        },
      },
    },
  };
}

export const FOCAL_SUBJECT_REPAIR_INSTRUCTIONS = `You are repairing a small, already-approved region of a documentary video's shot plan. Every shot listed below currently resolves to the SAME visual subject, which makes this run of shots repetitive on screen even though the underlying narration covers different information from shot to shot.

For EACH shot, read ONLY that shot's own narration text (never assume it continues whatever its neighbor was about) and decide the single best visual for THAT specific moment:
- It may be a character, a location, an object, or a concept/detail/reconstruction with no listed entity at all.
- Do NOT automatically default to the narrator, the protagonist, the first-mentioned entity, the most common entity, or a location — those are only the right choice when they are genuinely the best visual explanation of THIS exact narration moment, not by default.
- Choose focalEntityId ONLY from the candidate entities listed for that specific shot; use null when the narration moment is better shown as a concept/detail/reconstruction with no single existing entity as its subject.
- Whether a reference image is already AVAILABLE for a candidate entity is not a reason to choose it. Decide the correct visual first; reference availability is looked up afterward, never the other way around.

Preserve continuity between adjacent shots ONLY when it genuinely serves the explanation (the narration is still elaborating the same scene or idea). When the narration has moved on to new information, the visual must show a MEANINGFUL DELTA — a different subject, or the same subject in a materially different state, action, expression, prop, or framing. The goal is CONTINUITY + MEANINGFUL DELTA — never "make every shot different for its own sake," and never "keep repeating the same static image."

Never invent narrative content that isn't in the narration text you're given. Never contradict a shot's own narration. Never choose an entity that isn't in that specific shot's candidate list.`;

/**
 * Compact, per-shot input for the repair call — every shot in the region,
 * its own narration text, its own macro's candidate entities (never a
 * global list — different macros in one merged region can have entirely
 * different valid candidates), and reference-availability as pure
 * information (§F: "references must follow the plan, not control it").
 */
export function buildFocalSubjectRepairInput(region: RepairRegion, plan: any, entityRegistryById: Map<string, any>, referenceAvailabilityByEntityId: Map<string, boolean>) {
  const beatsById = new Map((plan.visualBeats ?? []).map((b: any) => [b.id, b]));
  const macrosBySourceId = new Map((plan.visualSequences ?? []).map((s: any) => [s.sourceMacroBeatId, s]));
  const orderedBeats = region.beatIds.map((id) => beatsById.get(id)).filter(Boolean) as any[];
  const firstBeat = orderedBeats[0];
  const lastBeat = orderedBeats[orderedBeats.length - 1];
  const allBeatsSorted = [...(plan.visualBeats ?? [])].sort((a: any, b: any) => a.sequenceIndex - b.sequenceIndex);
  const beforeBeat = firstBeat ? allBeatsSorted.filter((b) => b.sequenceIndex < firstBeat.sequenceIndex).slice(-1)[0] : null;
  const afterBeat = lastBeat ? allBeatsSorted.find((b) => b.sequenceIndex > lastBeat.sequenceIndex) : null;

  const describeCandidates = (macro: any) => {
    const ids = [...new Set([...(macro?.primaryEntityIds ?? []), ...(macro?.supportingEntityIds ?? [])])] as string[];
    return ids.map((id) => {
      const e = entityRegistryById.get(id);
      if (!e) return null;
      return { id: e.id, name: e.name, category: e.category, referenceAvailable: Boolean(referenceAvailabilityByEntityId.get(e.id)) };
    }).filter(Boolean);
  };

  return {
    regionReason: region.reason,
    contextBeforeRegion: beforeBeat ? { displaySubject: beforeBeat.subject, visualType: beforeBeat.visualType, narrationText: beforeBeat.shotNarrationText ?? "" } : null,
    contextAfterRegion: afterBeat ? { displaySubject: afterBeat.subject, visualType: afterBeat.visualType, narrationText: afterBeat.shotNarrationText ?? "" } : null,
    shots: orderedBeats.map((b) => {
      const macro = macrosBySourceId.get(b.sourceMacroBeatId);
      return {
        beatId: b.id,
        macroPurpose: macro?.purpose ?? null,
        narrativeFunction: b.narrativeFunction ?? macro?.narrativeFunction ?? null,
        narrationText: b.shotNarrationText || b.actionOrState || "",
        currentSubject: b.subject ?? null,
        candidateEntities: describeCandidates(macro),
      };
    }),
  };
}

/**
 * Merges the LLM's repaired shots back into a deep clone of the plan.
 * ONLY subject/display/visualType/provenance fields are touched — timing,
 * narration ranges, render_strategy, baseSetupKey, forbidden elements,
 * factual constraints, and every other authored field are copied verbatim.
 * Deliberately narrow: this repair fixes WHICH subject a shot shows, never
 * HOW it's rendered (render_strategy/baseSetupKey re-routing is out of
 * scope for this pass — see final report).
 *
 * beat.subject is set to the entity id itself when one was chosen (never a
 * display name) so the ALREADY-FIXED §6 compiler logic
 * (episodePreflight.ts: `focalEntityId = entities.has(rawFocalSubject) ?
 * rawFocalSubject : null`) picks it up as a real, stable entity id
 * automatically — no new compiler-side field is needed for this to work.
 */
export function mergeFocalSubjectRepairIntoPlan(plan: any, region: RepairRegion, repairedShots: any[], sourceVisualPlanVersionId: string) {
  const repairedById = new Map(repairedShots.map((s: any) => [s.beatId, s]));
  const next = structuredClone(plan);
  let changedCount = 0;
  next.visualBeats = (next.visualBeats ?? []).map((beat: any) => {
    if (!region.beatIds.includes(beat.id)) return beat;
    const repaired = repairedById.get(beat.id);
    if (!repaired) return { ...beat, preservedFromParent: true, repairRegionId: region.regionId };
    changedCount++;
    const newFocalEntityId: string | null = repaired.focalEntityId || null;
    // 2026-09-23 "root-contract stabilization" pass — real Atlantis finding:
    // this used to update ONLY subject/displaySubjectHint/narrationMeaning/
    // visualType — the beat's OWN entity-tagging fields (primaryEntityIds,
    // supportingEntityIds, entities, referenceEntityIds) were left pointing
    // at the OLD (pre-repair) subject. requiredReferenceLookups
    // (sceneRenderPlan.ts) and episodePreflight.ts's character-presence
    // derivation read ONLY primaryEntityIds/supportingEntityIds — never
    // subject/displaySubject — so a beat repaired from "Plato" to
    // "obj_sonar_photo" still carried primaryEntityIds:["ent_plato", ...],
    // still routed Plato's identity reference, and Plato still appeared in
    // the rendered scene despite the repair having "fixed" its subject
    // field. The repair schema's focalEntityId is the single authoritative
    // entity for this shot post-repair (or null — a concept/detail with no
    // entity) — every field that tags "who/what is in this shot" must be
    // rebuilt from it, never left describing the subject the repair just
    // replaced.
    return {
      ...beat,
      subject: repaired.focalEntityId || repaired.displaySubject,
      displaySubjectHint: repaired.displaySubject,
      narrationMeaning: repaired.narrationMeaning,
      visualType: REPAIR_VISUAL_TYPES.includes(repaired.visualType) ? repaired.visualType : beat.visualType,
      primarySubject: repaired.displaySubject,
      entities: newFocalEntityId ? [newFocalEntityId] : [],
      primaryEntityIds: newFocalEntityId ? [newFocalEntityId] : [],
      supportingEntityIds: [],
      referenceEntityIds: newFocalEntityId ? [newFocalEntityId] : [],
      castBindings: newFocalEntityId
        ? [{ characterId: newFocalEntityId, lookId: "canonical", action: repaired.narrationMeaning, expression: "narration-appropriate", screenPosition: "focal" }]
        : [],
      repairReason: region.reason,
      sourceVisualPlanVersionId,
      sourceBeatId: beat.id,
      repairRegionId: region.regionId,
      repairMethod: "focal_subject_llm_repair",
      preservedFromParent: false,
    };
  });
  return { plan: next, changedCount, unchangedInRegionCount: region.beatIds.length - changedCount };
}
