// Builds the AI Fruit Story idea library from the hand-written text files in
// this folder (one idea per line: title | summary | cast[, cast] [| story type]).
//   node scripts/fruit-story/ideas/build.mjs   → supabase/seeds/fruit_ideas.sql + counts
// loadIdeas() is also used by tests/fruitIdeas.test.mjs.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../../..");
const STORY_TYPES = ["marriage", "office", "crime", "law", "family", "dating", "money", "neighbors", "social", "wedding", "service", "hospital", "school", "sports"];

const slug = (s) => s.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60);

/** @returns {{ideas: object[], problems: string[]}} */
export function loadIdeas() {
  const library = JSON.parse(fs.readFileSync(path.join(ROOT, "data/fruit-characters/library.json"), "utf8"));
  const byId = new Map(library.map((c) => [c.id, c]));
  const ideas = [];
  const problems = [];
  const titles = new Map();
  const ids = new Set();
  for (const file of fs.readdirSync(HERE).filter((f) => f.endsWith(".txt")).sort()) {
    const fileType = path.basename(file, ".txt");
    const lines = fs.readFileSync(path.join(HERE, file), "utf8").split(/\r?\n/);
    lines.forEach((raw, i) => {
      const line = raw.trim();
      if (!line || line.startsWith("#")) return;
      const where = `${file}:${i + 1}`;
      const parts = line.split("|").map((p) => p.trim());
      if (parts.length < 3 || parts.length > 4) { problems.push(`${where}: expected 3-4 fields`); return; }
      const [title, summary, castRaw, typeRaw] = parts;
      const castIds = castRaw.split(",").map((s) => s.trim()).filter(Boolean);
      const storyType = typeRaw || fileType;
      if (!STORY_TYPES.includes(storyType)) problems.push(`${where}: unknown story type ${storyType}`);
      if (!title || title.length > 80) problems.push(`${where}: title length ${title.length}`);
      if (!summary || summary.length > 200) problems.push(`${where}: summary length ${summary.length}`);
      if (castIds.length < 2 || castIds.length > 3 || new Set(castIds).size !== castIds.length) problems.push(`${where}: cast must be 2-3 distinct ids`);
      for (const id of castIds) if (!byId.has(id)) problems.push(`${where}: unknown character ${id}`);
      const key = title.toLowerCase();
      if (titles.has(key)) problems.push(`${where}: duplicate title (also ${titles.get(key)})`);
      titles.set(key, where);
      let id = `${storyType}-${slug(title)}`;
      for (let n = 2; ids.has(id); n++) id = `${storyType}-${slug(title)}-${n}`;
      ids.add(id);
      const collection = fileType === "uk-roadman" ? "uk-roadman" : "core";
      ideas.push({ id, title, summary, castIds, storyType, collection });
    });
  }
  return { ideas, problems };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { ideas, problems } = loadIdeas();
  if (problems.length) {
    console.error(problems.join("\n"));
    process.exit(1);
  }
  const q = (v) => `'${String(v).replace(/'/g, "''")}'`;
  const rows = ideas.map((i) => `(${q(i.id)}, ${q(i.title)}, ${q(i.summary)}, ARRAY[${i.castIds.map(q).join(", ")}]::text[], ${q(i.storyType)}, ${q(i.collection)})`);
  const sql = `-- Seed for public.fruit_ideas (generated by scripts/fruit-story/ideas/build.mjs; edit the .txt files, not this).
-- ${ideas.length} hand-written ideas. Idempotent; ideas removed from the files are deactivated, not deleted.
BEGIN;
INSERT INTO public.fruit_ideas (id, title, summary, cast_ids, story_type, collection) VALUES
${rows.join(",\n")}
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, cast_ids = EXCLUDED.cast_ids,
  story_type = EXCLUDED.story_type, collection = EXCLUDED.collection, active = true;
UPDATE public.fruit_ideas SET active = false WHERE id NOT IN (${ideas.map((i) => q(i.id)).join(", ")});
COMMIT;
`;
  fs.writeFileSync(path.join(ROOT, "supabase/seeds/fruit_ideas.sql"), sql);
  const count = (f) => ideas.reduce((m, i) => ((m[f(i)] = (m[f(i)] ?? 0) + 1), m), {});
  console.log(JSON.stringify({ total: ideas.length, byType: count((i) => i.storyType), byCollection: count((i) => i.collection) }));
}
