// The AI Fruit Story character library (170 characters), for the mock backend.
// Generated by scripts/fruit-characters/export.mjs from the same data as the
// fruit_characters table seed. Do not edit by hand.

/** @type {import("../fruitStoryV2Api").Character[]} */
export const LIBRARY = [
 {
  "id": "mia",
  "name": "Mia Mango",
  "collection": "core",
  "fruit": "mango",
  "emoji": "🥭",
  "hue": 38,
  "tag": "Wife",
  "role": "Calm, patient schemer",
  "gender": "female",
  "voiceStyle": "calm, low, deliberate",
  "storyTypes": [
   "marriage",
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/mia-a1.jpg"
 },
 {
  "id": "marco",
  "name": "Marco Mango",
  "collection": "core",
  "fruit": "mango",
  "emoji": "🥭",
  "hue": 38,
  "tag": "Husband",
  "role": "Charming, smooth liar",
  "gender": "male",
  "voiceStyle": "smooth, confident",
  "storyTypes": [
   "marriage",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/marco-a1.jpg"
 },
 {
  "id": "pia",
  "name": "Pia Peach",
  "collection": "core",
  "fruit": "peach",
  "emoji": "🍑",
  "hue": 18,
  "tag": "Rival",
  "role": "Glamorous other woman",
  "gender": "female",
  "voiceStyle": "sweet, teasing",
  "storyTypes": [
   "marriage",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/pia-a2.jpg"
 },
 {
  "id": "rick",
  "name": "Rick Crisp",
  "collection": "core",
  "fruit": "apple",
  "emoji": "🍎",
  "hue": 0,
  "tag": "Boss",
  "role": "Loud CEO, bad liar",
  "gender": "male",
  "voiceStyle": "loud, blustering",
  "storyTypes": [
   "office",
   "marriage"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/rick-a1.jpg"
 },
 {
  "id": "bella",
  "name": "Bella Berry",
  "collection": "core",
  "fruit": "strawberry",
  "emoji": "🍓",
  "hue": 350,
  "tag": "Intern",
  "role": "Sweet intern with secrets",
  "gender": "female",
  "voiceStyle": "bright, nervous",
  "storyTypes": [
   "office",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/bella-a1.jpg"
 },
 {
  "id": "marg",
  "name": "Margaret Crisp",
  "collection": "core",
  "fruit": "green apple",
  "emoji": "🍏",
  "hue": 95,
  "tag": "Wife",
  "role": "Icy co-founder",
  "gender": "female",
  "voiceStyle": "cold, precise",
  "storyTypes": [
   "office",
   "marriage",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/marg-a1.jpg"
 },
 {
  "id": "gloria",
  "name": "Gloria Grape",
  "collection": "core",
  "fruit": "grape",
  "emoji": "🍇",
  "hue": 275,
  "tag": "Receptionist",
  "role": "Office gossip, 19 years",
  "gender": "female",
  "voiceStyle": "fast, gleeful",
  "storyTypes": [
   "office"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/gloria-a1.jpg"
 },
 {
  "id": "linda",
  "name": "Linda Lemon",
  "collection": "core",
  "fruit": "lemon",
  "emoji": "🍋",
  "hue": 55,
  "tag": "HR",
  "role": "Sour HR director",
  "gender": "female",
  "voiceStyle": "clipped, formal",
  "storyTypes": [
   "office"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/linda-a1.jpg"
 },
 {
  "id": "benny",
  "name": "Benny Banana",
  "collection": "core",
  "fruit": "banana",
  "emoji": "🍌",
  "hue": 48,
  "tag": "Boyfriend",
  "role": "Nervous over-explainer",
  "gender": "male",
  "voiceStyle": "fast, shaky",
  "storyTypes": [
   "dating",
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/benny-a1.jpg"
 },
 {
  "id": "pina",
  "name": "Big Pina",
  "collection": "core",
  "fruit": "pineapple",
  "emoji": "🍍",
  "hue": 42,
  "tag": "Kingpin",
  "role": "Cellblock kingpin",
  "gender": "male",
  "voiceStyle": "deep, slow, menacing",
  "storyTypes": [
   "crime"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/pina-a1.jpg"
 },
 {
  "id": "coco",
  "name": "Coco",
  "collection": "core",
  "fruit": "coconut",
  "emoji": "🥥",
  "hue": 100,
  "tag": "Enforcer",
  "role": "Silent enforcer",
  "gender": "male",
  "voiceStyle": "rare, gravelly",
  "storyTypes": [
   "crime"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/coco-a3.jpg"
 },
 {
  "id": "olive",
  "name": "Olivia Orange",
  "collection": "core",
  "fruit": "orange",
  "emoji": "🍊",
  "hue": 28,
  "tag": "Mom",
  "role": "Protective mom",
  "gender": "female",
  "voiceStyle": "warm, firm",
  "storyTypes": [
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/olive-a1.jpg"
 },
 {
  "id": "kiki",
  "name": "Kiki Kiwi",
  "collection": "core",
  "fruit": "kiwi",
  "emoji": "🥝",
  "hue": 88,
  "tag": "Friend",
  "role": "Loyal best friend",
  "gender": "female",
  "voiceStyle": "upbeat, loyal",
  "storyTypes": [
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/kiki-a1.jpg"
 },
 {
  "id": "walt",
  "name": "Walt Melon",
  "collection": "core",
  "fruit": "watermelon",
  "emoji": "🍉",
  "hue": 140,
  "tag": "Husband",
  "role": "Rich, clueless husband",
  "gender": "male",
  "voiceStyle": "cheerful, oblivious",
  "storyTypes": [
   "marriage",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/walt-a1.jpg"
 },
 {
  "id": "ana",
  "name": "Ana Pineapple",
  "collection": "core",
  "fruit": "pineapple",
  "emoji": "🍍",
  "hue": 42,
  "tag": "Influencer",
  "role": "Lives for the drama",
  "gender": "female",
  "voiceStyle": "bubbly, dramatic",
  "storyTypes": [
   "social",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/ana-a1.jpg"
 },
 {
  "id": "sally",
  "name": "Sally Strawberry",
  "collection": "core",
  "fruit": "strawberry",
  "emoji": "🍓",
  "hue": 350,
  "tag": "Mother-in-law",
  "role": "Never leaves, never forgets",
  "gender": "female",
  "voiceStyle": "sweet, passive-aggressive",
  "storyTypes": [
   "family",
   "marriage"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/sally-a1.jpg"
 },
 {
  "id": "andy",
  "name": "Andy Apple",
  "collection": "core",
  "fruit": "apple",
  "emoji": "🍎",
  "hue": 0,
  "tag": "Son",
  "role": "Spoiled only child",
  "gender": "male",
  "voiceStyle": "whiny, entitled",
  "storyTypes": [
   "family",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/andy-a1.jpg"
 },
 {
  "id": "adam",
  "name": "Adam Apple",
  "collection": "core",
  "fruit": "apple",
  "emoji": "🍎",
  "hue": 0,
  "tag": "Trainer",
  "role": "Personal trainer the wife keeps booking",
  "gender": "male",
  "voiceStyle": "loud, pumped",
  "storyTypes": [
   "marriage",
   "sports"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/adam-a1.jpg"
 },
 {
  "id": "abby",
  "name": "Abby Apple",
  "collection": "core",
  "fruit": "apple",
  "emoji": "🍎",
  "hue": 0,
  "tag": "Nurse",
  "role": "Kind nurse who hears everything",
  "gender": "female",
  "voiceStyle": "gentle, quick",
  "storyTypes": [
   "hospital"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/abby-a1.jpg"
 },
 {
  "id": "gus",
  "name": "Gus Gala",
  "collection": "core",
  "fruit": "apple",
  "emoji": "🍎",
  "hue": 0,
  "tag": "Grandpa",
  "role": "Grumpy grandpa rewriting his will",
  "gender": "male",
  "voiceStyle": "gravelly, stubborn",
  "storyTypes": [
   "family",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/gus-a1.jpg"
 },
 {
  "id": "fiona",
  "name": "Fiona Fuji",
  "collection": "core",
  "fruit": "apple",
  "emoji": "🍎",
  "hue": 0,
  "tag": "Wife",
  "role": "Teacher wife who found the receipts",
  "gender": "female",
  "voiceStyle": "crisp, precise",
  "storyTypes": [
   "marriage",
   "school"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/fiona-a1.jpg"
 },
 {
  "id": "candy",
  "name": "Candy Cortland",
  "collection": "core",
  "fruit": "apple",
  "emoji": "🍎",
  "hue": 0,
  "tag": "Realtor",
  "role": "Pushy realtor who lies about everything",
  "gender": "female",
  "voiceStyle": "salesy, bright",
  "storyTypes": [
   "office",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/candy-a1.jpg"
 },
 {
  "id": "grace",
  "name": "Grace Smith",
  "collection": "core",
  "fruit": "green apple",
  "emoji": "🍏",
  "hue": 95,
  "tag": "Grandma",
  "role": "Sweet grandma, sharp tongue",
  "gender": "female",
  "voiceStyle": "sweet, sly",
  "storyTypes": [
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/grace-a1.jpg"
 },
 {
  "id": "greg",
  "name": "Greg Green",
  "collection": "core",
  "fruit": "green apple",
  "emoji": "🍏",
  "hue": 95,
  "tag": "Accountant",
  "role": "Nervous accountant cooking the books",
  "gender": "male",
  "voiceStyle": "mumbling, anxious",
  "storyTypes": [
   "office",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/greg-a1.jpg"
 },
 {
  "id": "vic",
  "name": "Vic Sour",
  "collection": "core",
  "fruit": "green apple",
  "emoji": "🍏",
  "hue": 95,
  "tag": "Rival VP",
  "role": "Rival VP gunning for the CEO job",
  "gender": "male",
  "voiceStyle": "nasal, smug",
  "storyTypes": [
   "office"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/vic-a1.jpg"
 },
 {
  "id": "jade",
  "name": "Jade Apple",
  "collection": "core",
  "fruit": "green apple",
  "emoji": "🍏",
  "hue": 95,
  "tag": "Student",
  "role": "Overachiever with a secret TikTok",
  "gender": "female",
  "voiceStyle": "quick, bright",
  "storyTypes": [
   "school",
   "social"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/jade-a1.jpg"
 },
 {
  "id": "manny",
  "name": "Manny Mango",
  "collection": "core",
  "fruit": "mango",
  "emoji": "🥭",
  "hue": 38,
  "tag": "Father-in-law",
  "role": "Old-school dad who hates the groom",
  "gender": "male",
  "voiceStyle": "booming, proud",
  "storyTypes": [
   "family",
   "wedding"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/manny-a1.jpg"
 },
 {
  "id": "maya",
  "name": "Maya Mango",
  "collection": "core",
  "fruit": "mango",
  "emoji": "🥭",
  "hue": 38,
  "tag": "Sister",
  "role": "Little sister who spills everything",
  "gender": "female",
  "voiceStyle": "bubbly, fast",
  "storyTypes": [
   "family",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/maya-a1.jpg"
 },
 {
  "id": "milo",
  "name": "Milo Mango",
  "collection": "core",
  "fruit": "mango",
  "emoji": "🥭",
  "hue": 38,
  "tag": "Brother",
  "role": "Freeloading brother on the couch",
  "gender": "male",
  "voiceStyle": "lazy, charming",
  "storyTypes": [
   "family",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/milo-a1.jpg"
 },
 {
  "id": "ali",
  "name": "Ali Alphonso",
  "collection": "core",
  "fruit": "mango",
  "emoji": "🥭",
  "hue": 38,
  "tag": "Chef",
  "role": "Hot-tempered celebrity chef",
  "gender": "male",
  "voiceStyle": "fiery, loud",
  "storyTypes": [
   "service",
   "social"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/ali-a1.jpg"
 },
 {
  "id": "dina",
  "name": "Dina Dulce",
  "collection": "core",
  "fruit": "mango",
  "emoji": "🥭",
  "hue": 38,
  "tag": "Wedding planner",
  "role": "Wedding planner who's seen it all",
  "gender": "female",
  "voiceStyle": "brisk, dramatic",
  "storyTypes": [
   "wedding"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/dina-a1.jpg"
 },
 {
  "id": "paige",
  "name": "Paige Peach",
  "collection": "core",
  "fruit": "peach",
  "emoji": "🍑",
  "hue": 18,
  "tag": "Influencer",
  "role": "Brand-deal queen, fake perfect life",
  "gender": "female",
  "voiceStyle": "breathy, upbeat",
  "storyTypes": [
   "social"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/paige-a2.jpg"
 },
 {
  "id": "pete",
  "name": "Pete Peach",
  "collection": "core",
  "fruit": "peach",
  "emoji": "🍑",
  "hue": 18,
  "tag": "Dad",
  "role": "Dad-joke dad hiding a second phone",
  "gender": "male",
  "voiceStyle": "warm, corny",
  "storyTypes": [
   "family",
   "marriage"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/pete-a1.jpg"
 },
 {
  "id": "georgia",
  "name": "Georgia Peach",
  "collection": "core",
  "fruit": "peach",
  "emoji": "🍑",
  "hue": 18,
  "tag": "Rich widow",
  "role": "Southern widow, five husbands",
  "gender": "female",
  "voiceStyle": "slow, sugary",
  "storyTypes": [
   "money",
   "marriage"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/georgia-a1.jpg"
 },
 {
  "id": "percy",
  "name": "Percy Peach",
  "collection": "core",
  "fruit": "peach",
  "emoji": "🍑",
  "hue": 18,
  "tag": "Waiter",
  "role": "Actor-slash-waiter, always auditioning",
  "gender": "male",
  "voiceStyle": "theatrical",
  "storyTypes": [
   "service",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/percy-a1.jpg"
 },
 {
  "id": "penny",
  "name": "Penny Peach",
  "collection": "core",
  "fruit": "peach",
  "emoji": "🍑",
  "hue": 18,
  "tag": "Divorce lawyer",
  "role": "Shark divorce lawyer",
  "gender": "female",
  "voiceStyle": "cool, cutting",
  "storyTypes": [
   "law",
   "marriage"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/penny-a2.jpg"
 },
 {
  "id": "hank",
  "name": "Hank Peach",
  "collection": "core",
  "fruit": "peach",
  "emoji": "🍑",
  "hue": 18,
  "tag": "Security guard",
  "role": "Night guard who watches all the cameras",
  "gender": "male",
  "voiceStyle": "slow, dry",
  "storyTypes": [
   "office",
   "crime"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/hank-a1.jpg"
 },
 {
  "id": "stan",
  "name": "Stan Straw",
  "collection": "core",
  "fruit": "strawberry",
  "emoji": "🍓",
  "hue": 350,
  "tag": "Mailroom guy",
  "role": "Mailroom guy who reads the memos",
  "gender": "male",
  "voiceStyle": "casual, nosy",
  "storyTypes": [
   "office"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/stan-a1.jpg"
 },
 {
  "id": "rosa",
  "name": "Rosa Red",
  "collection": "core",
  "fruit": "strawberry",
  "emoji": "🍓",
  "hue": 350,
  "tag": "Bride",
  "role": "Bridezilla counting every gift",
  "gender": "female",
  "voiceStyle": "shrill, demanding",
  "storyTypes": [
   "wedding"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/rosa-a1.jpg"
 },
 {
  "id": "stella",
  "name": "Stella Berry",
  "collection": "core",
  "fruit": "strawberry",
  "emoji": "🍓",
  "hue": 350,
  "tag": "Hairdresser",
  "role": "Salon owner, knows every secret",
  "gender": "female",
  "voiceStyle": "chatty, loud",
  "storyTypes": [
   "service",
   "neighbors"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/stella-a1.jpg"
 },
 {
  "id": "jimmy",
  "name": "Jimmy Jam",
  "collection": "core",
  "fruit": "strawberry",
  "emoji": "🍓",
  "hue": 350,
  "tag": "Streamer",
  "role": "Loud gaming streamer",
  "gender": "male",
  "voiceStyle": "hyper, loud",
  "storyTypes": [
   "social"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/jimmy-a1.jpg"
 },
 {
  "id": "sid",
  "name": "Sid Shortcake",
  "collection": "core",
  "fruit": "strawberry",
  "emoji": "🍓",
  "hue": 350,
  "tag": "Judge",
  "role": "Stern judge with a soft heart",
  "gender": "male",
  "voiceStyle": "measured, deep",
  "storyTypes": [
   "law"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/sid-a1.jpg"
 },
 {
  "id": "greta",
  "name": "Greta Grape",
  "collection": "core",
  "fruit": "grape",
  "emoji": "🍇",
  "hue": 275,
  "tag": "Maid of honor",
  "role": "Maid of honor in love with the groom",
  "gender": "female",
  "voiceStyle": "sweet, guilty",
  "storyTypes": [
   "wedding",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/greta-a1.jpg"
 },
 {
  "id": "vinny",
  "name": "Vinny Vine",
  "collection": "core",
  "fruit": "grape",
  "emoji": "🍇",
  "hue": 275,
  "tag": "Con artist",
  "role": "Smooth con man with ten names",
  "gender": "male",
  "voiceStyle": "silky, fast",
  "storyTypes": [
   "crime",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/vinny-a1.jpg"
 },
 {
  "id": "gordon",
  "name": "Gordon Grape",
  "collection": "core",
  "fruit": "grape",
  "emoji": "🍇",
  "hue": 275,
  "tag": "Mayor",
  "role": "Small-town mayor with big secrets",
  "gender": "male",
  "voiceStyle": "booming, slick",
  "storyTypes": [
   "social",
   "neighbors"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/gordon-a1.jpg"
 },
 {
  "id": "connie",
  "name": "Connie Concord",
  "collection": "core",
  "fruit": "grape",
  "emoji": "🍇",
  "hue": 275,
  "tag": "Stepmom",
  "role": "Stepmom who wants the house",
  "gender": "female",
  "voiceStyle": "sweet, icy",
  "storyTypes": [
   "family",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/connie-a1.jpg"
 },
 {
  "id": "gabe",
  "name": "Gabe Grape",
  "collection": "core",
  "fruit": "grape",
  "emoji": "🍇",
  "hue": 275,
  "tag": "Bartender",
  "role": "Bartender who hears every confession",
  "gender": "male",
  "voiceStyle": "smooth, low",
  "storyTypes": [
   "service",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/gabe-a1.jpg"
 },
 {
  "id": "lenny",
  "name": "Lenny Lemon",
  "collection": "core",
  "fruit": "lemon",
  "emoji": "🍋",
  "hue": 55,
  "tag": "Landlord",
  "role": "Landlord who raises rent every scene",
  "gender": "male",
  "voiceStyle": "gruff, greedy",
  "storyTypes": [
   "neighbors",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/lenny-a1.jpg"
 },
 {
  "id": "lola",
  "name": "Lola Lemon",
  "collection": "core",
  "fruit": "lemon",
  "emoji": "🍋",
  "hue": 55,
  "tag": "Barista",
  "role": "Sarcastic barista, remembers every order",
  "gender": "female",
  "voiceStyle": "dry, sharp",
  "storyTypes": [
   "service",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/lola-a1.jpg"
 },
 {
  "id": "larry",
  "name": "Larry Zest",
  "collection": "core",
  "fruit": "lemon",
  "emoji": "🍋",
  "hue": 55,
  "tag": "Cop",
  "role": "Sour cop who never smiles",
  "gender": "male",
  "voiceStyle": "flat, tough",
  "storyTypes": [
   "law",
   "crime"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/larry-a1.jpg"
 },
 {
  "id": "lucy",
  "name": "Lucy Lemon",
  "collection": "core",
  "fruit": "lemon",
  "emoji": "🍋",
  "hue": 55,
  "tag": "Intern",
  "role": "Intern who wants the boss's job",
  "gender": "female",
  "voiceStyle": "sweet, ambitious",
  "storyTypes": [
   "office",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/lucy-a1.jpg"
 },
 {
  "id": "martin",
  "name": "Martin Meyer",
  "collection": "core",
  "fruit": "lemon",
  "emoji": "🍋",
  "hue": 55,
  "tag": "Founder",
  "role": "Retired founder who shows up unannounced",
  "gender": "male",
  "voiceStyle": "tired, formal",
  "storyTypes": [
   "office",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/martin-a1.jpg"
 },
 {
  "id": "lionel",
  "name": "Lionel Lime",
  "collection": "core",
  "fruit": "lime",
  "emoji": "🍋‍🟩",
  "hue": 90,
  "tag": "Private eye",
  "role": "PI hired to follow the husband",
  "gender": "male",
  "voiceStyle": "low, noir",
  "storyTypes": [
   "law",
   "marriage"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/lionel-a1.jpg"
 },
 {
  "id": "lila",
  "name": "Lila Lime",
  "collection": "core",
  "fruit": "lime",
  "emoji": "🍋‍🟩",
  "hue": 90,
  "tag": "Marketing lead",
  "role": "Marketing lead who steals ideas",
  "gender": "female",
  "voiceStyle": "peppy, fake",
  "storyTypes": [
   "office",
   "social"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/lila-a1.jpg"
 },
 {
  "id": "kay",
  "name": "Kay Key",
  "collection": "core",
  "fruit": "lime",
  "emoji": "🍋‍🟩",
  "hue": 90,
  "tag": "Secretary",
  "role": "Executive secretary for 30 years",
  "gender": "female",
  "voiceStyle": "whispery, sharp",
  "storyTypes": [
   "office"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/kay-a1.jpg"
 },
 {
  "id": "leo",
  "name": "Leo Lime",
  "collection": "core",
  "fruit": "lime",
  "emoji": "🍋‍🟩",
  "hue": 90,
  "tag": "Young lover",
  "role": "Wife's much younger secret lover",
  "gender": "male",
  "voiceStyle": "loud, lazy",
  "storyTypes": [
   "marriage",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/leo-a1.jpg"
 },
 {
  "id": "bruno",
  "name": "Bruno Banana",
  "collection": "core",
  "fruit": "banana",
  "emoji": "🍌",
  "hue": 48,
  "tag": "Sales rep",
  "role": "Top sales rep who fakes his numbers",
  "gender": "male",
  "voiceStyle": "loud, pushy",
  "storyTypes": [
   "office"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/bruno-a1.jpg"
 },
 {
  "id": "bea",
  "name": "Bea Banana",
  "collection": "core",
  "fruit": "banana",
  "emoji": "🍌",
  "hue": 48,
  "tag": "Flight attendant",
  "role": "Flight attendant with a man in every city",
  "gender": "female",
  "voiceStyle": "sweet, sly",
  "storyTypes": [
   "service",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/bea-a1.jpg"
 },
 {
  "id": "barb",
  "name": "Barb Bunch",
  "collection": "core",
  "fruit": "banana",
  "emoji": "🍌",
  "hue": 48,
  "tag": "Aunt",
  "role": "Aunt who brings drama to every holiday",
  "gender": "female",
  "voiceStyle": "loud, nosy",
  "storyTypes": [
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/barb-a1.jpg"
 },
 {
  "id": "buddy",
  "name": "Buddy Banana",
  "collection": "core",
  "fruit": "banana",
  "emoji": "🍌",
  "hue": 48,
  "tag": "Taxi driver",
  "role": "Taxi driver who knows every affair",
  "gender": "male",
  "voiceStyle": "chatty, gravelly",
  "storyTypes": [
   "service",
   "marriage"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/buddy-a1.jpg"
 },
 {
  "id": "bonnie",
  "name": "Bonnie Banana",
  "collection": "core",
  "fruit": "banana",
  "emoji": "🍌",
  "hue": 48,
  "tag": "Pop star",
  "role": "Pop star with a secret boyfriend",
  "gender": "female",
  "voiceStyle": "sing-song, bratty",
  "storyTypes": [
   "social",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/bonnie-a1.jpg"
 },
 {
  "id": "chip",
  "name": "Chip Cavendish",
  "collection": "core",
  "fruit": "banana",
  "emoji": "🍌",
  "hue": 48,
  "tag": "Groom",
  "role": "Groom with cold feet",
  "gender": "male",
  "voiceStyle": "nervous, sweet",
  "storyTypes": [
   "wedding"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/chip-a1.jpg"
 },
 {
  "id": "pablo",
  "name": "Pablo Pine",
  "collection": "core",
  "fruit": "pineapple",
  "emoji": "🍍",
  "hue": 42,
  "tag": "Inmate",
  "role": "New inmate who talks too much",
  "gender": "male",
  "voiceStyle": "fast, nervous",
  "storyTypes": [
   "crime"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/pablo-a1.jpg"
 },
 {
  "id": "pam",
  "name": "Pam Pineapple",
  "collection": "core",
  "fruit": "pineapple",
  "emoji": "🍍",
  "hue": 42,
  "tag": "Warden",
  "role": "Warden with a soft spot",
  "gender": "female",
  "voiceStyle": "stern, tired",
  "storyTypes": [
   "crime",
   "law"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/pam-a1.jpg"
 },
 {
  "id": "tony",
  "name": "Tony Tropic",
  "collection": "core",
  "fruit": "pineapple",
  "emoji": "🍍",
  "hue": 42,
  "tag": "Resort owner",
  "role": "Resort owner hiding debt",
  "gender": "male",
  "voiceStyle": "smooth, jovial",
  "storyTypes": [
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/tony-a1.jpg"
 },
 {
  "id": "piper",
  "name": "Piper Pine",
  "collection": "core",
  "fruit": "pineapple",
  "emoji": "🍍",
  "hue": 42,
  "tag": "Reality star",
  "role": "Reality-show villain",
  "gender": "female",
  "voiceStyle": "sassy, loud",
  "storyTypes": [
   "social",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/piper-a1.jpg"
 },
 {
  "id": "carl",
  "name": "Carl Coconut",
  "collection": "core",
  "fruit": "coconut",
  "emoji": "🥥",
  "hue": 100,
  "tag": "Prison guard",
  "role": "Prison guard taking bribes",
  "gender": "male",
  "voiceStyle": "bored, gruff",
  "storyTypes": [
   "crime"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/carl-a3.jpg"
 },
 {
  "id": "cora",
  "name": "Cora Coconut",
  "collection": "core",
  "fruit": "coconut",
  "emoji": "🥥",
  "hue": 100,
  "tag": "Surgeon",
  "role": "Cold-blooded star surgeon",
  "gender": "female",
  "voiceStyle": "clipped, calm",
  "storyTypes": [
   "hospital"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/cora-a3.jpg"
 },
 {
  "id": "kai",
  "name": "Kai Coconut",
  "collection": "core",
  "fruit": "coconut",
  "emoji": "🥥",
  "hue": 100,
  "tag": "Lifeguard",
  "role": "Lifeguard dating a married woman",
  "gender": "male",
  "voiceStyle": "laid-back",
  "storyTypes": [
   "marriage",
   "sports"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/kai-a3.jpg"
 },
 {
  "id": "hazel",
  "name": "Hazel Husk",
  "collection": "core",
  "fruit": "coconut",
  "emoji": "🥥",
  "hue": 100,
  "tag": "Fortune teller",
  "role": "Fortune teller who's always right",
  "gender": "female",
  "voiceStyle": "mystic, slow",
  "storyTypes": [
   "social",
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/hazel-a3.jpg"
 },
 {
  "id": "oscar",
  "name": "Oscar Orange",
  "collection": "core",
  "fruit": "orange",
  "emoji": "🍊",
  "hue": 28,
  "tag": "Dad",
  "role": "Dad having a midlife crisis",
  "gender": "male",
  "voiceStyle": "cheerful, clueless",
  "storyTypes": [
   "family",
   "marriage"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/oscar-a1.jpg"
 },
 {
  "id": "clara",
  "name": "Clara Clementine",
  "collection": "core",
  "fruit": "orange",
  "emoji": "🍊",
  "hue": 28,
  "tag": "Daughter",
  "role": "Daughter who brought home a 50-year-old",
  "gender": "female",
  "voiceStyle": "defiant, bright",
  "storyTypes": [
   "family",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/clara-a1.jpg"
 },
 {
  "id": "otto",
  "name": "Otto Orange",
  "collection": "core",
  "fruit": "orange",
  "emoji": "🍊",
  "hue": 28,
  "tag": "Butler",
  "role": "Butler who knows where bodies are buried",
  "gender": "male",
  "voiceStyle": "dry, formal",
  "storyTypes": [
   "money",
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/otto-a2.jpg"
 },
 {
  "id": "tanya",
  "name": "Tanya Tangerine",
  "collection": "core",
  "fruit": "orange",
  "emoji": "🍊",
  "hue": 28,
  "tag": "Cashier",
  "role": "Cashier who judges your groceries",
  "gender": "female",
  "voiceStyle": "bored, sassy",
  "storyTypes": [
   "service"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/tanya-a1.jpg"
 },
 {
  "id": "jojo",
  "name": "Jojo Juice",
  "collection": "core",
  "fruit": "orange",
  "emoji": "🍊",
  "hue": 28,
  "tag": "Best man",
  "role": "Best man with a terrible speech",
  "gender": "male",
  "voiceStyle": "loud, sloppy",
  "storyTypes": [
   "wedding",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/jojo-a1.jpg"
 },
 {
  "id": "mandy",
  "name": "Mandy Mandarin",
  "collection": "core",
  "fruit": "orange",
  "emoji": "🍊",
  "hue": 28,
  "tag": "Talk show host",
  "role": "Daytime talk show host",
  "gender": "female",
  "voiceStyle": "bright, dramatic",
  "storyTypes": [
   "social"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/mandy-a1.jpg"
 },
 {
  "id": "ken",
  "name": "Ken Kiwi",
  "collection": "core",
  "fruit": "kiwi",
  "emoji": "🥝",
  "hue": 88,
  "tag": "IT guy",
  "role": "IT guy who reads everyone's email",
  "gender": "male",
  "voiceStyle": "monotone, smug",
  "storyTypes": [
   "office"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/ken-a1.jpg"
 },
 {
  "id": "nora",
  "name": "Nora Kiwi",
  "collection": "core",
  "fruit": "kiwi",
  "emoji": "🥝",
  "hue": 88,
  "tag": "Counselor",
  "role": "Marriage counselor who takes sides",
  "gender": "female",
  "voiceStyle": "soothing, nosy",
  "storyTypes": [
   "marriage"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/nora-a1.jpg"
 },
 {
  "id": "kurt",
  "name": "Kurt Kiwi",
  "collection": "core",
  "fruit": "kiwi",
  "emoji": "🥝",
  "hue": 88,
  "tag": "Rookie cop",
  "role": "Rookie cop, first week",
  "gender": "male",
  "voiceStyle": "eager, squeaky",
  "storyTypes": [
   "law"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/kurt-a1.jpg"
 },
 {
  "id": "wanda",
  "name": "Wanda Melon",
  "collection": "core",
  "fruit": "watermelon",
  "emoji": "🍉",
  "hue": 140,
  "tag": "Trophy wife",
  "role": "Rich housewife with a pool boy",
  "gender": "female",
  "voiceStyle": "lazy, sweet",
  "storyTypes": [
   "marriage",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/wanda-a1.jpg"
 },
 {
  "id": "mel",
  "name": "Mel Melon",
  "collection": "core",
  "fruit": "watermelon",
  "emoji": "🍉",
  "hue": 140,
  "tag": "Pool guy",
  "role": "Pool guy with too many clients",
  "gender": "male",
  "voiceStyle": "relaxed, flirty",
  "storyTypes": [
   "dating",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/mel-a1.jpg"
 },
 {
  "id": "rhonda",
  "name": "Rhonda Rind",
  "collection": "core",
  "fruit": "watermelon",
  "emoji": "🍉",
  "hue": 140,
  "tag": "Wife",
  "role": "PTA mom who suspects her husband",
  "gender": "female",
  "voiceStyle": "shrill, bossy",
  "storyTypes": [
   "marriage",
   "school"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/rhonda-a1.jpg"
 },
 {
  "id": "wes",
  "name": "Wes Watermelon",
  "collection": "core",
  "fruit": "watermelon",
  "emoji": "🍉",
  "hue": 140,
  "tag": "Athlete",
  "role": "Athlete caught with the coach's wife",
  "gender": "male",
  "voiceStyle": "cocky",
  "storyTypes": [
   "marriage",
   "sports"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/wes-a1.jpg"
 },
 {
  "id": "chloe",
  "name": "Chloe Cherry",
  "collection": "core",
  "fruit": "cherry",
  "emoji": "🍒",
  "hue": 350,
  "tag": "Girlfriend",
  "role": "Jealous girlfriend who checks his phone",
  "gender": "female",
  "voiceStyle": "sweet, sharp",
  "storyTypes": [
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/chloe-a1.jpg"
 },
 {
  "id": "charlie",
  "name": "Charlie Cherry",
  "collection": "core",
  "fruit": "cherry",
  "emoji": "🍒",
  "hue": 350,
  "tag": "Husband",
  "role": "Cheating husband on a 'work trip'",
  "gender": "male",
  "voiceStyle": "smooth, nervous",
  "storyTypes": [
   "marriage"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/charlie-a1.jpg"
 },
 {
  "id": "carmen",
  "name": "Carmen Cherry",
  "collection": "core",
  "fruit": "cherry",
  "emoji": "🍒",
  "hue": 350,
  "tag": "Mistress",
  "role": "Other woman who wants a ring",
  "gender": "female",
  "voiceStyle": "sultry, bold",
  "storyTypes": [
   "marriage",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/carmen-a1.jpg"
 },
 {
  "id": "chuck",
  "name": "Chuck Cherry",
  "collection": "core",
  "fruit": "cherry",
  "emoji": "🍒",
  "hue": 350,
  "tag": "Husband",
  "role": "Retired husband who suspects everyone",
  "gender": "male",
  "voiceStyle": "grumbly",
  "storyTypes": [
   "marriage",
   "neighbors"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/chuck-a1.jpg"
 },
 {
  "id": "bing",
  "name": "Bing Cherry",
  "collection": "core",
  "fruit": "cherry",
  "emoji": "🍒",
  "hue": 350,
  "tag": "Blind date",
  "role": "Dating-app date with fake photos",
  "gender": "male",
  "voiceStyle": "awkward, eager",
  "storyTypes": [
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/bing-a1.jpg"
 },
 {
  "id": "tara",
  "name": "Tara Cherry",
  "collection": "core",
  "fruit": "cherry",
  "emoji": "🍒",
  "hue": 350,
  "tag": "Hotel manager",
  "role": "Hotel manager covering scandals",
  "gender": "female",
  "voiceStyle": "polished",
  "storyTypes": [
   "service",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/tara-a1.jpg"
 },
 {
  "id": "perry",
  "name": "Perry Pear",
  "collection": "core",
  "fruit": "pear",
  "emoji": "🍐",
  "hue": 75,
  "tag": "Manager",
  "role": "Middle manager who takes credit",
  "gender": "male",
  "voiceStyle": "whiny, smug",
  "storyTypes": [
   "office"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/perry-a1.jpg"
 },
 {
  "id": "paula",
  "name": "Paula Pear",
  "collection": "core",
  "fruit": "pear",
  "emoji": "🍐",
  "hue": 75,
  "tag": "Neighbor",
  "role": "Perfect neighbor with a dark secret",
  "gender": "female",
  "voiceStyle": "sweet, whispery",
  "storyTypes": [
   "neighbors",
   "marriage"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/paula-a1.jpg"
 },
 {
  "id": "bart",
  "name": "Bart Bartlett",
  "collection": "core",
  "fruit": "pear",
  "emoji": "🍐",
  "hue": 75,
  "tag": "Billionaire",
  "role": "Billionaire who fakes being broke",
  "gender": "male",
  "voiceStyle": "dry, amused",
  "storyTypes": [
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/bart-a1.jpg"
 },
 {
  "id": "anya",
  "name": "Anya Anjou",
  "collection": "core",
  "fruit": "pear",
  "emoji": "🍐",
  "hue": 75,
  "tag": "Assistant",
  "role": "Assistant who secretly runs the company",
  "gender": "female",
  "voiceStyle": "calm, efficient",
  "storyTypes": [
   "office"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/anya-a1.jpg"
 },
 {
  "id": "boris",
  "name": "Boris Bosc",
  "collection": "core",
  "fruit": "pear",
  "emoji": "🍐",
  "hue": 75,
  "tag": "Heist planner",
  "role": "Heist planner, always has a plan B",
  "gender": "male",
  "voiceStyle": "slow, calculating",
  "storyTypes": [
   "crime"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/boris-a1.jpg"
 },
 {
  "id": "polly",
  "name": "Polly Plum",
  "collection": "core",
  "fruit": "plum",
  "emoji": "🟣",
  "hue": 300,
  "tag": "Grandma",
  "role": "Grandma with a secret boyfriend",
  "gender": "female",
  "voiceStyle": "sweet, giggly",
  "storyTypes": [
   "family",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/polly-a1.jpg"
 },
 {
  "id": "philip",
  "name": "Philip Plum",
  "collection": "core",
  "fruit": "plum",
  "emoji": "🟣",
  "hue": 300,
  "tag": "CFO",
  "role": "CFO hiding the real numbers",
  "gender": "male",
  "voiceStyle": "pompous",
  "storyTypes": [
   "office",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/philip-a1.jpg"
 },
 {
  "id": "priya",
  "name": "Priya Plum",
  "collection": "core",
  "fruit": "plum",
  "emoji": "🟣",
  "hue": 300,
  "tag": "Doctor",
  "role": "ER doctor, no patience",
  "gender": "female",
  "voiceStyle": "fast, blunt",
  "storyTypes": [
   "hospital"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/priya-a1.jpg"
 },
 {
  "id": "dan",
  "name": "Dan Damson",
  "collection": "core",
  "fruit": "plum",
  "emoji": "🟣",
  "hue": 300,
  "tag": "Mechanic",
  "role": "Mechanic who overcharges everyone",
  "gender": "male",
  "voiceStyle": "easygoing, shady",
  "storyTypes": [
   "service"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/dan-a1.jpg"
 },
 {
  "id": "betty",
  "name": "Betty Blue",
  "collection": "core",
  "fruit": "blueberry",
  "emoji": "🫐",
  "hue": 235,
  "tag": "Single mom",
  "role": "Divorced mom back on the dating apps",
  "gender": "female",
  "voiceStyle": "hopeful, frazzled",
  "storyTypes": [
   "dating",
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/betty-a1.jpg"
 },
 {
  "id": "barry",
  "name": "Barry Blue",
  "collection": "core",
  "fruit": "blueberry",
  "emoji": "🫐",
  "hue": 235,
  "tag": "Car salesman",
  "role": "Car salesman who lies with a smile",
  "gender": "male",
  "voiceStyle": "fast, slick",
  "storyTypes": [
   "service",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/barry-a1.jpg"
 },
 {
  "id": "bree",
  "name": "Bree Blueberry",
  "collection": "core",
  "fruit": "blueberry",
  "emoji": "🫐",
  "hue": 235,
  "tag": "Babysitter",
  "role": "Babysitter who knows too much",
  "gender": "female",
  "voiceStyle": "chirpy, sly",
  "storyTypes": [
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/bree-a1.jpg"
 },
 {
  "id": "jay",
  "name": "Jay Blue",
  "collection": "core",
  "fruit": "blueberry",
  "emoji": "🫐",
  "hue": 235,
  "tag": "Paramedic",
  "role": "Paramedic, calm in any crisis",
  "gender": "male",
  "voiceStyle": "steady",
  "storyTypes": [
   "hospital"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/jay-a1.jpg"
 },
 {
  "id": "violet",
  "name": "Violet Blue",
  "collection": "core",
  "fruit": "blueberry",
  "emoji": "🫐",
  "hue": 235,
  "tag": "Gossip columnist",
  "role": "Gossip columnist with a big mouth",
  "gender": "female",
  "voiceStyle": "purring",
  "storyTypes": [
   "social"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/violet-a1.jpg"
 },
 {
  "id": "moe",
  "name": "Moe Blue",
  "collection": "core",
  "fruit": "blueberry",
  "emoji": "🫐",
  "hue": 235,
  "tag": "Bouncer",
  "role": "Bouncer who never lets anyone in",
  "gender": "male",
  "voiceStyle": "deep, blunt",
  "storyTypes": [
   "crime",
   "service"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/moe-a1.jpg"
 },
 {
  "id": "remy",
  "name": "Remy Raspberry",
  "collection": "core",
  "fruit": "raspberry",
  "emoji": "🔴",
  "hue": 340,
  "tag": "Sous-chef",
  "role": "Sous-chef plotting to take over",
  "gender": "male",
  "voiceStyle": "quiet, scheming",
  "storyTypes": [
   "service"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/remy-a1.jpg"
 },
 {
  "id": "rita",
  "name": "Rita Raspberry",
  "collection": "core",
  "fruit": "raspberry",
  "emoji": "🔴",
  "hue": 340,
  "tag": "Inmate",
  "role": "Cellblock queen",
  "gender": "female",
  "voiceStyle": "raspy, tough",
  "storyTypes": [
   "crime"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/rita-a1.jpg"
 },
 {
  "id": "ron",
  "name": "Ron Raspberry",
  "collection": "core",
  "fruit": "raspberry",
  "emoji": "🔴",
  "hue": 340,
  "tag": "Chairman",
  "role": "Company chairman who hates change",
  "gender": "male",
  "voiceStyle": "slow, booming",
  "storyTypes": [
   "office",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/ron-a1.jpg"
 },
 {
  "id": "rae",
  "name": "Rae Raspberry",
  "collection": "core",
  "fruit": "raspberry",
  "emoji": "🔴",
  "hue": 340,
  "tag": "Tattoo artist",
  "role": "Tattoo artist who covers exes' names",
  "gender": "female",
  "voiceStyle": "cool, low",
  "storyTypes": [
   "service",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/rae-a1.jpg"
 },
 {
  "id": "ava",
  "name": "Ava Avocado",
  "collection": "core",
  "fruit": "avocado",
  "emoji": "🥑",
  "hue": 100,
  "tag": "Tenant",
  "role": "Millennial who can't afford a house",
  "gender": "female",
  "voiceStyle": "whiny, funny",
  "storyTypes": [
   "neighbors",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/ava-a1.jpg"
 },
 {
  "id": "al",
  "name": "Al Avocado",
  "collection": "core",
  "fruit": "avocado",
  "emoji": "🥑",
  "hue": 100,
  "tag": "Mob accountant",
  "role": "Mob accountant, knows every number",
  "gender": "male",
  "voiceStyle": "quiet, sweaty",
  "storyTypes": [
   "crime",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/al-a1.jpg"
 },
 {
  "id": "hector",
  "name": "Hector Hass",
  "collection": "core",
  "fruit": "avocado",
  "emoji": "🥑",
  "hue": 100,
  "tag": "Lawyer",
  "role": "Flashy lawyer, never lost a case",
  "gender": "male",
  "voiceStyle": "smooth, loud",
  "storyTypes": [
   "law",
   "office"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/hector-a1.jpg"
 },
 {
  "id": "addie",
  "name": "Addie Avocado",
  "collection": "core",
  "fruit": "avocado",
  "emoji": "🥑",
  "hue": 100,
  "tag": "Wellness guru",
  "role": "Wellness guru selling nonsense",
  "gender": "female",
  "voiceStyle": "airy, calm",
  "storyTypes": [
   "social"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/addie-a1.jpg"
 },
 {
  "id": "andre",
  "name": "Andre Avocado",
  "collection": "core",
  "fruit": "avocado",
  "emoji": "🥑",
  "hue": 100,
  "tag": "Ex-husband",
  "role": "Ex-husband who wants her back",
  "gender": "male",
  "voiceStyle": "sad, charming",
  "storyTypes": [
   "marriage",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/andre-a1.jpg"
 },
 {
  "id": "edna",
  "name": "Edna Avocado",
  "collection": "core",
  "fruit": "avocado",
  "emoji": "🥑",
  "hue": 100,
  "tag": "Mother of the bride",
  "role": "Mother of the bride, hates everyone",
  "gender": "female",
  "voiceStyle": "shrill, proud",
  "storyTypes": [
   "wedding",
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/edna-a1.jpg"
 },
 {
  "id": "priscilla",
  "name": "Priscilla Pom",
  "collection": "core",
  "fruit": "pomegranate",
  "emoji": "🔴",
  "hue": 355,
  "tag": "Heiress",
  "role": "Old-money heiress",
  "gender": "female",
  "voiceStyle": "icy, grand",
  "storyTypes": [
   "money",
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/priscilla-a1.jpg"
 },
 {
  "id": "pedro",
  "name": "Pedro Pom",
  "collection": "core",
  "fruit": "pomegranate",
  "emoji": "🔴",
  "hue": 355,
  "tag": "Detective",
  "role": "Detective on the affair case",
  "gender": "male",
  "voiceStyle": "slow, sharp",
  "storyTypes": [
   "law",
   "crime"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/pedro-a1.jpg"
 },
 {
  "id": "ruby",
  "name": "Ruby Pom",
  "collection": "core",
  "fruit": "pomegranate",
  "emoji": "🔴",
  "hue": 355,
  "tag": "Nail tech",
  "role": "Nail tech who spreads rumors",
  "gender": "female",
  "voiceStyle": "chatty",
  "storyTypes": [
   "service"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/ruby-a1.jpg"
 },
 {
  "id": "omar",
  "name": "Omar Pom",
  "collection": "core",
  "fruit": "pomegranate",
  "emoji": "🔴",
  "hue": 355,
  "tag": "Restaurant owner",
  "role": "Restaurant owner in debt to the mob",
  "gender": "male",
  "voiceStyle": "warm, worried",
  "storyTypes": [
   "service",
   "crime"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/omar-a1.jpg"
 },
 {
  "id": "felix",
  "name": "Felix Fig",
  "collection": "core",
  "fruit": "fig",
  "emoji": "🟤",
  "hue": 320,
  "tag": "Barber",
  "role": "Barber who gives life advice",
  "gender": "male",
  "voiceStyle": "smooth, wise",
  "storyTypes": [
   "service",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/felix-a1.jpg"
 },
 {
  "id": "fran",
  "name": "Fran Fig",
  "collection": "core",
  "fruit": "fig",
  "emoji": "🟤",
  "hue": 320,
  "tag": "Widow",
  "role": "Widow with eyes on the neighbor",
  "gender": "female",
  "voiceStyle": "flirty, slow",
  "storyTypes": [
   "neighbors",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/fran-a1.jpg"
 },
 {
  "id": "farrah",
  "name": "Farrah Fig",
  "collection": "core",
  "fruit": "fig",
  "emoji": "🟤",
  "hue": 320,
  "tag": "Designer",
  "role": "Fashion designer, no filter",
  "gender": "female",
  "voiceStyle": "posh, cutting",
  "storyTypes": [
   "social"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/farrah-a1.jpg"
 },
 {
  "id": "pappy",
  "name": "Pappy Papaya",
  "collection": "core",
  "fruit": "papaya",
  "emoji": "🟠",
  "hue": 35,
  "tag": "Grandpa",
  "role": "Grandpa who says the quiet part loud",
  "gender": "male",
  "voiceStyle": "loud, cheeky",
  "storyTypes": [
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/pappy-a1.jpg"
 },
 {
  "id": "paco",
  "name": "Paco Papaya",
  "collection": "core",
  "fruit": "papaya",
  "emoji": "🟠",
  "hue": 35,
  "tag": "Food truck owner",
  "role": "Food truck owner, loud and proud",
  "gender": "male",
  "voiceStyle": "loud, cheerful",
  "storyTypes": [
   "service"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/paco-a1.jpg"
 },
 {
  "id": "pilar",
  "name": "Pilar Papaya",
  "collection": "core",
  "fruit": "papaya",
  "emoji": "🟠",
  "hue": 35,
  "tag": "Housekeeper",
  "role": "Housekeeper who sees everything",
  "gender": "female",
  "voiceStyle": "quiet, knowing",
  "storyTypes": [
   "money",
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/pilar-a1.jpg"
 },
 {
  "id": "patty",
  "name": "Patty Papaya",
  "collection": "core",
  "fruit": "papaya",
  "emoji": "🟠",
  "hue": 35,
  "tag": "Cheer coach",
  "role": "Cheer coach, extremely intense",
  "gender": "female",
  "voiceStyle": "shouty, peppy",
  "storyTypes": [
   "sports",
   "school"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/patty-a1.jpg"
 },
 {
  "id": "dex",
  "name": "Dex Dragon",
  "collection": "core",
  "fruit": "dragon fruit",
  "emoji": "🩷",
  "hue": 330,
  "tag": "Club owner",
  "role": "Nightclub owner with shady friends",
  "gender": "male",
  "voiceStyle": "smooth, low",
  "storyTypes": [
   "crime",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/dex-a1.jpg"
 },
 {
  "id": "daria",
  "name": "Daria Dragon",
  "collection": "core",
  "fruit": "dragon fruit",
  "emoji": "🩷",
  "hue": 330,
  "tag": "Rock star",
  "role": "Rock star on a comeback",
  "gender": "female",
  "voiceStyle": "raspy, wild",
  "storyTypes": [
   "social"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/daria-a1.jpg"
 },
 {
  "id": "dot",
  "name": "Dot Dragon",
  "collection": "core",
  "fruit": "dragon fruit",
  "emoji": "🩷",
  "hue": 330,
  "tag": "Rich aunt",
  "role": "Rich aunt who controls the family money",
  "gender": "female",
  "voiceStyle": "sly, sharp",
  "storyTypes": [
   "money",
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/dot-a1.jpg"
 },
 {
  "id": "ty",
  "name": "Ty Dragon",
  "collection": "core",
  "fruit": "dragon fruit",
  "emoji": "🩷",
  "hue": 330,
  "tag": "Rapper",
  "role": "Rapper who's never left the suburbs",
  "gender": "male",
  "voiceStyle": "cocky, loud",
  "storyTypes": [
   "social"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/ty-a1.jpg"
 },
 {
  "id": "gail",
  "name": "Gail Grapefruit",
  "collection": "core",
  "fruit": "grapefruit",
  "emoji": "🍊",
  "hue": 10,
  "tag": "Office manager",
  "role": "Office manager who controls the snacks",
  "gender": "female",
  "voiceStyle": "tight, bossy",
  "storyTypes": [
   "office"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/gail-a2.jpg"
 },
 {
  "id": "grant",
  "name": "Grant Grapefruit",
  "collection": "core",
  "fruit": "grapefruit",
  "emoji": "🍊",
  "hue": 10,
  "tag": "Politician",
  "role": "Politician with a hidden family",
  "gender": "male",
  "voiceStyle": "booming, fake",
  "storyTypes": [
   "social",
   "marriage"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/grant-a2.jpg"
 },
 {
  "id": "ruth",
  "name": "Ruth Grapefruit",
  "collection": "core",
  "fruit": "grapefruit",
  "emoji": "🍊",
  "hue": 10,
  "tag": "Grandma",
  "role": "Grandma who hates every girlfriend",
  "gender": "female",
  "voiceStyle": "sharp, dry",
  "storyTypes": [
   "family",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/ruth-a2.jpg"
 },
 {
  "id": "hal",
  "name": "Hal Grapefruit",
  "collection": "core",
  "fruit": "grapefruit",
  "emoji": "🍊",
  "hue": 10,
  "tag": "Gym teacher",
  "role": "Gym teacher who peaked in high school",
  "gender": "male",
  "voiceStyle": "shouty",
  "storyTypes": [
   "school",
   "sports"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/hal-a2.jpg"
 },
 {
  "id": "april",
  "name": "April Apricot",
  "collection": "core",
  "fruit": "apricot",
  "emoji": "🟠",
  "hue": 32,
  "tag": "Makeup artist",
  "role": "Makeup artist to the stars",
  "gender": "female",
  "voiceStyle": "chatty, dramatic",
  "storyTypes": [
   "social",
   "service"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/april-a1.jpg"
 },
 {
  "id": "archie",
  "name": "Archie Apricot",
  "collection": "core",
  "fruit": "apricot",
  "emoji": "🟠",
  "hue": 32,
  "tag": "Dad",
  "role": "Retired army dad, very strict",
  "gender": "male",
  "voiceStyle": "barking",
  "storyTypes": [
   "family",
   "wedding"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/archie-a1.jpg"
 },
 {
  "id": "aria",
  "name": "Aria Apricot",
  "collection": "core",
  "fruit": "apricot",
  "emoji": "🟠",
  "hue": 32,
  "tag": "Pilot",
  "role": "Airline pilot, cool under pressure",
  "gender": "female",
  "voiceStyle": "cool, calm",
  "storyTypes": [
   "service",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/aria-a2.jpg"
 },
 {
  "id": "arlo",
  "name": "Arlo Apricot",
  "collection": "core",
  "fruit": "apricot",
  "emoji": "🟠",
  "hue": 32,
  "tag": "Intern",
  "role": "Overconfident intern",
  "gender": "male",
  "voiceStyle": "eager, loud",
  "storyTypes": [
   "office"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/arlo-a1.jpg"
 },
 {
  "id": "lily",
  "name": "Lily Lychee",
  "collection": "core",
  "fruit": "lychee",
  "emoji": "🔴",
  "hue": 355,
  "tag": "Dentist",
  "role": "Dentist with a scary smile",
  "gender": "female",
  "voiceStyle": "bubbly, scary",
  "storyTypes": [
   "hospital"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/lily-a1.jpg"
 },
 {
  "id": "lee",
  "name": "Lee Lychee",
  "collection": "core",
  "fruit": "lychee",
  "emoji": "🔴",
  "hue": 355,
  "tag": "Casino owner",
  "role": "Casino owner, calm and dangerous",
  "gender": "male",
  "voiceStyle": "calm, dangerous",
  "storyTypes": [
   "money",
   "crime"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/lee-a1.jpg"
 },
 {
  "id": "lulu",
  "name": "Lulu Lychee",
  "collection": "core",
  "fruit": "lychee",
  "emoji": "🔴",
  "hue": 355,
  "tag": "Spa owner",
  "role": "Spa owner who runs a gossip ring",
  "gender": "female",
  "voiceStyle": "silky",
  "storyTypes": [
   "service",
   "neighbors"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/lulu-a1.jpg"
 },
 {
  "id": "brad",
  "name": "Brad Bramble",
  "collection": "core",
  "fruit": "blackberry",
  "emoji": "🫐",
  "hue": 280,
  "tag": "Husband",
  "role": "Firefighter husband with a second phone",
  "gender": "male",
  "voiceStyle": "deep, calm",
  "storyTypes": [
   "marriage",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/brad-a2.jpg"
 },
 {
  "id": "bianca",
  "name": "Bianca Bramble",
  "collection": "core",
  "fruit": "blackberry",
  "emoji": "🫐",
  "hue": 280,
  "tag": "Ex-wife",
  "role": "Ex-wife who won everything",
  "gender": "female",
  "voiceStyle": "icy, amused",
  "storyTypes": [
   "marriage",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/bianca-a2.jpg"
 },
 {
  "id": "mac",
  "name": "Mac Black",
  "collection": "core",
  "fruit": "blackberry",
  "emoji": "🫐",
  "hue": 280,
  "tag": "Mob boss",
  "role": "Old-school mob boss",
  "gender": "male",
  "voiceStyle": "whispery, cold",
  "storyTypes": [
   "crime"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/mac-a2.jpg"
 },
 {
  "id": "dolly",
  "name": "Dolly Bramble",
  "collection": "core",
  "fruit": "blackberry",
  "emoji": "🫐",
  "hue": 280,
  "tag": "Cleaner",
  "role": "Night cleaner who reads every desk",
  "gender": "female",
  "voiceStyle": "gruff, sly",
  "storyTypes": [
   "office"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/dolly-a2.jpg"
 },
 {
  "id": "harriet",
  "name": "Harriet Honeydew",
  "collection": "core",
  "fruit": "honeydew",
  "emoji": "🍈",
  "hue": 110,
  "tag": "Librarian",
  "role": "Librarian who shushes everyone",
  "gender": "female",
  "voiceStyle": "whispery, strict",
  "storyTypes": [
   "school"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/harriet-a1.jpg"
 },
 {
  "id": "hugh",
  "name": "Hugh Honeydew",
  "collection": "core",
  "fruit": "honeydew",
  "emoji": "🍈",
  "hue": 110,
  "tag": "Nurse",
  "role": "Male nurse everyone flirts with",
  "gender": "male",
  "voiceStyle": "gentle",
  "storyTypes": [
   "hospital",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/hugh-a1.jpg"
 },
 {
  "id": "dewey",
  "name": "Dewey Honeydew",
  "collection": "core",
  "fruit": "honeydew",
  "emoji": "🍈",
  "hue": 110,
  "tag": "Weatherman",
  "role": "TV weatherman, always wrong",
  "gender": "male",
  "voiceStyle": "cheesy",
  "storyTypes": [
   "social"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/dewey-a1.jpg"
 },
 {
  "id": "duke",
  "name": "Duke Durian",
  "collection": "core",
  "fruit": "durian",
  "emoji": "🟢",
  "hue": 70,
  "tag": "Loan shark",
  "role": "Loan shark nobody can stand",
  "gender": "male",
  "voiceStyle": "menacing, slow",
  "storyTypes": [
   "crime",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/duke-a1.jpg"
 },
 {
  "id": "doris",
  "name": "Doris Durian",
  "collection": "core",
  "fruit": "durian",
  "emoji": "🟢",
  "hue": 70,
  "tag": "Mother-in-law",
  "role": "Mother-in-law who moved in",
  "gender": "female",
  "voiceStyle": "shrill",
  "storyTypes": [
   "family",
   "marriage"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/doris-a1.jpg"
 },
 {
  "id": "dusty",
  "name": "Dusty Durian",
  "collection": "core",
  "fruit": "durian",
  "emoji": "🟢",
  "hue": 70,
  "tag": "Husband",
  "role": "Lazy husband who hides the bills",
  "gender": "male",
  "voiceStyle": "lazy, loud",
  "storyTypes": [
   "marriage",
   "money"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/core/dusty-a1.jpg"
 },
 {
  "id": "lemz",
  "name": "Lemz",
  "collection": "uk-roadman",
  "fruit": "lemon",
  "emoji": "🍋",
  "hue": 55,
  "tag": "Crew leader",
  "role": "Mandem leader, always has a plan",
  "gender": "male",
  "voiceStyle": "calm London accent, laid-back UK slang, never raises his voice",
  "storyTypes": [
   "dating",
   "neighbors"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/lemz-a1.jpg"
 },
 {
  "id": "zesty",
  "name": "Zesty",
  "collection": "uk-roadman",
  "fruit": "lime",
  "emoji": "🍋‍🟩",
  "hue": 90,
  "tag": "Youngest",
  "role": "Youngest in the crew, trying too hard",
  "gender": "male",
  "voiceStyle": "fast, eager London accent, overuses the newest slang",
  "storyTypes": [
   "neighbors",
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/zesty-a1.jpg"
 },
 {
  "id": "tomzy",
  "name": "Tomzy",
  "collection": "uk-roadman",
  "fruit": "tomato",
  "emoji": "🍅",
  "hue": 5,
  "tag": "Mandem",
  "role": "Crew joker, turns everything into a bit",
  "gender": "male",
  "voiceStyle": "loud, playful London accent, lots of UK slang and laughing",
  "storyTypes": [
   "dating",
   "neighbors"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/tomzy-a1.jpg"
 },
 {
  "id": "razz",
  "name": "Razz",
  "collection": "uk-roadman",
  "fruit": "raspberry",
  "emoji": "🔴",
  "hue": 340,
  "tag": "Rival",
  "role": "Rival from the other estate",
  "gender": "male",
  "voiceStyle": "low, cool London accent, short sharp slang",
  "storyTypes": [
   "neighbors",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/razz-a1.jpg"
 },
 {
  "id": "pinesy",
  "name": "Pinesy",
  "collection": "uk-roadman",
  "fruit": "pineapple",
  "emoji": "🍍",
  "hue": 42,
  "tag": "Rapper",
  "role": "Aspiring rapper, one freestyle from fame",
  "gender": "male",
  "voiceStyle": "rhythmic London accent, confident UK slang, talks in bars",
  "storyTypes": [
   "social",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/pinesy-a1.jpg"
 },
 {
  "id": "pez",
  "name": "Pez",
  "collection": "uk-roadman",
  "fruit": "pear",
  "emoji": "🍐",
  "hue": 75,
  "tag": "Producer",
  "role": "Bedroom music producer, hears beats everywhere",
  "gender": "male",
  "voiceStyle": "soft, chilled London accent, relaxed slang",
  "storyTypes": [
   "social"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/pez-a1.jpg"
 },
 {
  "id": "wedge",
  "name": "Wedge",
  "collection": "uk-roadman",
  "fruit": "watermelon",
  "emoji": "🍉",
  "hue": 140,
  "tag": "Delivery rider",
  "role": "Delivery rider who sees every drama",
  "gender": "male",
  "voiceStyle": "cheerful, quick London accent, friendly slang",
  "storyTypes": [
   "service",
   "neighbors"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/wedge-a1.jpg"
 },
 {
  "id": "blu",
  "name": "Blu",
  "collection": "uk-roadman",
  "fruit": "blueberry",
  "emoji": "🫐",
  "hue": 235,
  "tag": "Reseller",
  "role": "Trainer reseller, always has a deal",
  "gender": "male",
  "voiceStyle": "smooth, persuasive London accent, salesy slang",
  "storyTypes": [
   "money",
   "service"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/blu-a1.jpg"
 },
 {
  "id": "grapz",
  "name": "Grapz",
  "collection": "uk-roadman",
  "fruit": "grape",
  "emoji": "🍇",
  "hue": 275,
  "tag": "Mandem",
  "role": "The quiet one who notices everything",
  "gender": "male",
  "voiceStyle": "quiet, deep London accent, few words",
  "storyTypes": [
   "neighbors",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/grapz-a1.jpg"
 },
 {
  "id": "chez",
  "name": "Chez",
  "collection": "uk-roadman",
  "fruit": "cherry",
  "emoji": "🍒",
  "hue": 350,
  "tag": "Chicken shop",
  "role": "Chicken shop worker who knows everyone's order",
  "gender": "male",
  "voiceStyle": "friendly, chatty London accent, easy slang",
  "storyTypes": [
   "service",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/chez-a1.jpg"
 },
 {
  "id": "uncle",
  "name": "Uncle Tay",
  "collection": "uk-roadman",
  "fruit": "tomato",
  "emoji": "🍅",
  "hue": 5,
  "tag": "Shop owner",
  "role": "Uncle who runs the chicken shop, knows every secret",
  "gender": "male",
  "voiceStyle": "warm, booming older London accent, gentle slang",
  "storyTypes": [
   "service",
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/uncle-a1.jpg"
 },
 {
  "id": "trims",
  "name": "Trims",
  "collection": "uk-roadman",
  "fruit": "pear",
  "emoji": "🍐",
  "hue": 75,
  "tag": "Barber",
  "role": "Barber who gives the best advice on the ends",
  "gender": "male",
  "voiceStyle": "calm, wise London accent, measured slang",
  "storyTypes": [
   "service",
   "family"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/trims-a1.jpg"
 },
 {
  "id": "rasco",
  "name": "Rasco",
  "collection": "uk-roadman",
  "fruit": "raspberry",
  "emoji": "🔴",
  "hue": 340,
  "tag": "Mandem",
  "role": "Gym-obsessed crew member, protein at all times",
  "gender": "male",
  "voiceStyle": "loud, hype London accent, gym slang",
  "storyTypes": [
   "sports",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/rasco-a1.jpg"
 },
 {
  "id": "jito",
  "name": "Jito",
  "collection": "uk-roadman",
  "fruit": "lime",
  "emoji": "🍋‍🟩",
  "hue": 90,
  "tag": "Mandem",
  "role": "Always late, always has an excuse",
  "gender": "male",
  "voiceStyle": "easygoing London accent, apologetic slang",
  "storyTypes": [
   "dating",
   "neighbors"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/jito-a1.jpg"
 },
 {
  "id": "roxy",
  "name": "Roxy",
  "collection": "uk-roadman",
  "fruit": "cherry",
  "emoji": "🍒",
  "hue": 350,
  "tag": "Girlfriend",
  "role": "Roadgyal who runs the relationship",
  "gender": "female",
  "voiceStyle": "confident, quick London accent, sharp UK slang",
  "storyTypes": [
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/roxy-a1.jpg"
 },
 {
  "id": "tia",
  "name": "Tia",
  "collection": "uk-roadman",
  "fruit": "grape",
  "emoji": "🍇",
  "hue": 275,
  "tag": "Ex",
  "role": "The ex who still shows up everywhere",
  "gender": "female",
  "voiceStyle": "cool, dry London accent, cutting slang",
  "storyTypes": [
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/tia-a1.jpg"
 },
 {
  "id": "chatty",
  "name": "Chatty",
  "collection": "uk-roadman",
  "fruit": "watermelon",
  "emoji": "🍉",
  "hue": 140,
  "tag": "Estate gossip",
  "role": "Estate gossip who hears it first",
  "gender": "female",
  "voiceStyle": "fast, gleeful London accent, gossipy slang",
  "storyTypes": [
   "neighbors"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/chatty-a1.jpg"
 },
 {
  "id": "nessa",
  "name": "Nessa",
  "collection": "uk-roadman",
  "fruit": "lime",
  "emoji": "🍋‍🟩",
  "hue": 90,
  "tag": "Mum",
  "role": "Young mum who takes no nonsense",
  "gender": "female",
  "voiceStyle": "firm, warm London accent, no-nonsense slang",
  "storyTypes": [
   "family",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/nessa-a1.jpg"
 },
 {
  "id": "auntie",
  "name": "Auntie Rubes",
  "collection": "uk-roadman",
  "fruit": "raspberry",
  "emoji": "🔴",
  "hue": 340,
  "tag": "Shop owner",
  "role": "Auntie who runs the corner shop, sees everything",
  "gender": "female",
  "voiceStyle": "warm, sharp older London accent, motherly slang",
  "storyTypes": [
   "service",
   "neighbors"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/auntie-a1.jpg"
 },
 {
  "id": "tizzy",
  "name": "Tizzy",
  "collection": "uk-roadman",
  "fruit": "tomato",
  "emoji": "🍅",
  "hue": 5,
  "tag": "Roadgyal",
  "role": "Roadgyal in the crew, always filming",
  "gender": "female",
  "voiceStyle": "bubbly, loud London accent, fast UK slang",
  "storyTypes": [
   "social",
   "dating"
  ],
  "refImageUrl": "https://ilpiwoxubnevmxxikyvx.supabase.co/storage/v1/object/public/public-assets/fruit-characters/uk-roadman/tizzy-a1.jpg"
 }
];
