// Builds supabase/functions/_shared/stickman/thumbnailPack.gen.ts from
// docs/thumbnails/thumbnail-pack.md (the source of truth): the shared
// THUMBNAIL HEADER and COMPOSITION/NO-TEXT blocks (verbatim) and all 50
// examples {n, niche, archetype, headline, background, subject, prompt}.
// Fails loudly if a prompt doesn't have the pack's exact header/composition.
//   node scripts/buildThumbnailPack.mjs
import fs from "node:fs";

const md = fs.readFileSync("docs/thumbnails/thumbnail-pack.md", "utf8").replace(/\r\n/g, "\n");
const examples = [];
let niche = null;
const lines = md.split("\n");
for (let i = 0; i < lines.length; i++) {
  const h2 = lines[i].match(/^## (.+)$/);
  if (h2 && !/spec for the generator/i.test(h2[1])) niche = h2[1].trim();
  const h3 = lines[i].match(/^### (\d+)\. (.+?)\s+·\s+([A-Z]+)\s*$/);
  if (!h3) continue;
  const fence = lines.indexOf("```", i);
  const prompt = lines[fence + 1].trim();
  const headline = (md.slice(md.indexOf(lines[i])).match(/\*\*Headline \(drawn by code\):\*\* `([^`]+)`/) ?? [])[1];
  const m = prompt.match(/^(.*?) BACKGROUND: (.*?) SUBJECT: (.*?) COMPOSITION: (.*)$/);
  if (!m) throw new Error(`#${h3[1]}: no BACKGROUND/SUBJECT/COMPOSITION split`);
  examples.push({ n: Number(h3[1]), niche, archetype: h3[3], headline, header: m[1], background: m[2], subject: m[3], composition: `COMPOSITION: ${m[4]}`, prompt });
}
if (examples.length !== 50) throw new Error(`expected 50 examples, found ${examples.length}`);
const header = examples[0].header, composition = examples[0].composition;
for (const e of examples) {
  if (e.header !== header) throw new Error(`#${e.n}: a different THUMBNAIL HEADER`);
  if (e.composition !== composition) throw new Error(`#${e.n}: a different COMPOSITION block`);
}
const out = `// GENERATED by scripts/buildThumbnailPack.mjs from docs/thumbnails/thumbnail-pack.md — do not edit by hand.
export const PACK_HEADER = ${JSON.stringify(header)};
export const PACK_COMPOSITION = ${JSON.stringify(composition)};
export type PackExample = { n: number; niche: string; archetype: string; headline: string; background: string; subject: string; prompt: string };
export const PACK: PackExample[] = ${JSON.stringify(examples.map(({ header: _h, composition: _c, ...e }) => e), null, 1)};
`;
fs.writeFileSync("supabase/functions/_shared/stickman/thumbnailPack.gen.ts", out);
console.log(`${examples.length} examples, ${new Set(examples.map((e) => e.niche)).size} niches`);
