// generateVoiceSamples.mjs — Phase 6b, run ONCE (paid: ~235 ElevenLabs chars
// per voice). For every voice in src/lib/voiceCatalog.js without a sample:
// synthesize the fixed VOICE_SAMPLE_TEXT with the real narration settings
// (via the service-only elevenlabs-quota-check { sample }), save it to
// public/voices/samples/<voiceId>.mp3, keep the alignment as a fixture, and
// measure the voice's pace (words / spoken span) into src/lib/voiceSamplePace.ts.
// Existing samples are never regenerated (free re-run; pace is re-measured
// from the saved alignment fixtures).
//   node --env-file=.env.local scripts/generateVoiceSamples.mjs
import fs from "node:fs";
import path from "node:path";
import { VOICE_CATALOG, VOICE_SAMPLE_TEXT } from "../src/lib/voiceCatalog.js";

const SAMPLES = "public/voices/samples";
const FIXTURES = "tests/fixtures/stickman/audio/voice-samples";
fs.mkdirSync(SAMPLES, { recursive: true });
fs.mkdirSync(FIXTURES, { recursive: true });

// Word timings from the character alignment (same rule as the narration mapper: whitespace splits words).
function wordsFromAlignment(al) {
  const words = [];
  let cur = null;
  al.characters.forEach((ch, i) => {
    if (/\s/.test(ch)) { if (cur) { words.push(cur); cur = null; } return; }
    if (!cur) cur = { start: al.character_start_times_seconds[i], end: al.character_end_times_seconds[i] };
    else cur.end = al.character_end_times_seconds[i];
  });
  if (cur) words.push(cur);
  return words;
}
const wpm = (w) => { const span = w[w.length - 1].end - w[0].start; return Math.round((w.length / (span / 60)) * 10) / 10; };

let credits = 0;
const pace = {};
const failed = [];
for (const voice of VOICE_CATALOG) {
  const mp3 = path.join(SAMPLES, `${voice.voiceId}.mp3`);
  const fx = path.join(FIXTURES, `${voice.voiceId}.json`);
  if (!fs.existsSync(fx)) {
    const r = await fetch(`${process.env.SUPABASE_URL}/functions/v1/elevenlabs-quota-check`, {
      method: "POST", headers: { Authorization: `Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({ sample: { voiceId: voice.voiceId, voiceModel: voice.voiceModel, text: VOICE_SAMPLE_TEXT } }),
    });
    const j = await r.json().catch(() => ({}));
    if (!j.ok) { failed.push({ name: voice.name, voiceId: voice.voiceId, error: j.error ?? r.status }); console.log("FAIL", voice.name, j.error ?? r.status); continue; }
    fs.writeFileSync(mp3, Buffer.from(j.audioBase64, "base64"));
    fs.writeFileSync(fx, JSON.stringify({ voiceId: voice.voiceId, name: voice.name, voiceModel: voice.voiceModel, text: VOICE_SAMPLE_TEXT, durationSeconds: j.durationSeconds, characterCost: j.characterCost, alignment: j.alignment }));
    credits += Number(j.characterCost ?? 0);
  }
  const saved = JSON.parse(fs.readFileSync(fx, "utf8"));
  const w = wordsFromAlignment(saved.alignment);
  pace[voice.voiceId] = { name: voice.name, wpm: wpm(w), words: w.length, durationSeconds: Math.round(saved.durationSeconds * 10) / 10, characterCost: saved.characterCost ?? null };
  console.log(voice.name.padEnd(16), String(pace[voice.voiceId].wpm).padStart(6), "wpm", `${pace[voice.voiceId].durationSeconds}s`, `cost ${saved.characterCost}`);
}

const rows = Object.entries(pace).map(([id, p]) => `  ${JSON.stringify(id)}: { name: ${JSON.stringify(p.name)}, wpm: ${p.wpm}, words: ${p.words}, durationSeconds: ${p.durationSeconds} },`).join("\n");
fs.writeFileSync("src/lib/voiceSamplePace.ts", `// voiceSamplePace.ts — GENERATED by scripts/generateVoiceSamples.mjs (Phase 6b).
// Measured pace of each library voice: words / spoken span of its fixed
// ${VOICE_SAMPLE_TEXT.split(/\\s+/).length}-word sample (eleven_flash_v2_5, speed 1.0, the real narration
// settings). Alignments: tests/fixtures/stickman/audio/voice-samples/.
export const VOICE_SAMPLE_PACE: Record<string, { name: string; wpm: number; words: number; durationSeconds: number }> = {
${rows}
};
`);
console.log(JSON.stringify({ voices: Object.keys(pace).length, newCredits: credits, failed }));
