// "Length slider + niche thumbnail re-roll" pass, Part B — replaces all 25
// niche preview images with real YouTube-thumbnail-style versions (bold
// yellow headline + extreme reaction/head-to-head), same slugs/paths as
// before so no code changes are needed. Cost confirmed with the user:
// 25 x $0.04945 = $1.23625. Prompts used verbatim, never rewritten/shortened.
import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local", quiet: true });
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = process.env.SUPABASE_URL;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const admin = createClient(SUPABASE_URL, SERVICE_KEY);
const TEST_EMAIL = "upwardlift6@gmail.com";

async function mintSession() {
  const { data, error } = await admin.auth.admin.generateLink({ type: "magiclink", email: TEST_EMAIL });
  if (error) throw error;
  const anon = createClient(SUPABASE_URL, process.env.SUPABASE_ANON_KEY ?? SERVICE_KEY);
  const { data: verify, error: verifyError } = await anon.auth.verifyOtp({ token_hash: data.properties.hashed_token, type: "email" });
  if (verifyError) throw verifyError;
  return verify.session.access_token;
}
async function callFn(name, accessToken, body) {
  const res = await fetch(`${SUPABASE_URL}/functions/v1/${name}`, {
    method: "POST",
    headers: { Authorization: `Bearer ${accessToken}`, apikey: process.env.SUPABASE_ANON_KEY ?? SERVICE_KEY, "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const json = await res.json().catch(() => ({}));
  return { status: res.status, ok: res.ok, json };
}

const NICHES = [
  { id: "ancient_humans_prehistory", headline: "NO FIRE?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat deep navy night with a flat pale-blue snowy ground band and a few white snowflake dots. SUBJECT: a hunter-gatherer stickman with a deep warm brown skin tone on the circle head, short tightly coiled black hair as a flat black cap of small bumps, wearing a tan hide wrap with a jagged hem, hugging himself and shivering violently with small motion lines and frost marks on his head, eyes huge, eyebrows angled up in terror, teeth-chattering zigzag mouth. Beside him, a small pile of cold sticks with no flame. Behind him in the dark, three pairs of glowing yellow eyes. HEADLINE TEXT: exactly "NO FIRE?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "dark_brutal_history", headline: "SURVIVE THIS?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat deep maroon-red with a flat dark-grey silhouette of leaning medieval houses along the bottom. SUBJECT: a medieval peasant stickman with a light peach skin tone on the circle head, messy brown hair as a flat tuft, wearing a patched flat brown tunic, leaning back in horror with both mitten hands raised, eyes huge, mouth a wide screaming oval. Towering behind him, a plague doctor stickman in a long flat black cloak, a flat black wide-brimmed hat and a long pale-grey bird-beak mask with two round glass-lens eyes, holding a small lantern with a flat yellow glow. HEADLINE TEXT: exactly "SURVIVE THIS?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "daily_life_past_eras", headline: "ROMAN TOILETS?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat warm terracotta with a flat cream stone wall. SUBJECT: a long flat cream stone bench with a row of round holes, three Roman stickmen sitting side by side on it in flat white and pale-blue tunics with light olive skin tones on their circle heads and short curly black hair. The middle one stares straight at the viewer with huge embarrassed eyes, eyebrows raised high, cheeks with small flat pink blush marks, mouth a tight wavy line; the two neighbors chat cheerfully. A sponge on a stick leans against the bench. HEADLINE TEXT: exactly "ROMAN TOILETS?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "military_logistics_history", headline: "30 KM A DAY?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat bright ochre sky over a flat grey straight stone road. SUBJECT: a Roman legionary stickman with a light tan skin tone on the circle head, a flat bronze helmet with a red crest, a flat red tunic and grey segmented armor, bent almost double under a comically huge flat brown pack piled with pots, tools and a shovel on a wooden pole, sweat drops flying, tongue out, eyes huge and exhausted, eyebrows sagging. Small flat footprint marks trail behind him to the horizon. HEADLINE TEXT: exactly "30 KM A DAY?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "ancient_medicine_science", headline: "SKULL SURGERY?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat warm orange-terracotta. SUBJECT: a patient stickman with a light peach skin tone on the circle head, short brown hair, wearing a flat brown tunic, sitting stiffly with eyes huge and pupils tiny, eyebrows shot up, mouth a wide horrified oval, sweat drops flying. Behind him, a calm ancient healer stickman with a medium brown skin tone on the circle head, a flat white beard and a flat dark-green robe, holding a small flint tool near the top of the patient's head with a calm smile. No blood, no wounds. HEADLINE TEXT: exactly "SKULL SURGERY?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "timeline_history", headline: "ALL OF HISTORY?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: a flat sky split into hard-edged vertical bands from dusty orange on the left to teal on the right. SUBJECT: a stickman with a light-medium tan skin tone on the circle head, short dark-brown hair, wearing a flat mustard-yellow shirt and navy trousers, sprinting left to right in panic with speed lines behind him, eyes huge, mouth a wide open oval, along a flat sand-colored path. Along the path behind and ahead of him: a tiny cave with a campfire, a pyramid, a castle, and a modern city skyline. HEADLINE TEXT: exactly "ALL OF HISTORY?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "myth_vs_reality", headline: "FAKE HORNS?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: split by a jagged vertical crack: flat glowing gold on the left, flat plain grey on the right. LEFT: a Viking stickman with a light peach skin tone on the circle head, a big flat orange braided beard, a flat grey helmet with two big white curved horns and a flat red tunic, posing heroically — the horns crossed out by a bold flat red X. RIGHT: the same Viking stickman with a light peach skin tone on the circle head, a big flat orange braided beard and a flat red tunic, wearing a plain round grey helmet with no horns, staring at the viewer with huge confused eyes, one eyebrow high, mouth a crooked line. HEADLINE TEXT: exactly "FAKE HORNS?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "psychology_human_behavior", headline: "OVERTHINKING?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat deep violet. SUBJECT: a modern stickman with a medium brown skin tone on the circle head, black hair in a low ponytail, wearing a flat teal hoodie, clutching both sides of the head with mitten hands, eyes huge with spiral pupils, eyebrows angled up in panic, mouth a jagged wavy line. Exploding upward from the head, a huge tangled flat lavender scribble cloud of looping lines that fills the space behind her. HEADLINE TEXT: exactly "OVERTHINKING?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "the_body_explained", headline: "WHY DO WE YAWN?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat bright mint green. SUBJECT: a modern stickman with a light-medium beige skin tone on the circle head, messy dark-brown hair, wearing a flat heather-grey t-shirt, in the middle of an enormous yawn — mouth a giant open oval taking up half the head, eyes squeezed shut as curved lines, arms stretched up. Beside him, two smaller stickmen with different skin tones in flat blue and orange shirts start yawning too, with small motion lines. HEADLINE TEXT: exactly "WHY DO WE YAWN?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "sleep_health_habits", headline: "3 AM AGAIN?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat dark navy night bedroom with a window showing a flat pale-yellow crescent moon. SUBJECT: a modern stickman with a light-medium beige skin tone on the circle head, messy dark-brown hair, wearing a flat grey t-shirt, sitting bolt upright in bed under a flat lavender blanket, eyes enormous and wide awake with tiny pupils, flat dark-grey bags under the eyes, eyebrows sagging, mouth a flat miserable line. On the bedside table, a black alarm clock whose red display reads exactly "3:00" (the only text allowed besides the headline). HEADLINE TEXT: exactly "3 AM AGAIN?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline and the "3:00" on the clock. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "evolution_quirks", headline: "WHY BACK PAIN?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat warm lilac. SUBJECT: an evolution-march lineup walking left to right: a flat brown ape, an early human stickman with a tan hide wrap, an upright hunter-gatherer stickman with a spear, and at the front, largest, a modern stickman with a light-medium beige skin tone on the circle head, a flat teal hoodie and jeans, hunched over a glowing phone, one mitten hand clutching his lower back with bold red pain-burst lines, eyes huge, mouth a grimacing zigzag. HEADLINE TEXT: exactly "WHY BACK PAIN?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "why_dont_we_eat_x", headline: "EAT A LION?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat soft sage green. SUBJECT: a modern stickman with a light-medium tan skin tone on the circle head, short dark-brown hair and a flat white shirt, sitting at a small dinner table holding a knife and fork, leaning back in horror with huge eyes, eyebrows shot up, mouth a wide oval. Across the table sits a big flat tawny-gold lion with a dark-brown jagged mane and a white napkin tied around its neck, grinning slyly and holding its own fork. HEADLINE TEXT: exactly "EAT A LION?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "animal_behavior_predator_prey", headline: "WHO WINS?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: split down the middle: flat golden-yellow on the left, flat olive green on the right, with a small flat white spark burst at the center line. LEFT: a big flat tawny-gold lion with a dark-brown jagged mane, crouched and snarling, eyes narrowed. RIGHT: a big flat zebra with bold black stripes, rearing up with one hoof raised, eyes wide and defiant. They face each other across the center line. HEADLINE TEXT: exactly "WHO WINS?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "survival_scenarios", headline: "30 DAYS HERE?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat bright turquoise ocean under a flat pale-yellow sky. SUBJECT: a tiny round sand island with one flat green palm tree, and on it a modern stickman with a light-medium beige skin tone on the circle head, messy dark-brown hair, wearing a torn flat grey t-shirt with a jagged hem and navy shorts, waving both arms frantically, eyes huge, mouth a screaming oval, sweat drops flying. Four dark-grey shark fins circle the island. HEADLINE TEXT: exactly "30 DAYS HERE?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "extinct_animals", headline: "MAMMOTHS RETURN?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat pale-blue sky over a flat grey city street with simple flat building shapes. SUBJECT: a giant flat woolly mammoth with shaggy brown fur shapes and long curved white tusks stomping down the street, towering over a tiny modern stickman with a light-medium tan skin tone on the circle head, short dark-brown hair and a flat red jacket, who drops his coffee cup and stares up with huge eyes and a wide screaming mouth. HEADLINE TEXT: exactly "MAMMOTHS RETURN?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "space_cosmic_scale", headline: "HOW BIG?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat deep indigo space with small white dot stars. SUBJECT: a tiny stickman astronaut in a flat white spacesuit with a round pale-blue visor showing huge shocked eyes and a small open mouth, floating in the lower right with arms flung wide. Filling most of the frame behind him, an enormous flat orange-and-yellow star curving off the edge, dwarfing him completely, with a tiny flat blue Earth dot beside it for scale. HEADLINE TEXT: exactly "HOW BIG?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "what_if_hypotheticals", headline: "NO MOON?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat deep teal night sky with small white dot stars. SUBJECT: a modern stickman with a medium brown skin tone on the circle head, short black curly hair, wearing a flat orange shirt and navy trousers, standing on a beach pointing up at an empty circle drawn as a thin white dashed outline where the Moon should be, eyes huge, eyebrows shot up, mouth a wide oval. Behind him, a big flat dark-blue wave curls strangely. HEADLINE TEXT: exactly "NO MOON?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "mysteries_unexplained", headline: "WHO BUILT THIS?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat misty dark teal with flat dark-green pine tree shapes. SUBJECT: a stickman investigator with a light-medium beige skin tone on the circle head, short dark-brown hair, wearing a flat mustard-yellow raincoat, holding a flashlight and leaning back in amazement, eyes huge, mouth a wide oval. In front of him, a ring of tall flat grey standing stones with a flat pale-green glow at its center and one pale-green beam shooting into the sky. HEADLINE TEXT: exactly "WHO BUILT THIS?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "everyday_science", headline: "WHY ICE FLOATS?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat bright sky blue. SUBJECT: a modern stickman with a light-medium beige skin tone on the circle head, messy dark-brown hair, wearing a flat heather-grey t-shirt, holding up a big clear glass of water with a flat white ice cube floating at the top, squinting at it through a large magnifying glass, one eye enormous behind the lens, eyebrows scrunched in confusion, mouth a sideways squiggle. HEADLINE TEXT: exactly "WHY ICE FLOATS?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "money_psychology_economics", headline: "WHY YOU'RE BROKE?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat soft mint green. SUBJECT: a modern stickman with a light-medium tan skin tone on the circle head, short dark-brown hair, wearing a flat navy blazer over a white shirt, holding a wide-open flat brown wallet that is completely empty except for a small flat grey moth fluttering out, while flat gold coins with little white wings fly away above him. His eyes are huge, eyebrows angled up in despair, mouth a wobbly downward curve. HEADLINE TEXT: exactly "WHY YOU'RE BROKE?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "technology_attention_economy", headline: "ADDICTED?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat deep teal. SUBJECT: a modern stickman with a medium brown skin tone on the circle head, short black hair, wearing a flat purple hoodie, standing hypnotized in front of a giant flat black smartphone taller than himself with a glowing pale-blue screen of simple rounded app shapes; his eyes are huge with spiral pupils and his mouth hangs open. A fishing line with a silver hook comes out of the screen and hooks his hoodie, pulling him forward. HEADLINE TEXT: exactly "ADDICTED?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "how_systems_work", headline: "SO FAST?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat pale yellow. SUBJECT: a modern stickman with a light-medium beige skin tone on the circle head, messy dark-brown hair, wearing a flat grey t-shirt, standing at his front door holding a brown cardboard package, eyes huge, mouth a wide amazed oval. Behind him, a looping flat grey conveyor belt, a flat red delivery truck, and a small flat white plane all race along with bold speed lines, showing the package's journey. HEADLINE TEXT: exactly "SO FAST?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "countries_cultures", headline: "ILLEGAL HERE?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat soft sky blue with a flat pale-green city park ground. SUBJECT: a tourist stickman with a light-medium tan skin tone on the circle head, short dark-brown hair, a flat mustard-yellow t-shirt, khaki shorts and a red backpack, frozen mid-chew with a flat pink gum bubble, eyes huge, eyebrows shot up. Beside him, a police officer stickman with a medium brown skin tone on the circle head, a flat navy uniform and cap, pointing at the gum and blowing a whistle, with small motion lines. HEADLINE TEXT: exactly "ILLEGAL HERE?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "jobs_careers", headline: "PAID FOR THIS?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: flat murky swamp green with flat darker-green reeds. SUBJECT: a medieval worker stickman with a light peach skin tone on the circle head, messy brown hair and a patched flat brown tunic, standing knee-deep in flat brown swamp water with several flat dark leeches stuck to his bare stick legs, holding a small bucket, eyes huge and disgusted, eyebrows angled down, mouth a grimacing zigzag, one mitten hand pinching his nose. HEADLINE TEXT: exactly "PAID FOR THIS?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
  { id: "you_vs_x", headline: "COULD YOU WIN?", prompt: `YouTube thumbnail in flat-color 2D doodle/stickman explainer style, 16:9. Bold, simple, and very high contrast so it reads instantly at 120 pixels wide. Uniform thick clean black outlines; flat solid color fills only; no shading, no gradients, no texture, no 3D. Characters are stickmen: a perfect circle head with no neck, thin black stick limbs, rounded black mitten hands and feet, clothing as simple flat color shapes. Thumbnail faces are exaggerated for impact: large round white eyes with black pupils, thick strongly angled eyebrows, and a big expressive mouth — the emotion must be extreme and readable at tiny size. BACKGROUND: split down the middle: flat modern teal on the left, flat warm terracotta on the right, with a flat yellow spark burst at the center line. LEFT: a modern stickman with a light-medium beige skin tone on the circle head, messy dark-brown hair, wearing a flat grey hoodie and jeans, raising his fists nervously, eyes huge, eyebrows angled up, sweat drop flying. RIGHT: a Roman legionary stickman with a light olive skin tone on the circle head, a flat bronze helmet with a red crest, a flat red tunic, grey armor and a big rectangular flat red shield, glaring confidently with eyebrows angled down and a smug grin. HEADLINE TEXT: exactly "COULD YOU WIN?" in heavy bold rounded all-caps letters, bright yellow fill with a thick black outline, filling the top third of the frame and spanning about 80% of its width. The subject fills the bottom two-thirds, large and centered. No other text, letters, numbers, logos, or watermarks anywhere except the headline. Keep the background flat with 2–3 tones and no clutter; no boxes, panels, frames, or blank rectangles anywhere.` },
];

async function main() {
  console.log(`Niches to generate: ${NICHES.length}`);
  const accessToken = await mintSession();
  console.log("Session minted. Generating...\n");

  const results = [];
  let totalCost = 0;
  for (const item of NICHES) {
    process.stdout.write(`  ${item.id} ("${item.headline}") ... `);
    // Distinct storage key (v2 suffix) so we never touch the live v1 asset
    // until the user approves the contact sheet.
    const rerollId = `${item.id}__v2thumb`;
    const res = await callFn("generate-style-preview-asset", accessToken, { styleId: rerollId, prompt: item.prompt });
    if (!res.ok) {
      console.log("FAILED", res.status, JSON.stringify(res.json));
      results.push({ id: item.id, headline: item.headline, ok: false, error: res.json });
      continue;
    }
    console.log("OK");
    totalCost += res.json.costUSD;
    results.push({ id: item.id, headline: item.headline, rerollId, ok: true, publicUrl: res.json.publicUrl, costUSD: res.json.costUSD });
  }

  console.log("\n=== SUMMARY ===");
  const failed = results.filter((r) => !r.ok);
  console.log(`${results.filter((r) => r.ok).length}/${NICHES.length} succeeded. Total cost: $${totalCost.toFixed(4)}`);
  if (failed.length) console.log("FAILED:", JSON.stringify(failed, null, 2));
}
main().catch((e) => { console.error("GENERATION FAILED:", e); process.exit(1); });
