-- Allow a user to remove only the newest episode in one of their 30 Days
-- Series. Deletion never changes the user's credit balance: the original
-- reservation and any retry charges remain spent. Because generation and
-- billing rows cascade away with the deleted episode, retain a private audit
-- record of the amounts that existed at deletion time.

CREATE TABLE IF NOT EXISTS public.thirty_days_series_episode_deletion_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  series_id uuid NOT NULL,
  episode_id uuid NOT NULL,
  generation_id uuid,
  episode_number integer NOT NULL CHECK (episode_number > 0),
  start_day integer NOT NULL CHECK (start_day > 0),
  end_day integer NOT NULL CHECK (end_day >= start_day),
  reserved_credits integer NOT NULL DEFAULT 0 CHECK (reserved_credits >= 0),
  already_refunded_credits integer NOT NULL DEFAULT 0 CHECK (already_refunded_credits >= 0),
  retry_credits integer NOT NULL DEFAULT 0 CHECK (retry_credits >= 0),
  deletion_refund_credits integer NOT NULL DEFAULT 0 CHECK (deletion_refund_credits = 0),
  deleted_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (episode_id)
);

ALTER TABLE public.thirty_days_series_episode_deletion_ledger ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS thirty_days_series_episode_deletions_user_time
  ON public.thirty_days_series_episode_deletion_ledger (user_id, deleted_at DESC);
REVOKE ALL ON TABLE public.thirty_days_series_episode_deletion_ledger
  FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.delete_latest_thirty_days_series_episode(
  p_episode_id uuid
)
RETURNS public.thirty_days_series
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_series_id uuid;
  v_series public.thirty_days_series;
  v_episode public.thirty_days_series_episodes;
  v_latest public.thirty_days_series_episodes;
  v_previous public.thirty_days_series_episodes;
  v_generation public.thirty_days_generations;
  v_base_references jsonb := '[]'::jsonb;
  -- NULL means there is no completed episode to restore from. Initializing
  -- this to [] made COALESCE prefer the empty array over setup references
  -- when the first/latest episode was deleted.
  v_restore_references jsonb;
  v_story_state jsonb;
  v_remaining record;
  v_retry_credits integer := 0;
  v_previous_day integer := 0;
  v_previous_number integer := 0;
  v_previous_tease text;
  v_previous_cover text;
BEGIN
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;

  -- Lock the target episode before its series, matching the completion RPC.
  -- A completion finishing at the same moment as deletion therefore cannot
  -- deadlock with this rollback.
  SELECT * INTO v_episode
  FROM public.thirty_days_series_episodes
  WHERE id = p_episode_id AND user_id = v_user_id
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'EPISODE_NOT_FOUND'; END IF;
  v_series_id := v_episode.series_id;

  SELECT * INTO v_series
  FROM public.thirty_days_series
  WHERE id = v_series_id AND user_id = v_user_id
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'SERIES_NOT_FOUND'; END IF;

  SELECT * INTO v_latest
  FROM public.thirty_days_series_episodes
  WHERE series_id = v_series.id
  ORDER BY episode_number DESC, created_at DESC
  LIMIT 1
  FOR UPDATE;
  IF NOT FOUND OR v_latest.id <> v_episode.id THEN
    RAISE EXCEPTION 'DELETE_ONLY_LATEST_EPISODE';
  END IF;

  IF v_episode.generation_id IS NOT NULL THEN
    SELECT * INTO v_generation
    FROM public.thirty_days_generations
    WHERE id = v_episode.generation_id AND user_id = v_user_id
    FOR UPDATE;

    SELECT COALESCE(sum(credits), 0) INTO v_retry_credits
    FROM public.thirty_days_series_retry_ledger
    WHERE generation_id = v_episode.generation_id;

    -- Stop queued/local worker work before removing the reservation graph.
    -- Provider work already submitted may still finish remotely, but it can
    -- no longer update or advance a deleted Series episode.
    UPDATE public.jobs
    SET status = 'canceled', updated_at = now()
    WHERE id IN (
      SELECT job_id
      FROM public.thirty_days_generation_assets
      WHERE generation_id = v_episode.generation_id AND job_id IS NOT NULL
    )
      AND user_id = v_user_id
      AND status IN ('queued', 'running', 'processing');
  END IF;

  INSERT INTO public.thirty_days_series_episode_deletion_ledger (
    user_id, series_id, episode_id, generation_id, episode_number,
    start_day, end_day, reserved_credits, already_refunded_credits,
    retry_credits, deletion_refund_credits
  ) VALUES (
    v_user_id, v_series.id, v_episode.id, v_episode.generation_id,
    v_episode.episode_number, v_episode.start_day, v_episode.end_day,
    COALESCE(v_generation.reserved_credits, 0),
    COALESCE(v_generation.refunded_credits, 0), v_retry_credits, 0
  );

  -- Delete the generation explicitly first. Its assets and reservation /
  -- retry ledgers cascade; deleting it sets episode.generation_id to NULL.
  -- No profile balance update occurs anywhere in this function.
  IF v_episode.generation_id IS NOT NULL THEN
    DELETE FROM public.thirty_days_generations
    WHERE id = v_episode.generation_id AND user_id = v_user_id;
  END IF;
  DELETE FROM public.thirty_days_series_episodes
  WHERE id = v_episode.id AND user_id = v_user_id;

  SELECT COALESCE(visual_references, '[]'::jsonb)
  INTO v_base_references
  FROM public.thirty_days_generations
  WHERE id = v_series.setup_generation_id;
  v_base_references := COALESCE(v_base_references, '[]'::jsonb);

  -- Recreate the setup-time entity state from the original persistent
  -- references, then replay every remaining verified episode in order.
  -- This avoids trusting a client-supplied rollback snapshot and works for
  -- episodes created before this deletion feature existed.
  WITH raw_entities AS (
    SELECT
      COALESCE(NULLIF(ref->>'entityId', ''), NULLIF(ref->>'id', '')) AS entity_id,
      ref,
      ordinality
    FROM jsonb_array_elements(v_base_references) WITH ORDINALITY AS refs(ref, ordinality)
    WHERE COALESCE(ref->>'role', '') <> 'core_cast_style'
      AND COALESCE(ref->>'role', '') NOT LIKE 'environment%'
  ), unique_entities AS (
    SELECT DISTINCT ON (entity_id) entity_id, ref
    FROM raw_entities
    WHERE entity_id IS NOT NULL
    ORDER BY entity_id, ordinality
  )
  SELECT jsonb_build_object(
    'entities', COALESCE(jsonb_agg(jsonb_build_object(
      'entityId', entity_id,
      'entityType', COALESCE(NULLIF(ref->>'role', ''), 'character'),
      'canonicalType', COALESCE(NULLIF(ref->>'label', ''), entity_id),
      'displayName', COALESCE(NULLIF(ref->>'label', ''), entity_id),
      'introducedDay', COALESCE((ref->>'activeFromDay')::integer, 1),
      'status', 'active',
      'currentForm', COALESCE(NULLIF(ref->>'label', ''), entity_id),
      'visualIdentity', COALESCE(ref->>'visualLock', ref->>'prompt', ''),
      'referenceId', ref->>'id',
      'abilities', '[]'::jsonb,
      'relationships', '{}'::jsonb
    ) ORDER BY entity_id), '[]'::jsonb),
    'relationships', '{}'::jsonb,
    'inventory', '[]'::jsonb,
    'abilities', '[]'::jsonb,
    'mysteries', '{}'::jsonb,
    'events', '[]'::jsonb,
    'consumedBeatIds', '[]'::jsonb
  ) INTO v_story_state
  FROM unique_entities;

  v_story_state := COALESCE(v_story_state, jsonb_build_object(
    'entities', '[]'::jsonb, 'relationships', '{}'::jsonb,
    'inventory', '[]'::jsonb, 'abilities', '[]'::jsonb,
    'mysteries', '{}'::jsonb, 'events', '[]'::jsonb,
    'consumedBeatIds', '[]'::jsonb
  ));

  FOR v_remaining IN
    SELECT state_delta, verified_episode
    FROM public.thirty_days_series_episodes
    WHERE series_id = v_series.id AND status = 'completed'
    ORDER BY episode_number
  LOOP
    v_story_state := public.merge_thirty_days_story_state(
      v_story_state,
      COALESCE(v_remaining.state_delta, '{}'::jsonb),
      COALESCE(v_remaining.verified_episode, '{}'::jsonb)
    );
  END LOOP;

  SELECT * INTO v_previous
  FROM public.thirty_days_series_episodes
  WHERE series_id = v_series.id AND status = 'completed'
  ORDER BY episode_number DESC
  LIMIT 1;

  IF FOUND THEN
    v_previous_day := v_previous.end_day;
    v_previous_number := v_previous.episode_number;
    v_previous_tease := COALESCE(
      NULLIF(v_previous.next_episode_tease, ''),
      v_previous.verified_episode->>'nextEpisodeSetup'
    );
    v_previous_cover := v_previous.thumbnail_url;
    SELECT COALESCE(visual_references, v_base_references)
    INTO v_restore_references
    FROM public.thirty_days_generations
    WHERE id = v_previous.generation_id;
  END IF;

  v_restore_references := COALESCE(v_restore_references, v_base_references, '[]'::jsonb);
  v_previous_cover := COALESCE(
    NULLIF(v_previous_cover, ''),
    NULLIF(v_base_references->0->>'imageUrl', '')
  );

  UPDATE public.thirty_days_series
  SET current_day = v_previous_day,
      current_episode = v_previous_number,
      status = 'ready',
      verified_story_state = v_story_state,
      current_story_state = v_story_state,
      entity_registry = COALESCE(v_story_state->'entities', '[]'::jsonb),
      reference_library = v_restore_references,
      pacing_state = (COALESCE(pacing_state, '{}'::jsonb) - 'consumedBeatIds' - 'lastCompletedDay')
        || jsonb_build_object(
          'consumedBeatIds', COALESCE(v_story_state->'consumedBeatIds', '[]'::jsonb),
          'lastCompletedDay', v_previous_day
        ),
      next_episode_tease = v_previous_tease,
      cover_url = v_previous_cover,
      last_active_at = now()
  WHERE id = v_series.id
  RETURNING * INTO v_series;

  RETURN v_series;
END;
$$;

REVOKE ALL ON FUNCTION public.delete_latest_thirty_days_series_episode(uuid)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.delete_latest_thirty_days_series_episode(uuid)
  TO authenticated;
