-- 2026-09-19 "make the narration contract mandatory" V1 fix, Task 1's
-- explicit "Generate preflight" ask: "Before a user can pay for Generate
-- Episode: run a deterministic preflight confirming that every planned
-- beat can compile into a valid render plan. Especially: GRAPHIC beats
-- must compile successfully... No credit charge until preflight succeeds."
--
-- advance-long-form-visual-plan's stageFinalizing (this session's separate
-- fix) now refuses to let a NEWLY generated plan reach 'ready' if any
-- PROGRAMMATIC_GRAPHIC beat lacks a bound narrationClaimId -- the exact
-- precondition start-long-form-scene-generation's own fail-closed
-- GRAPHIC_REPLAN_REQUIRED gate requires to compile a graphic beat at all.
-- This is the matching DEFENSE-IN-DEPTH check at the charge boundary
-- itself: a plan generated by a worker version that predates that fix (or
-- any other path that produced a 'ready' plan without this guarantee)
-- must still never be charged for. Read-only against the plan's own
-- already-persisted visual_plan JSON -- no new compile simulation, no
-- provider call, just the same fact stageFinalizing already checks made
-- visible at the one remaining place real money changes hands.
-- Retire the unchecked entry point: old callers must upgrade, never bypass preflight.
create or replace function public.charge_long_form_episode_generation(p_project_id uuid, p_user_id uuid, p_tier text)
returns jsonb language plpgsql security definer set search_path = '' as $$
begin
  raise exception 'GENERATE_PREFLIGHT_FAILED_SERVER_UPGRADE_REQUIRED';
end $$;
revoke all on function public.charge_long_form_episode_generation(uuid,uuid,text) from public, anon, authenticated;

create or replace function public.charge_long_form_episode_generation(p_project_id uuid, p_user_id uuid, p_tier text, p_preflight jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  proj public.long_form_projects; world public.long_form_visual_world_versions; plan public.long_form_visual_plan_versions;
  existing public.long_form_episode_generation_charges; stale public.long_form_episode_generation_charges;
  price jsonb; total int; balance int; idem_key text; new_id uuid; unclaimed_graphics int;
begin
  select * into proj from public.long_form_projects where id = p_project_id for update;
  if not found then raise exception 'PROJECT_NOT_FOUND'; end if;
  if proj.user_id is distinct from p_user_id then raise exception 'FORBIDDEN'; end if;
  if p_tier not in ('v2', 'v3', 'v4') then raise exception 'INVALID_TIER'; end if;

  select * into existing from public.long_form_episode_generation_charges
    where project_id = p_project_id and status = 'charged' and visual_plan_version_id = proj.current_visual_plan_version_id;
  if found then
    return jsonb_build_object('charged', true, 'alreadyCharged', true, 'creditsCharged', existing.credits_charged, 'breakdown', existing.cost_breakdown, 'tier', existing.tier);
  end if;

  select * into stale from public.long_form_episode_generation_charges where project_id = p_project_id and status = 'charged';

  if proj.current_visual_world_version_id is null or proj.current_visual_plan_version_id is null then raise exception 'NOT_READY'; end if;
  select * into world from public.long_form_visual_world_versions where id = proj.current_visual_world_version_id;
  if world.status is distinct from 'ready' then raise exception 'VISUAL_WORLD_NOT_READY'; end if;

  -- Generate preflight: every PROGRAMMATIC_GRAPHIC beat must carry a bound
  -- narrationClaimId, or start-long-form-scene-generation's own fail-closed
  -- gate would throw GRAPHIC_REPLAN_REQUIRED for it after the user already
  -- paid. Zero graphic beats is not a failure (nothing to check).
  select * into plan from public.long_form_visual_plan_versions where id = proj.current_visual_plan_version_id;
  if plan.status is distinct from 'ready'
    or p_preflight->>'planId' is distinct from plan.id::text
    or p_preflight->>'worldId' is distinct from world.id::text
    or p_preflight->'plan' is distinct from plan.visual_plan
    or p_preflight->>'contractId' is distinct from plan.visual_plan->>'narrationContractVersionId'
    or not exists (select 1 from public.long_form_narration_contract_versions c
      where c.id::text = p_preflight->>'contractId' and c.project_id = proj.id
        and c.script_version_id = proj.current_script_version_id and c.status = 'ready' and jsonb_array_length(c.claims) > 0)
    or coalesce(jsonb_array_length(plan.visual_plan->'visualBeats'), 0) = 0
    or (select jsonb_agg(b->>'id' order by b->>'id') from jsonb_array_elements(plan.visual_plan->'visualBeats') b)
       is distinct from (select jsonb_agg(b order by b) from jsonb_array_elements_text(p_preflight->'beatIds') b)
  then raise exception 'GENERATE_PREFLIGHT_FAILED_PLAN_CHANGED_OR_UNCOMPILED'; end if;
  select count(*) into unclaimed_graphics
    from jsonb_array_elements(coalesce(plan.visual_plan->'visualBeats', '[]'::jsonb)) b
    where b->>'renderMethod' = 'PROGRAMMATIC_GRAPHIC' and (b->>'narrationClaimId') is null;
  if unclaimed_graphics > 0 then raise exception 'GENERATE_PREFLIGHT_FAILED_GRAPHIC_BEATS_NOT_COMPILABLE'; end if;

  price := public.estimate_long_form_episode_credits(p_project_id, p_tier);
  total := (price->>'totalCredits')::int;

  select credit_balance into balance from public.profiles where id = p_user_id for update;
  if balance is null or balance < total then raise exception 'INSUFFICIENT_CREDITS'; end if;

  if stale.id is not null then
    update public.long_form_episode_generation_charges set status = 'superseded', superseded_at = now() where id = stale.id;
  end if;

  update public.profiles set credit_balance = credit_balance - total, credits_spent_today = coalesce(credits_spent_today, 0) + total where id = p_user_id;

  idem_key := p_project_id::text || ':episode_generation:' || proj.current_visual_plan_version_id::text;
  insert into public.long_form_episode_generation_charges(project_id, visual_world_version_id, visual_plan_version_id, user_id, tier, credits_charged, cost_breakdown, idempotency_key, rebuild_of_charge_id)
  values (p_project_id, proj.current_visual_world_version_id, proj.current_visual_plan_version_id, p_user_id, p_tier, total, price, idem_key, stale.id)
  on conflict (idempotency_key) do nothing
  returning id into new_id;
  if new_id is null then select id into new_id from public.long_form_episode_generation_charges where idempotency_key = idem_key; end if;

  if stale.id is not null then
    update public.long_form_episode_generation_charges set superseded_by_charge_id = new_id where id = stale.id and superseded_by_charge_id is null;
  end if;

  update public.long_form_projects set scene_generation_tier = p_tier, current_scene_generation_status = 'charged', active_generation_charge_id = new_id, updated_at = now() where id = p_project_id;

  return jsonb_build_object('charged', true, 'alreadyCharged', false, 'creditsCharged', total, 'breakdown', price->'breakdown', 'tier', p_tier);
end $$;
revoke all on function public.charge_long_form_episode_generation(uuid,uuid,text,jsonb) from public, anon, authenticated;
grant execute on function public.charge_long_form_episode_generation(uuid,uuid,text,jsonb) to service_role;
