-- Harden 30 Days billing around one server-priced reservation. Every visual
-- asset has an immutable cost and may only be dispatched by a worker after it
-- has been attached to that reservation. Settlement reads trusted job rows;
-- the client never supplies prices, completion counts, or refund amounts.

ALTER TABLE public.thirty_days_generations
  ADD COLUMN IF NOT EXISTS service_credits_charged integer NOT NULL DEFAULT 0
  CHECK (service_credits_charged >= 0);

CREATE TABLE public.thirty_days_generation_assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  generation_id uuid NOT NULL REFERENCES public.thirty_days_generations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  asset_key text NOT NULL,
  asset_type text NOT NULL
    CHECK (asset_type IN ('reference_image', 'scene_image', 'scene_video')),
  reference_id text,
  scene_index integer CHECK (scene_index BETWEEN 0 AND 6),
  dependency_keys text[] NOT NULL DEFAULT '{}'::text[],
  tool_key text NOT NULL,
  cost_credits integer NOT NULL CHECK (cost_credits > 0),
  job_id uuid REFERENCES public.jobs(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'planned'
    CHECK (status IN ('planned', 'queued', 'running', 'retrying', 'succeeded', 'failed', 'canceled')),
  qa_status text NOT NULL DEFAULT 'pending'
    CHECK (qa_status IN ('pending', 'passed', 'failed', 'unavailable')),
  qa_attempts integer NOT NULL DEFAULT 0 CHECK (qa_attempts BETWEEN 0 AND 2),
  result_url text,
  error text,
  refunded_credits integer NOT NULL DEFAULT 0 CHECK (refunded_credits >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (generation_id, asset_key)
);

CREATE UNIQUE INDEX thirty_days_assets_current_job
  ON public.thirty_days_generation_assets (job_id)
  WHERE job_id IS NOT NULL;
CREATE INDEX thirty_days_assets_generation_status
  ON public.thirty_days_generation_assets (generation_id, status);
CREATE INDEX thirty_days_assets_user_created
  ON public.thirty_days_generation_assets (user_id, created_at DESC);

ALTER TABLE public.thirty_days_generation_assets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users read own 30 Days assets"
  ON public.thirty_days_generation_assets FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);

DROP TRIGGER IF EXISTS set_thirty_days_asset_updated_at ON public.thirty_days_generation_assets;
CREATE TRIGGER set_thirty_days_asset_updated_at
  BEFORE UPDATE ON public.thirty_days_generation_assets
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.thirty_days_credit_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  generation_id uuid NOT NULL REFERENCES public.thirty_days_generations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  operation text NOT NULL CHECK (operation IN ('reserve', 'refund')),
  credits integer NOT NULL CHECK (credits >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (generation_id, operation)
);

ALTER TABLE public.thirty_days_credit_ledger ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users read own 30 Days credit ledger"
  ON public.thirty_days_credit_ledger FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);

-- Remove the old client-priced entry point. Its p_cost argument was only
-- clamped, so an authenticated caller could reserve an entire generation at
-- the floor price. The replacement is service-role-only and derives every
-- cost from a fixed tier table in this function.
REVOKE ALL ON FUNCTION public.begin_thirty_days_generation(text, boolean, text, jsonb, integer)
  FROM PUBLIC, authenticated;

CREATE OR REPLACE FUNCTION public.begin_thirty_days_generation(
  p_user_id uuid,
  p_universe text,
  p_ai_idea_mode boolean,
  p_premise text,
  p_plan jsonb,
  p_quality_tier text
)
RETURNS public.thirty_days_generations
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_generation public.thirty_days_generations;
  v_plan_code text;
  v_quality text := COALESCE(NULLIF(trim(p_quality_tier), ''), 'thirtydays-v2');
  v_image_tool text;
  v_image_cost integer;
  v_reference_cost integer := 5;
  v_video_cost integer := 6;
  v_voice_limit integer;
  v_service_cost integer;
  v_total_cost integer;
  v_reference_count integer := COALESCE(jsonb_array_length(p_plan->'visualReferences'), 0);
  v_scene_count integer := COALESCE(jsonb_array_length(p_plan->'scenes'), 0);
  v_ref jsonb;
  v_scene jsonb;
  v_reference_id text;
  v_scene_index integer;
  v_dependencies text[];
BEGIN
  IF p_user_id IS NULL THEN RAISE EXCEPTION 'USER_REQUIRED'; END IF;
  IF length(trim(COALESCE(p_universe, ''))) < 2 THEN RAISE EXCEPTION 'UNIVERSE_REQUIRED'; END IF;
  IF v_reference_count NOT BETWEEN 4 AND 6 THEN RAISE EXCEPTION 'INVALID_REFERENCE_COUNT'; END IF;
  IF v_scene_count <> 7 THEN RAISE EXCEPTION 'INVALID_SCENE_COUNT'; END IF;

  SELECT lower(COALESCE(plan_code, 'free'))
  INTO v_plan_code
  FROM public.profiles
  WHERE id = p_user_id;

  IF NOT FOUND THEN RAISE EXCEPTION 'PROFILE_NOT_FOUND'; END IF;

  CASE v_quality
    WHEN 'thirtydays-v2' THEN
      v_image_tool := 'image:thirtydays1k';
      v_image_cost := 5;
      IF v_plan_code NOT IN ('starter', 'affiliate', 'pro', 'generative') THEN
        RAISE EXCEPTION 'PLAN_UPGRADE_REQUIRED';
      END IF;
    WHEN 'thirtydays-v3' THEN
      v_image_tool := 'image:thirtydays2k';
      v_image_cost := 7;
      IF v_plan_code NOT IN ('pro', 'generative') THEN RAISE EXCEPTION 'PLAN_UPGRADE_REQUIRED'; END IF;
    WHEN 'thirtydays-v4' THEN
      v_image_tool := 'image:thirtydays4k';
      v_image_cost := 10;
      IF v_plan_code <> 'generative' THEN RAISE EXCEPTION 'PLAN_UPGRADE_REQUIRED'; END IF;
    ELSE
      RAISE EXCEPTION 'INVALID_QUALITY_TIER';
  END CASE;

  v_voice_limit := CASE v_plan_code
    WHEN 'generative' THEN 5
    WHEN 'pro' THEN 3
    ELSE 2
  END;
  -- Same paid service bundle as Cooking Matic: 12 credits for script/
  -- preview services plus 3 credits for every included generated voice take.
  v_service_cost := 12 + v_voice_limit * 3;
  v_total_cost := v_reference_count * v_reference_cost
    + 7 * v_image_cost
    + 7 * v_video_cost
    + v_service_cost;

  -- Validate stable, unique reference ids and all scene references before
  -- deducting anything.
  IF (
    SELECT count(DISTINCT value->>'id')
    FROM jsonb_array_elements(p_plan->'visualReferences') AS refs(value)
  ) <> v_reference_count OR EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_plan->'visualReferences') AS refs(value)
    WHERE length(trim(COALESCE(value->>'id', ''))) = 0
  ) THEN
    RAISE EXCEPTION 'INVALID_REFERENCE_IDS';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_plan->'scenes') AS scenes(scene),
         jsonb_array_elements_text(COALESCE(scene->'referenceIds', '[]'::jsonb)) AS assigned(reference_id)
    WHERE NOT EXISTS (
      SELECT 1
      FROM jsonb_array_elements(p_plan->'visualReferences') AS refs(reference)
      WHERE reference->>'id' = assigned.reference_id
    )
  ) THEN
    RAISE EXCEPTION 'INVALID_SCENE_REFERENCE';
  END IF;

  PERFORM public.deduct_credits(p_user_id, v_total_cost);

  INSERT INTO public.thirty_days_generations (
    user_id, universe, ai_idea_mode, premise, title, hook, camera_mode,
    world_bible, visual_references, scenes, quality_tier, status,
    reserved_credits, reservation_status, voice_generation_limit,
    service_credits_charged
  ) VALUES (
    p_user_id,
    trim(p_universe),
    COALESCE(p_ai_idea_mode, true),
    NULLIF(trim(COALESCE(p_premise, '')), ''),
    NULLIF(trim(COALESCE(p_plan->>'title', '')), ''),
    NULLIF(trim(COALESCE(p_plan->>'hook', '')), ''),
    CASE WHEN p_plan->>'cameraMode' = 'first_person' THEN 'first_person' ELSE 'third_person' END,
    COALESCE(p_plan->'worldBible', '{}'::jsonb),
    p_plan->'visualReferences',
    p_plan->'scenes',
    v_quality,
    'references',
    v_total_cost,
    'reserved',
    v_voice_limit,
    v_service_cost
  ) RETURNING * INTO v_generation;

  FOR v_ref IN SELECT value FROM jsonb_array_elements(p_plan->'visualReferences') LOOP
    v_reference_id := v_ref->>'id';
    INSERT INTO public.thirty_days_generation_assets (
      generation_id, user_id, asset_key, asset_type, reference_id, tool_key, cost_credits
    ) VALUES (
      v_generation.id, p_user_id, 'reference:' || v_reference_id,
      'reference_image', v_reference_id, 'image:thirtydays1k', v_reference_cost
    );
  END LOOP;

  FOR v_scene IN SELECT value FROM jsonb_array_elements(p_plan->'scenes') LOOP
    v_scene_index := (v_scene->>'index')::integer;
    IF v_scene_index NOT BETWEEN 0 AND 6 THEN RAISE EXCEPTION 'INVALID_SCENE_INDEX'; END IF;

    SELECT COALESCE(array_agg('reference:' || value ORDER BY ordinality), '{}'::text[])
    INTO v_dependencies
    FROM jsonb_array_elements_text(COALESCE(v_scene->'referenceIds', '[]'::jsonb))
      WITH ORDINALITY AS ids(value, ordinality);

    IF cardinality(v_dependencies) NOT BETWEEN 1 AND 3 THEN RAISE EXCEPTION 'INVALID_SCENE_REFERENCES'; END IF;

    INSERT INTO public.thirty_days_generation_assets (
      generation_id, user_id, asset_key, asset_type, scene_index,
      dependency_keys, tool_key, cost_credits
    ) VALUES (
      v_generation.id, p_user_id, 'scene:' || v_scene_index || ':image',
      'scene_image', v_scene_index, v_dependencies, v_image_tool, v_image_cost
    );

    INSERT INTO public.thirty_days_generation_assets (
      generation_id, user_id, asset_key, asset_type, scene_index,
      dependency_keys, tool_key, cost_credits
    ) VALUES (
      v_generation.id, p_user_id, 'scene:' || v_scene_index || ':video',
      'scene_video', v_scene_index, ARRAY['scene:' || v_scene_index || ':image'],
      'video:seedance15pro', v_video_cost
    );
  END LOOP;

  INSERT INTO public.thirty_days_credit_ledger (generation_id, user_id, operation, credits)
  VALUES (v_generation.id, p_user_id, 'reserve', v_total_cost);

  RETURN v_generation;
END;
$$;

-- Called only by job-worker. It proves that a zero-charge job belongs to an
-- active reservation and atomically makes that job the asset's current try.
CREATE OR REPLACE FUNCTION public.authorize_thirty_days_asset_job(
  p_generation_id uuid,
  p_asset_key text,
  p_job_id uuid
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_asset public.thirty_days_generation_assets;
  v_job public.jobs;
  v_reservation_status text;
BEGIN
  SELECT * INTO v_asset
  FROM public.thirty_days_generation_assets
  WHERE generation_id = p_generation_id AND asset_key = p_asset_key
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'ASSET_RESERVATION_NOT_FOUND'; END IF;

  SELECT reservation_status INTO v_reservation_status
  FROM public.thirty_days_generations
  WHERE id = p_generation_id;
  IF v_reservation_status <> 'reserved' THEN RAISE EXCEPTION 'RESERVATION_NOT_ACTIVE'; END IF;

  SELECT * INTO v_job FROM public.jobs WHERE id = p_job_id;
  IF NOT FOUND
    OR v_job.user_id <> v_asset.user_id
    OR v_job.tool_key <> v_asset.tool_key
    OR COALESCE(v_job.charge_credits, -1) <> 0
    OR (v_asset.asset_type = 'scene_video' AND v_job.type <> 'video')
    OR (v_asset.asset_type <> 'scene_video' AND v_job.type <> 'image')
    OR v_job.input #>> '{billing_reservation,template}' <> 'thirty-days'
    OR v_job.input #>> '{billing_reservation,generationId}' <> p_generation_id::text
    OR v_job.input #>> '{billing_reservation,assetKey}' <> p_asset_key
  THEN
    RAISE EXCEPTION 'INVALID_RESERVED_JOB';
  END IF;

  IF v_asset.status = 'succeeded' AND v_asset.qa_status IN ('passed', 'unavailable') THEN
    RAISE EXCEPTION 'ASSET_ALREADY_COMPLETED';
  END IF;

  UPDATE public.thirty_days_generation_assets
  SET job_id = p_job_id,
      status = CASE v_job.status
        WHEN 'succeeded' THEN 'succeeded'
        WHEN 'failed' THEN 'failed'
        WHEN 'canceled' THEN 'canceled'
        WHEN 'queued' THEN 'queued'
        ELSE 'running'
      END,
      result_url = v_job.result_url,
      error = v_job.error
  WHERE id = v_asset.id;

  RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_thirty_days_generation_assets(p_generation_id uuid)
RETURNS SETOF public.thirty_days_generation_assets
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_owner uuid;
BEGIN
  SELECT user_id INTO v_owner
  FROM public.thirty_days_generations
  WHERE id = p_generation_id;
  IF NOT FOUND OR auth.uid() IS NULL OR v_owner <> auth.uid() THEN
    RAISE EXCEPTION 'CREATION_ACCESS_DENIED';
  END IF;

  UPDATE public.thirty_days_generation_assets AS asset
  SET status = CASE job.status
        WHEN 'succeeded' THEN 'succeeded'
        WHEN 'failed' THEN 'failed'
        WHEN 'canceled' THEN 'canceled'
        WHEN 'queued' THEN 'queued'
        ELSE 'running'
      END,
      result_url = job.result_url,
      error = job.error
  FROM public.jobs AS job
  WHERE asset.generation_id = p_generation_id
    AND asset.job_id = job.id
    AND NOT (asset.qa_status = 'failed' AND asset.qa_attempts >= 2);

  RETURN QUERY
  SELECT * FROM public.thirty_days_generation_assets
  WHERE generation_id = p_generation_id
  ORDER BY asset_key;
END;
$$;

CREATE OR REPLACE FUNCTION public.record_thirty_days_scene_qa(
  p_generation_id uuid,
  p_scene_index integer,
  p_job_id uuid,
  p_usable boolean,
  p_reason text
)
RETURNS public.thirty_days_generation_assets
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_asset public.thirty_days_generation_assets;
  v_attempts integer;
BEGIN
  SELECT asset.* INTO v_asset
  FROM public.thirty_days_generation_assets AS asset
  WHERE asset.generation_id = p_generation_id
    AND asset.asset_key = 'scene:' || p_scene_index || ':image'
    AND asset.user_id = auth.uid()
  FOR UPDATE;

  IF NOT FOUND OR auth.uid() IS NULL THEN RAISE EXCEPTION 'CREATION_ACCESS_DENIED'; END IF;
  IF v_asset.job_id <> p_job_id THEN RAISE EXCEPTION 'QA_JOB_MISMATCH'; END IF;
  IF v_asset.status <> 'succeeded' THEN RAISE EXCEPTION 'QA_JOB_NOT_SUCCEEDED'; END IF;

  v_attempts := LEAST(2, v_asset.qa_attempts + 1);
  UPDATE public.thirty_days_generation_assets
  SET qa_attempts = v_attempts,
      qa_status = CASE
        WHEN p_usable AND p_reason = 'qa_unavailable' THEN 'unavailable'
        WHEN p_usable THEN 'passed'
        ELSE 'failed'
      END,
      status = CASE WHEN p_usable THEN 'succeeded' WHEN v_attempts < 2 THEN 'retrying' ELSE 'failed' END,
      error = CASE WHEN p_usable THEN NULL ELSE left(COALESCE(NULLIF(p_reason, ''), 'qa_failed'), 500) END
  WHERE id = v_asset.id
  RETURNING * INTO v_asset;

  RETURN v_asset;
END;
$$;

-- Replace the count-based settlement API with a parameter-free, trusted
-- derivation from assets and jobs. Dependency failures cascade (reference ->
-- scene image -> scene video), so unstarted dependent work is refunded too.
REVOKE ALL ON FUNCTION public.settle_thirty_days_generation(uuid, integer, integer)
  FROM PUBLIC, authenticated;

CREATE OR REPLACE FUNCTION public.settle_thirty_days_generation(p_generation_id uuid)
RETURNS public.thirty_days_generations
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_generation public.thirty_days_generations;
  v_changed integer := 1;
  v_nonterminal integer;
  v_succeeded integer;
  v_total integer;
  v_refund integer;
BEGIN
  SELECT * INTO v_generation
  FROM public.thirty_days_generations
  WHERE id = p_generation_id AND user_id = auth.uid()
  FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'GENERATION_NOT_FOUND'; END IF;
  IF v_generation.reservation_status <> 'reserved' THEN RETURN v_generation; END IF;

  UPDATE public.thirty_days_generation_assets AS asset
  SET status = CASE job.status
        WHEN 'succeeded' THEN 'succeeded'
        WHEN 'failed' THEN 'failed'
        WHEN 'canceled' THEN 'canceled'
        WHEN 'queued' THEN 'queued'
        ELSE 'running'
      END,
      result_url = job.result_url,
      error = job.error
  FROM public.jobs AS job
  WHERE asset.generation_id = p_generation_id
    AND asset.job_id = job.id
    AND NOT (asset.qa_status = 'failed' AND asset.qa_attempts >= 2);

  WHILE v_changed > 0 LOOP
    UPDATE public.thirty_days_generation_assets AS dependent
    SET status = 'failed', error = 'dependency_failed'
    WHERE dependent.generation_id = p_generation_id
      AND dependent.status IN ('planned', 'queued', 'retrying')
      AND EXISTS (
        SELECT 1
        FROM public.thirty_days_generation_assets AS dependency
        WHERE dependency.generation_id = dependent.generation_id
          AND dependency.asset_key = ANY(dependent.dependency_keys)
          AND dependency.status IN ('failed', 'canceled')
      );
    GET DIAGNOSTICS v_changed = ROW_COUNT;
  END LOOP;

  SELECT count(*),
         count(*) FILTER (WHERE status = 'succeeded'),
         count(*) FILTER (WHERE status NOT IN ('succeeded', 'failed', 'canceled')),
         COALESCE(sum(cost_credits) FILTER (WHERE status IN ('failed', 'canceled')), 0)
  INTO v_total, v_succeeded, v_nonterminal, v_refund
  FROM public.thirty_days_generation_assets
  WHERE generation_id = p_generation_id;

  IF v_total = 0 THEN RAISE EXCEPTION 'GENERATION_ASSETS_MISSING'; END IF;
  IF v_nonterminal > 0 THEN RAISE EXCEPTION 'ASSETS_NOT_TERMINAL'; END IF;

  IF v_refund > 0 THEN
    INSERT INTO public.thirty_days_credit_ledger (generation_id, user_id, operation, credits)
    VALUES (p_generation_id, v_generation.user_id, 'refund', v_refund);

    UPDATE public.profiles
    SET credit_balance = credit_balance + v_refund,
        credits_spent_today = GREATEST(0, COALESCE(credits_spent_today, 0) - v_refund)
    WHERE id = v_generation.user_id;

    UPDATE public.thirty_days_generation_assets
    SET refunded_credits = cost_credits
    WHERE generation_id = p_generation_id AND status IN ('failed', 'canceled');
  END IF;

  UPDATE public.thirty_days_generations
  SET refunded_credits = v_refund,
      -- The script/voice service bundle is consumed by this creation and is
      -- intentionally not a refundable visual asset.
      reservation_status = CASE WHEN v_refund = v_generation.reserved_credits THEN 'refunded' ELSE 'settled' END,
      status = CASE WHEN v_succeeded = v_total THEN 'voiceover' WHEN v_succeeded = 0 THEN 'failed' ELSE 'partial' END
  WHERE id = p_generation_id
  RETURNING * INTO v_generation;

  RETURN v_generation;
END;
$$;

-- Existing RLS still enforces ownership, while column privileges keep all
-- billing, plan, ownership, and rate-limit state server-only.
REVOKE ALL ON TABLE public.thirty_days_generations FROM anon, authenticated;
GRANT SELECT ON TABLE public.thirty_days_generations TO authenticated;
GRANT UPDATE (
  title, hook, camera_mode, world_bible, visual_references, scenes, status,
  narration_script, narration_take, full_video_url, error, updated_at
) ON TABLE public.thirty_days_generations TO authenticated;

REVOKE ALL ON TABLE public.thirty_days_generation_assets FROM anon, authenticated;
GRANT SELECT ON TABLE public.thirty_days_generation_assets TO authenticated;
REVOKE ALL ON TABLE public.thirty_days_credit_ledger FROM anon, authenticated;
GRANT SELECT ON TABLE public.thirty_days_credit_ledger TO authenticated;

REVOKE ALL ON FUNCTION public.begin_thirty_days_generation(uuid, text, boolean, text, jsonb, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.authorize_thirty_days_asset_job(uuid, text, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sync_thirty_days_generation_assets(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.record_thirty_days_scene_qa(uuid, integer, uuid, boolean, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.settle_thirty_days_generation(uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.begin_thirty_days_generation(uuid, text, boolean, text, jsonb, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.authorize_thirty_days_asset_job(uuid, text, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_thirty_days_generation_assets(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_thirty_days_scene_qa(uuid, integer, uuid, boolean, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.settle_thirty_days_generation(uuid) TO authenticated;
