-- Persistent, progressively billed 30 Days Series mode. Single-video rows
-- remain unchanged. A series owns one setup generation (persistent visual
-- references) and each episode owns a normal reservation-backed generation,
-- so the existing jobs/asset authorization/refund machinery is reused.

CREATE TABLE public.thirty_days_series (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  universe text NOT NULL,
  premise text NOT NULL,
  visual_style text NOT NULL DEFAULT 'auto'
    CHECK (visual_style IN ('auto', 'cinematic_3d', 'anime_accurate', 'realistic', 'dark_cinematic')),
  quality_tier text NOT NULL REFERENCES public.thirty_days_quality_tiers(quality_tier),
  days_per_episode integer NOT NULL DEFAULT 1 CHECK (days_per_episode IN (1, 2, 3, 5)),
  total_days integer NOT NULL DEFAULT 30 CHECK (total_days > 0),
  current_day integer NOT NULL DEFAULT 0 CHECK (current_day >= 0),
  current_episode integer NOT NULL DEFAULT 0 CHECK (current_episode >= 0),
  status text NOT NULL DEFAULT 'planning'
    CHECK (status IN ('planning', 'references', 'ready', 'generating', 'completed', 'failed')),
  master_story_bible jsonb NOT NULL DEFAULT '{}'::jsonb,
  hidden_future_beats jsonb NOT NULL DEFAULT '[]'::jsonb,
  reference_library jsonb NOT NULL DEFAULT '[]'::jsonb,
  current_story_state jsonb NOT NULL DEFAULT '{}'::jsonb,
  next_episode_tease text,
  cover_url text,
  setup_generation_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_active_at timestamptz NOT NULL DEFAULT now(),
  CHECK (current_day <= total_days),
  CHECK (jsonb_typeof(master_story_bible) = 'object'),
  CHECK (jsonb_typeof(hidden_future_beats) = 'array'),
  CHECK (jsonb_typeof(reference_library) = 'array'),
  CHECK (jsonb_array_length(reference_library) <= 10),
  CHECK (jsonb_typeof(current_story_state) = 'object')
);

CREATE TABLE public.thirty_days_series_episodes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  series_id uuid NOT NULL REFERENCES public.thirty_days_series(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  generation_id uuid,
  episode_number integer NOT NULL CHECK (episode_number > 0),
  start_day integer NOT NULL CHECK (start_day > 0),
  end_day integer NOT NULL CHECK (end_day >= start_day),
  title text NOT NULL,
  hook text NOT NULL,
  story_plan jsonb NOT NULL DEFAULT '{}'::jsonb,
  episode_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  cliffhanger text,
  next_episode_tease text,
  narration text,
  narration_take jsonb,
  thumbnail_url text,
  final_video_url text,
  status text NOT NULL DEFAULT 'generating'
    CHECK (status IN ('planning', 'generating', 'voiceover', 'stitching', 'completed', 'partial', 'failed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  UNIQUE (series_id, episode_number),
  UNIQUE (series_id, start_day, end_day),
  CHECK (jsonb_typeof(story_plan) = 'object'),
  CHECK (jsonb_typeof(episode_summary) = 'object')
);

ALTER TABLE public.thirty_days_generations
  ADD COLUMN IF NOT EXISTS generation_mode text NOT NULL DEFAULT 'single'
    CHECK (generation_mode IN ('single', 'series_setup', 'series_episode')),
  ADD COLUMN IF NOT EXISTS series_id uuid REFERENCES public.thirty_days_series(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS series_episode_id uuid REFERENCES public.thirty_days_series_episodes(id) ON DELETE CASCADE;

ALTER TABLE public.thirty_days_generation_assets
  ADD COLUMN IF NOT EXISTS retry_count integer NOT NULL DEFAULT 0 CHECK (retry_count BETWEEN 0 AND 1);

CREATE TABLE public.thirty_days_series_retry_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  generation_id uuid NOT NULL REFERENCES public.thirty_days_generations(id) ON DELETE CASCADE,
  asset_id uuid NOT NULL REFERENCES public.thirty_days_generation_assets(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  credits integer NOT NULL CHECK (credits > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (asset_id)
);
ALTER TABLE public.thirty_days_series_retry_ledger ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own 30 Days series retry ledger"
  ON public.thirty_days_series_retry_ledger FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);
REVOKE ALL ON TABLE public.thirty_days_series_retry_ledger FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.thirty_days_series_retry_ledger TO authenticated;

ALTER TABLE public.thirty_days_series
  ADD CONSTRAINT thirty_days_series_setup_generation_fkey
  FOREIGN KEY (setup_generation_id) REFERENCES public.thirty_days_generations(id) ON DELETE SET NULL;
ALTER TABLE public.thirty_days_series_episodes
  ADD CONSTRAINT thirty_days_series_episode_generation_fkey
  FOREIGN KEY (generation_id) REFERENCES public.thirty_days_generations(id) ON DELETE SET NULL;

CREATE INDEX thirty_days_series_user_active
  ON public.thirty_days_series (user_id, last_active_at DESC);
CREATE INDEX thirty_days_series_episodes_series_number
  ON public.thirty_days_series_episodes (series_id, episode_number DESC);
CREATE INDEX thirty_days_series_episodes_user_updated
  ON public.thirty_days_series_episodes (user_id, updated_at DESC);
CREATE UNIQUE INDEX thirty_days_series_one_open_episode
  ON public.thirty_days_series_episodes (series_id)
  WHERE status IN ('planning', 'generating', 'voiceover', 'stitching');
CREATE UNIQUE INDEX thirty_days_generations_series_episode_unique
  ON public.thirty_days_generations (series_episode_id)
  WHERE series_episode_id IS NOT NULL;

ALTER TABLE public.thirty_days_series ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.thirty_days_series_episodes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users read own 30 Days series"
  ON public.thirty_days_series FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);
CREATE POLICY "Users read own 30 Days series episodes"
  ON public.thirty_days_series_episodes FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);

DROP TRIGGER IF EXISTS set_thirty_days_series_updated_at ON public.thirty_days_series;
CREATE TRIGGER set_thirty_days_series_updated_at
  BEFORE UPDATE ON public.thirty_days_series
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS set_thirty_days_series_episode_updated_at ON public.thirty_days_series_episodes;
CREATE TRIGGER set_thirty_days_series_episode_updated_at
  BEFORE UPDATE ON public.thirty_days_series_episodes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

REVOKE ALL ON TABLE public.thirty_days_series FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.thirty_days_series_episodes FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.thirty_days_series TO authenticated;
GRANT SELECT ON TABLE public.thirty_days_series_episodes TO authenticated;

-- Service-only setup reservation. The master planner supplies structured
-- creative data, while this function independently resolves plan eligibility,
-- quality pricing, reference count, ownership, and the amount deducted.
CREATE OR REPLACE FUNCTION public.begin_thirty_days_series(
  p_user_id uuid,
  p_universe text,
  p_premise text,
  p_visual_style text,
  p_quality_tier text,
  p_days_per_episode integer,
  p_master_plan jsonb
)
RETURNS public.thirty_days_series
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_series public.thirty_days_series;
  v_generation public.thirty_days_generations;
  v_tier public.thirty_days_quality_tiers;
  v_plan_code text;
  v_plan_rank integer;
  v_min_rank integer;
  v_refs jsonb := COALESCE(p_master_plan->'visualReferences', '[]'::jsonb);
  v_ref jsonb;
  v_ref_count integer := jsonb_array_length(v_refs);
  v_setup_service integer := 12;
  v_total integer;
  v_style text := COALESCE(NULLIF(trim(p_visual_style), ''), 'auto');
BEGIN
  IF p_user_id IS NULL THEN RAISE EXCEPTION 'USER_REQUIRED'; END IF;
  IF length(trim(COALESCE(p_universe, ''))) < 2 THEN RAISE EXCEPTION 'UNIVERSE_REQUIRED'; END IF;
  IF length(trim(COALESCE(p_premise, ''))) < 5 THEN RAISE EXCEPTION 'PREMISE_REQUIRED'; END IF;
  IF p_days_per_episode NOT IN (1, 2, 3, 5) THEN RAISE EXCEPTION 'INVALID_DAYS_PER_EPISODE'; END IF;
  IF v_style NOT IN ('auto', 'cinematic_3d', 'anime_accurate', 'realistic', 'dark_cinematic') THEN
    RAISE EXCEPTION 'INVALID_VISUAL_STYLE';
  END IF;
  IF v_ref_count <> 5 THEN RAISE EXCEPTION 'INVALID_REFERENCE_COUNT'; END IF;
  IF jsonb_typeof(COALESCE(p_master_plan->'seriesBible', '{}'::jsonb)) <> 'object'
     OR jsonb_typeof(COALESCE(p_master_plan->'hiddenFutureBeats', '[]'::jsonb)) <> 'array' THEN
    RAISE EXCEPTION 'INVALID_SERIES_BIBLE';
  END IF;
  IF (SELECT count(DISTINCT value->>'id') FROM jsonb_array_elements(v_refs) refs(value)) <> v_ref_count
     OR EXISTS (SELECT 1 FROM jsonb_array_elements(v_refs) refs(value)
                WHERE length(trim(COALESCE(value->>'id', ''))) = 0) THEN
    RAISE EXCEPTION 'INVALID_REFERENCE_IDS';
  END IF;

  SELECT * INTO v_tier FROM public.thirty_days_quality_tiers
  WHERE quality_tier = p_quality_tier FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'INVALID_QUALITY_TIER'; END IF;

  SELECT lower(COALESCE(plan_code, 'free')) INTO v_plan_code
  FROM public.profiles WHERE id = p_user_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'PROFILE_NOT_FOUND'; END IF;
  v_plan_rank := CASE v_plan_code WHEN 'generative' THEN 3 WHEN 'pro' THEN 2
    WHEN 'starter' THEN 1 WHEN 'affiliate' THEN 1 ELSE 0 END;
  v_min_rank := CASE v_tier.min_plan WHEN 'generative' THEN 3 WHEN 'pro' THEN 2 ELSE 1 END;
  IF v_plan_rank < v_min_rank THEN RAISE EXCEPTION 'PLAN_UPGRADE_REQUIRED'; END IF;

  v_total := v_ref_count * v_tier.reference_cost_credits + v_setup_service;
  PERFORM public.deduct_credits(p_user_id, v_total);

  INSERT INTO public.thirty_days_series (
    user_id, title, universe, premise, visual_style, quality_tier,
    days_per_episode, status, master_story_bible, hidden_future_beats
  ) VALUES (
    p_user_id, COALESCE(NULLIF(trim(p_master_plan->>'title'), ''), '30 Days in ' || trim(p_universe)),
    trim(p_universe), trim(p_premise), v_style, v_tier.quality_tier,
    p_days_per_episode, 'references', p_master_plan->'seriesBible',
    COALESCE(p_master_plan->'hiddenFutureBeats', '[]'::jsonb)
  ) RETURNING * INTO v_series;

  INSERT INTO public.thirty_days_generations (
    user_id, universe, ai_idea_mode, premise, title, hook, camera_mode,
    world_bible, visual_references, scenes, quality_tier, visual_style,
    status, reserved_credits, reservation_status, voice_generation_limit,
    service_credits_charged, generation_mode, series_id
  ) VALUES (
    p_user_id, v_series.universe, true, v_series.premise, v_series.title,
    COALESCE(p_master_plan->>'hook', v_series.premise),
    CASE WHEN p_master_plan->>'cameraMode' = 'first_person' THEN 'first_person' ELSE 'third_person' END,
    COALESCE(p_master_plan->'worldBible', '{}'::jsonb), v_refs, '[]'::jsonb,
    v_tier.quality_tier, v_style, 'references', v_total, 'reserved', 1,
    v_setup_service, 'series_setup', v_series.id
  ) RETURNING * INTO v_generation;

  UPDATE public.thirty_days_series SET setup_generation_id = v_generation.id WHERE id = v_series.id
  RETURNING * INTO v_series;

  FOR v_ref IN SELECT value FROM jsonb_array_elements(v_refs) LOOP
    INSERT INTO public.thirty_days_generation_assets (
      generation_id, user_id, asset_key, asset_type, reference_id, tool_key, cost_credits
    ) VALUES (
      v_generation.id, p_user_id, 'reference:' || (v_ref->>'id'), 'reference_image',
      v_ref->>'id', v_tier.reference_tool_key, v_tier.reference_cost_credits
    );
  END LOOP;
  INSERT INTO public.thirty_days_credit_ledger (generation_id, user_id, operation, credits)
  VALUES (v_generation.id, p_user_id, 'reserve', v_total);
  RETURN v_series;
END;
$$;

-- Called after setup reference jobs have settled. It copies only successfully
-- persisted references from the linked generation into the reusable library.
CREATE OR REPLACE FUNCTION public.complete_thirty_days_series_setup(p_series_id uuid)
RETURNS public.thirty_days_series
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_series public.thirty_days_series;
  v_generation public.thirty_days_generations;
  v_refs jsonb;
BEGIN
  SELECT * INTO v_series FROM public.thirty_days_series
  WHERE id = p_series_id AND user_id = auth.uid() FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'SERIES_NOT_FOUND'; END IF;
  SELECT * INTO v_generation FROM public.thirty_days_generations
  WHERE id = v_series.setup_generation_id FOR UPDATE;
  IF NOT FOUND OR v_generation.reservation_status = 'reserved' THEN RAISE EXCEPTION 'SETUP_NOT_SETTLED'; END IF;
  v_refs := COALESCE(v_generation.visual_references, '[]'::jsonb);
  IF jsonb_array_length(v_refs) NOT BETWEEN 4 AND 6
     OR EXISTS (SELECT 1 FROM jsonb_array_elements(v_refs) refs(value)
                WHERE length(COALESCE(value->>'imageUrl', '')) = 0) THEN
    RAISE EXCEPTION 'SETUP_REFERENCES_INCOMPLETE';
  END IF;
  UPDATE public.thirty_days_series
  SET reference_library = v_refs, status = 'ready',
      cover_url = COALESCE(v_refs->0->>'imageUrl', cover_url), last_active_at = now()
  WHERE id = p_series_id RETURNING * INTO v_series;
  RETURN v_series;
END;
$$;

-- Service-only progressive episode reservation. It locks the series row,
-- proves the requested range is exactly next, and derives every price from
-- the quality table. Existing persistent references are free to reuse; only
-- newly requested references become billable assets.
CREATE OR REPLACE FUNCTION public.begin_thirty_days_series_episode(
  p_user_id uuid,
  p_series_id uuid,
  p_episode_plan jsonb
)
RETURNS public.thirty_days_series_episodes
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_series public.thirty_days_series;
  v_episode public.thirty_days_series_episodes;
  v_generation public.thirty_days_generations;
  v_tier public.thirty_days_quality_tiers;
  v_plan_code text;
  v_voice_limit integer;
  v_service_cost integer;
  v_scene_count integer := jsonb_array_length(COALESCE(p_episode_plan->'scenes', '[]'::jsonb));
  v_new_refs jsonb := COALESCE(p_episode_plan->'newReferences', '[]'::jsonb);
  v_all_refs jsonb;
  v_ref jsonb;
  v_scene jsonb;
  v_scene_index integer;
  v_start integer := COALESCE((p_episode_plan->>'startDay')::integer, 0);
  v_end integer := COALESCE((p_episode_plan->>'endDay')::integer, 0);
  v_episode_number integer;
  v_total integer;
  v_dependencies text[];
BEGIN
  SELECT * INTO v_series FROM public.thirty_days_series
  WHERE id = p_series_id AND user_id = p_user_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'SERIES_NOT_FOUND'; END IF;
  IF v_series.status NOT IN ('ready', 'generating') THEN RAISE EXCEPTION 'SERIES_NOT_READY'; END IF;
  IF v_series.current_day >= v_series.total_days THEN RAISE EXCEPTION 'SERIES_COMPLETE'; END IF;
  IF v_start <> v_series.current_day + 1
     OR v_end <> LEAST(v_series.total_days, v_start + v_series.days_per_episode - 1) THEN
    RAISE EXCEPTION 'INVALID_EPISODE_RANGE';
  END IF;
  IF v_scene_count <> 7 THEN RAISE EXCEPTION 'INVALID_EPISODE_SCENE_COUNT'; END IF;
  IF jsonb_array_length(v_new_refs) > 2
     OR jsonb_array_length(v_series.reference_library) + jsonb_array_length(v_new_refs) > 10 THEN
    RAISE EXCEPTION 'REFERENCE_LIBRARY_LIMIT';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(v_new_refs) refs(value)
    WHERE length(trim(COALESCE(value->>'id', ''))) = 0
  ) OR (
    SELECT count(DISTINCT value->>'id')
    FROM jsonb_array_elements(v_new_refs) refs(value)
  ) <> jsonb_array_length(v_new_refs) OR EXISTS (
    SELECT 1
    FROM jsonb_array_elements(v_new_refs) new_refs(value)
    WHERE EXISTS (
      SELECT 1
      FROM jsonb_array_elements(v_series.reference_library) existing_refs(existing)
      WHERE existing->>'id' = value->>'id'
    )
  ) THEN
    RAISE EXCEPTION 'INVALID_NEW_REFERENCE_IDS';
  END IF;
  IF EXISTS (SELECT 1 FROM public.thirty_days_series_episodes
             WHERE series_id = p_series_id AND status IN ('planning','generating','voiceover','stitching')) THEN
    RAISE EXCEPTION 'EPISODE_ALREADY_ACTIVE';
  END IF;

  SELECT * INTO v_tier FROM public.thirty_days_quality_tiers
  WHERE quality_tier = v_series.quality_tier FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'INVALID_QUALITY_TIER'; END IF;
  SELECT lower(COALESCE(plan_code, 'free')) INTO v_plan_code FROM public.profiles WHERE id = p_user_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'PROFILE_NOT_FOUND'; END IF;
  v_voice_limit := CASE v_plan_code WHEN 'generative' THEN 5 WHEN 'pro' THEN 3 ELSE 2 END;
  v_service_cost := 12 + v_voice_limit * 3;
  v_total := jsonb_array_length(v_new_refs) * v_tier.reference_cost_credits
    + v_scene_count * v_tier.image_cost_credits
    + v_scene_count * v_tier.video_cost_credits
    + v_service_cost;
  PERFORM public.deduct_credits(p_user_id, v_total);

  v_episode_number := v_series.current_episode + 1;
  INSERT INTO public.thirty_days_series_episodes (
    series_id, user_id, episode_number, start_day, end_day, title, hook,
    story_plan, cliffhanger, next_episode_tease, status
  ) VALUES (
    p_series_id, p_user_id, v_episode_number, v_start, v_end,
    COALESCE(NULLIF(trim(p_episode_plan->>'title'), ''), 'Days ' || v_start || '–' || v_end),
    COALESCE(NULLIF(trim(p_episode_plan->>'hook'), ''), 'This is Day ' || v_start || ' of 30.'),
    p_episode_plan, p_episode_plan->>'cliffhanger', p_episode_plan->>'nextEpisodeTease', 'generating'
  ) RETURNING * INTO v_episode;

  v_all_refs := v_series.reference_library || v_new_refs;
  INSERT INTO public.thirty_days_generations (
    user_id, universe, ai_idea_mode, premise, title, hook, camera_mode,
    world_bible, visual_references, scenes, quality_tier, visual_style,
    status, reserved_credits, reservation_status, voice_generation_limit,
    service_credits_charged, generation_mode, series_id, series_episode_id
  ) VALUES (
    p_user_id, v_series.universe, true, v_series.premise, v_episode.title, v_episode.hook,
    COALESCE(NULLIF(p_episode_plan->>'cameraMode', ''), 'third_person'),
    COALESCE(p_episode_plan->'worldBible', v_series.master_story_bible->'worldBible'),
    v_all_refs, p_episode_plan->'scenes', v_tier.quality_tier, v_series.visual_style,
    'scenes', v_total, 'reserved', v_voice_limit, v_service_cost,
    'series_episode', p_series_id, v_episode.id
  ) RETURNING * INTO v_generation;
  UPDATE public.thirty_days_series_episodes SET generation_id = v_generation.id
  WHERE id = v_episode.id RETURNING * INTO v_episode;
  UPDATE public.thirty_days_series SET status = 'generating', last_active_at = now() WHERE id = p_series_id;

  FOR v_ref IN SELECT value FROM jsonb_array_elements(v_new_refs) LOOP
    INSERT INTO public.thirty_days_generation_assets (
      generation_id, user_id, asset_key, asset_type, reference_id, tool_key, cost_credits
    ) VALUES (v_generation.id, p_user_id, 'reference:' || (v_ref->>'id'), 'reference_image',
      v_ref->>'id', v_tier.reference_tool_key, v_tier.reference_cost_credits);
  END LOOP;

  FOR v_scene IN SELECT value FROM jsonb_array_elements(p_episode_plan->'scenes') LOOP
    v_scene_index := (v_scene->>'index')::integer;
    IF v_scene_index NOT BETWEEN 0 AND 6 THEN RAISE EXCEPTION 'INVALID_SCENE_INDEX'; END IF;
    SELECT COALESCE(array_agg('reference:' || value ORDER BY ordinality), '{}'::text[])
    INTO v_dependencies
    FROM jsonb_array_elements_text(COALESCE(v_scene->'referenceIds', '[]'::jsonb))
      WITH ORDINALITY ids(value, ordinality);
    IF cardinality(v_dependencies) NOT BETWEEN 1 AND 3 THEN RAISE EXCEPTION 'INVALID_SCENE_REFERENCES'; END IF;
    IF EXISTS (SELECT 1 FROM unnest(v_dependencies) dependency
               WHERE NOT EXISTS (SELECT 1 FROM jsonb_array_elements(v_all_refs) refs(value)
                                 WHERE 'reference:' || (value->>'id') = dependency)) THEN
      RAISE EXCEPTION 'INVALID_SCENE_REFERENCE';
    END IF;
    INSERT INTO public.thirty_days_generation_assets (
      generation_id, user_id, asset_key, asset_type, scene_index,
      dependency_keys, tool_key, cost_credits
    ) VALUES (v_generation.id, p_user_id, 'scene:' || v_scene_index || ':image',
      'scene_image', v_scene_index, v_dependencies, v_tier.image_tool_key, v_tier.image_cost_credits);
    INSERT INTO public.thirty_days_generation_assets (
      generation_id, user_id, asset_key, asset_type, scene_index,
      dependency_keys, tool_key, cost_credits
    ) VALUES (v_generation.id, p_user_id, 'scene:' || v_scene_index || ':video',
      'scene_video', v_scene_index, ARRAY['scene:' || v_scene_index || ':image'],
      v_tier.video_tool_key, v_tier.video_cost_credits);
  END LOOP;
  INSERT INTO public.thirty_days_credit_ledger (generation_id, user_id, operation, credits)
  VALUES (v_generation.id, p_user_id, 'reserve', v_total);
  RETURN v_episode;
END;
$$;

-- Completion advances the series exactly once and stores structured memory
-- for the next planner. The summary is creative state only; billing and day
-- progression are derived from locked database rows.
CREATE OR REPLACE FUNCTION public.complete_thirty_days_series_episode(
  p_episode_id uuid,
  p_episode_summary jsonb,
  p_final_video_url text,
  p_thumbnail_url text
)
RETURNS public.thirty_days_series_episodes
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_episode public.thirty_days_series_episodes;
  v_series public.thirty_days_series;
  v_generation public.thirty_days_generations;
BEGIN
  SELECT * INTO v_episode FROM public.thirty_days_series_episodes
  WHERE id = p_episode_id AND user_id = auth.uid() FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'EPISODE_NOT_FOUND'; END IF;
  SELECT * INTO v_series FROM public.thirty_days_series WHERE id = v_episode.series_id FOR UPDATE;
  SELECT * INTO v_generation FROM public.thirty_days_generations WHERE id = v_episode.generation_id FOR UPDATE;
  IF v_generation.reservation_status = 'reserved' THEN RAISE EXCEPTION 'EPISODE_ASSETS_NOT_SETTLED'; END IF;
  IF length(trim(COALESCE(p_final_video_url, ''))) = 0 THEN RAISE EXCEPTION 'FINAL_VIDEO_REQUIRED'; END IF;
  IF v_episode.status = 'completed' THEN RETURN v_episode; END IF;
  IF v_episode.start_day <> v_series.current_day + 1 THEN RAISE EXCEPTION 'EPISODE_OUT_OF_ORDER'; END IF;
  IF jsonb_typeof(COALESCE(p_episode_summary, '{}'::jsonb)) <> 'object' THEN RAISE EXCEPTION 'INVALID_EPISODE_SUMMARY'; END IF;

  UPDATE public.thirty_days_series_episodes
  SET episode_summary = p_episode_summary, final_video_url = trim(p_final_video_url),
      thumbnail_url = NULLIF(trim(COALESCE(p_thumbnail_url, '')), ''), status = 'completed', completed_at = now(),
      narration = v_generation.narration_script, narration_take = v_generation.narration_take
  WHERE id = p_episode_id RETURNING * INTO v_episode;

  UPDATE public.thirty_days_series
  SET current_day = v_episode.end_day, current_episode = v_episode.episode_number,
      status = CASE WHEN v_episode.end_day >= total_days THEN 'completed' ELSE 'ready' END,
      current_story_state = p_episode_summary,
      next_episode_tease = COALESCE(NULLIF(v_episode.next_episode_tease, ''), p_episode_summary->>'cliffhanger'),
      reference_library = v_generation.visual_references,
      cover_url = COALESCE(NULLIF(trim(COALESCE(p_thumbnail_url, '')), ''), cover_url),
      last_active_at = now()
  WHERE id = v_series.id;
  RETURN v_episode;
END;
$$;

-- A failed Series animation was already refunded at settlement. Reopening its
-- one included retry re-deducts exactly that refunded asset cost, making the
-- user's net charge equal to the original episode price rather than charging
-- an additional video. The shared worker can then authorize another zero-job-
-- charge attempt against the reopened reservation.
CREATE OR REPLACE FUNCTION public.reopen_thirty_days_series_video_retry(
  p_generation_id uuid,
  p_scene_index integer
)
RETURNS public.thirty_days_generation_assets
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_generation public.thirty_days_generations;
  v_asset public.thirty_days_generation_assets;
BEGIN
  SELECT * INTO v_generation FROM public.thirty_days_generations
  WHERE id = p_generation_id AND user_id = auth.uid() AND generation_mode = 'series_episode'
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'GENERATION_NOT_FOUND'; END IF;
  SELECT * INTO v_asset FROM public.thirty_days_generation_assets
  WHERE generation_id = p_generation_id
    AND asset_key = 'scene:' || p_scene_index || ':video'
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'ASSET_NOT_FOUND'; END IF;
  IF v_asset.status NOT IN ('failed', 'canceled') OR v_asset.refunded_credits <> v_asset.cost_credits THEN
    RAISE EXCEPTION 'ASSET_NOT_REFUNDED';
  END IF;
  IF v_asset.retry_count >= 1 THEN RAISE EXCEPTION 'SERIES_RETRY_LIMIT_REACHED'; END IF;

  PERFORM public.deduct_credits(v_generation.user_id, v_asset.cost_credits);
  INSERT INTO public.thirty_days_series_retry_ledger (generation_id, asset_id, user_id, credits)
  VALUES (p_generation_id, v_asset.id, v_generation.user_id, v_asset.cost_credits);
  UPDATE public.thirty_days_generations
  SET reservation_status = 'reserved', refunded_credits = GREATEST(0, refunded_credits - v_asset.cost_credits),
      status = 'scenes'
  WHERE id = p_generation_id;
  UPDATE public.thirty_days_generation_assets
  SET retry_count = retry_count + 1, refunded_credits = 0, job_id = NULL,
      status = 'retrying', result_url = NULL, error = NULL
  WHERE id = v_asset.id RETURNING * INTO v_asset;
  UPDATE public.thirty_days_series_episodes SET status = 'generating'
  WHERE id = v_generation.series_episode_id;
  RETURN v_asset;
END;
$$;

-- Retry-aware settlement uses the difference from the currently recorded
-- refund. This makes settlement idempotent across one reopened Series retry
-- while keeping the original single-video behavior unchanged.
CREATE OR REPLACE FUNCTION public.settle_thirty_days_generation(p_generation_id uuid)
RETURNS public.thirty_days_generations
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_generation public.thirty_days_generations;
  v_changed integer := 1;
  v_nonterminal integer;
  v_succeeded integer;
  v_total integer;
  v_refund integer;
  v_refund_delta integer;
BEGIN
  SELECT * INTO v_generation FROM public.thirty_days_generations
  WHERE id = p_generation_id AND user_id = auth.uid() FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'GENERATION_NOT_FOUND'; END IF;
  IF v_generation.reservation_status <> 'reserved' THEN RETURN v_generation; END IF;

  UPDATE public.thirty_days_generation_assets AS asset
  SET status = CASE job.status WHEN 'succeeded' THEN 'succeeded' WHEN 'failed' THEN 'failed'
        WHEN 'canceled' THEN 'canceled' WHEN 'queued' THEN 'queued' ELSE 'running' END,
      result_url = job.result_url, error = job.error
  FROM public.jobs AS job
  WHERE asset.generation_id = p_generation_id AND asset.job_id = job.id
    AND NOT (asset.qa_status = 'failed' AND asset.qa_attempts >= 2);
  WHILE v_changed > 0 LOOP
    UPDATE public.thirty_days_generation_assets AS dependent
    SET status = 'failed', error = 'dependency_failed'
    WHERE dependent.generation_id = p_generation_id
      AND dependent.status IN ('planned', 'queued', 'retrying')
      AND EXISTS (SELECT 1 FROM public.thirty_days_generation_assets AS dependency
        WHERE dependency.generation_id = dependent.generation_id
          AND dependency.asset_key = ANY(dependent.dependency_keys)
          AND dependency.status IN ('failed', 'canceled'));
    GET DIAGNOSTICS v_changed = ROW_COUNT;
  END LOOP;
  SELECT count(*), count(*) FILTER (WHERE status = 'succeeded'),
    count(*) FILTER (WHERE status NOT IN ('succeeded','failed','canceled')),
    COALESCE(sum(cost_credits) FILTER (WHERE status IN ('failed','canceled')), 0)
  INTO v_total, v_succeeded, v_nonterminal, v_refund
  FROM public.thirty_days_generation_assets WHERE generation_id = p_generation_id;
  IF v_total = 0 THEN RAISE EXCEPTION 'GENERATION_ASSETS_MISSING'; END IF;
  IF v_nonterminal > 0 THEN RAISE EXCEPTION 'ASSETS_NOT_TERMINAL'; END IF;

  v_refund_delta := v_refund - v_generation.refunded_credits;
  IF v_refund_delta > 0 THEN
    UPDATE public.profiles SET credit_balance = credit_balance + v_refund_delta,
      credits_spent_today = GREATEST(0, COALESCE(credits_spent_today,0) - v_refund_delta)
    WHERE id = v_generation.user_id;
  END IF;
  INSERT INTO public.thirty_days_credit_ledger (generation_id,user_id,operation,credits)
  VALUES (p_generation_id,v_generation.user_id,'refund',v_refund)
  ON CONFLICT (generation_id,operation) DO UPDATE SET credits = EXCLUDED.credits;
  UPDATE public.thirty_days_generation_assets SET refunded_credits = CASE
    WHEN status IN ('failed','canceled') THEN cost_credits ELSE 0 END
  WHERE generation_id = p_generation_id;
  UPDATE public.thirty_days_generations
  SET refunded_credits = v_refund,
      reservation_status = CASE WHEN v_refund = reserved_credits THEN 'refunded' ELSE 'settled' END,
      status = CASE WHEN v_succeeded = v_total THEN 'voiceover' WHEN v_succeeded = 0 THEN 'failed' ELSE 'partial' END
  WHERE id = p_generation_id RETURNING * INTO v_generation;
  RETURN v_generation;
END;
$$;

REVOKE ALL ON FUNCTION public.begin_thirty_days_series(uuid,text,text,text,text,integer,jsonb)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.begin_thirty_days_series_episode(uuid,uuid,jsonb)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.complete_thirty_days_series_setup(uuid)
  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.complete_thirty_days_series_episode(uuid,jsonb,text,text)
  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.reopen_thirty_days_series_video_retry(uuid,integer)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.begin_thirty_days_series(uuid,text,text,text,text,integer,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.begin_thirty_days_series_episode(uuid,uuid,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_thirty_days_series_setup(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_thirty_days_series_episode(uuid,jsonb,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reopen_thirty_days_series_video_retry(uuid,integer) TO authenticated;
